### ISSUE TITLE
ghost create table error，can't find table

### ISSUE THREAD

**Issue by minicloudsky** [github/gh-ost#1008]
I used ghost to execute a ddl like create table xxx,however,I got an error
ERROR Cannot find table,what's the matter with this error ? is ghost must execute online ddl on an exist table ?

**Comment by shlomi-noach** [comment]
>  is ghost must execute online ddl on an exist table ?

Yes, indeed. `gh-ost` is only used for `ALTER` statements, not for `CREATE` statements.

**Comment by minicloudsky** [comment]
> > is ghost must execute online ddl on an exist table ?
> 
> Yes, indeed. `gh-ost` is only used for `ALTER` statements, not for `CREATE` statements.

thanks，I got it .
