### ISSUE TITLE
Migrator status should be sent to migrationContext logger

### ISSUE THREAD

**Issue by SocalNick** [github/gh-ost#1026]
We contributed a logging interface a while back in #789, unfortunately, it still took us a while to get back to using `GitHub/gh-ost` rather than our fork in our project. One of our users just pointed out they didn't see progress indicators. Turns out we missed this from our fork, we used to send the status messages through the migrationContext logger in addition to stdout.

I will submit a PR for this, thanks in advance for your consideration!

**Comment by Reynolds251** [comment]
> We contributed a logging interface a while back in #789, unfortunately, it still took us a while to get back to using `GitHub/gh-ost` rather than our fork in our project. One of our users just pointed out they didn't see progress indicators. Turns out we missed this from our fork, we used to send the status messages through the migrationContext logger in addition to stdout.
> 
> I will submit a PR for this, thanks in advance for your consideration!

**Comment by Reynolds251** [comment]
https://github.com/github/gh-ost/issues/1026#issue-998848520

**Comment by Reynolds251** [comment]
> We contributed a logging interface a while back in #789, unfortunately, it still took us a while to get back to using `GitHub/gh-ost` rather than our fork in our project. One of our users just pointed out they didn't see progress indicators. Turns out we missed this from our fork, we used to send the status messages through the migrationContext logger in addition to stdout.
> 
> I will submit a PR for this, thanks in advance for your consideration!

**Comment by dm-2** [comment]
:wave: @SocalNick Thanks for the PRs!

I like the simplicity of #1194, so I think this is the one to go for - I've run CI, and approved and merged the PR 🚀

Thanks again for your contribution!
