### ISSUE TITLE
Feasibility of PostgreSQL support

### ISSUE THREAD

**Issue by systemist** [github/gh-ost#1028]
Since GitHub presumably doesn't operate PostgreSQL servers, I am curious what the feasibility of supporting PostgreSQL online schema changes would be. I've only briefly looked through the code, but it seems like a ton of changes would need to be made to support PostgreSQL since this project seems pretty tightly coupled to MySQL syntax and binlog implementation, and ultimately making the code more abstract to support multiple databases might be too risky. If I'm interested in using the same approach for PostgreSQL, would a fork be preferred? Or is there interest with the contributors to accept changes to support PostgreSQL?

**Comment by shlomi-noach** [comment]
`gh-ost` is oriented towards MySQL in almost every aspect. I'd say it makes more sense to fork. Note: I'm the previous maintainer and do not speak for current maintainers.

**Comment by dpashkevich** [comment]
@systemist did you end up working on a PostgreSQL implementation? I'm interested too
