### ISSUE TITLE
Duplicate of  Luimoll-patch-2 #8

### ISSUE THREAD

**Issue by Luimoll** [github/gh-ost#1031]
Duplicate of  Luimoll-patch-2 (#8)

_Originally posted by @Luimoll in https://github.com/github/docs/issues/10465#issuecomment-932627885_

**Comment by Luimoll** [comment]
#1028 #1026 #1027

**Comment by Reynolds251** [comment]
> #1028 #1026 #1027

https://github.com/github/gh-ost/issues/1026#issue-998848520
