### ISSUE TITLE
gh-ost may lose data when performing DDL on mysql with semi-sync replication enabled

### ISSUE THREAD

**Issue by wangzihuacool** [github/gh-ost#1039]
We encountered a case of the gh-ost losing data. When perform DDL on a table in mysql with semi-sync replication enabled, we lost the max value which is inserted into the table right before gh-ost executing addDMLEventsListener().
### case: 
environment:
  gh-ost v1.1.2 
  MySQL 5.7.26 with semi-sync replication enabled and one semi-sync slave.

parameter:
  gh-ost: --allow-on-master
  MySQL:
    rpl_semi_sync_master_wait_point = AFTER_SYNC
    rpl_semi_sync_master_enabled             = 1
    rpl_semi_sync_master_timeout             = 50000

table defination:
```Create Table: CREATE TABLE `sbtest1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `k` int(11) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  `fcreate_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  PRIMARY KEY (`id`),
  KEY `k_1` (`k`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**gh-ost command:**
```gh-ost --initially-drop-socket-file --initially-drop-ghost-table --initially-drop-old-table --max-load=Threads_running=100 --critical-load=Threads_running=100  --critical-load-interval-millis=10000 --chunk-size=100 --max-lag-millis=10000 --host='127.0.0.1' --port=3306 --user=test --password=test --database='bbb' --table='sbtest1' --alter="ADD COLUMN newc7 VARCHAR(10) NOT NULL DEFAULT '';"  --allow-on-master  --cut-over=atomic --default-retries=360 --assume-rbr --serve-socket-file=/tmp/f9ad2bcf-67c0-40ff-911a-8b1630bc3d2a.sock --skip-foreign-key-checks --debug --execute
 ```

**lost data:**
```MySQL [bbb]> select id,k,fcreate_time from _sbtest1_del where id not in (select id from sbtest1);
+------+-------+-------------------------+
| id   | k     | fcreate_time            |
+------+-------+-------------------------+
| 3297 | 92998 | 2021-10-24 12:59:43.134 |
```
gh-ost debug log:
```2021-10-24 12:59:43 DEBUG Potential unique keys in _sbtest1_gho: [PRIMARY (auto_increment): [id]; has nullable: false]
2021-10-24 12:59:43 INFO Chosen shared unique key is PRIMARY
2021-10-24 12:59:43 INFO Shared columns are id,k,c,pad,fcreate_time,newc7
2021-10-24 12:59:43 INFO Listening on unix socket file: /tmp/f9ad2bcf-67c0-40ff-911a-8b1630bc3d2a.sock
2021-10-24 12:59:43 DEBUG Reading migration range according to key: PRIMARY
2021-10-24 12:59:43 INFO Migration min values: [1]
2021-10-24 12:59:43 DEBUG Reading migration range according to key: PRIMARY
2021-10-24 12:59:43 INFO Migration max values: [3296]
2021-10-24 12:59:43 INFO Waiting for first throttle metrics to be collected
2021-10-24 12:59:43 INFO First throttle metrics collected
2021-10-24 12:59:43 DEBUG Operating until row copy is complete
```
general_log:
```2021-10-24T12:59:43.134752+08:00        45921456 Query  INSERT INTO sbtest1 (id, k, c, pad) VALUES (3297, 92998, '89022776681-93700450025-43617159868-10064230083-89360585583-73486929941-20100518753-63717928781-08418935310-01543590560', '11734872257-20273602703-16476939902-49341727995-89647541041')

2021-10-24T12:59:43.138023+08:00        45921501 Query  select /* gh-ost `bbb`.`sbtest1` */ `id`
                                from
                                        `bbb`.`sbtest1`
                                order by
                                        `id` asc
                                limit 1
2021-10-24T12:59:43.138264+08:00        45921501 Query  select /* gh-ost `bbb`.`sbtest1` */ `id`
                                from
                                        `bbb`.`sbtest1`
                                order by
                                        `id` desc
                                limit 1
```
MySQL processlist info:
```136459580       test    127.0.0.1:11325      NULL    Query   0       Waiting for semi-sync ACK from slave    COMMIT```

### Reason why data is lost
Transaction in MySQL master with a semi-sync slave may encouter 'Waiting for semi-sync ACK from slave' in commit phase, and it may take a while before transaction finnally succeed commiting. In the above case, the insert of id=3297 execute and commit before gh-ost addDMLEventsListener(), the binlog event has been sync to binlog and send to slaves. But for some reason, mysql master did not recieve the ACK from semi-sync slave and the transaction is blocked. the transaction with id=3297 is invisible to gh-ost thread executing query of ReadMigrationRangeValues. gh-ost got the max value is id=3296. Thus, the row with id=3297 has neither been notified to DMLListener nor copyed to _gho table. It's lost.

### Fix for it
Just add a read lock to the query in ReadMigrationRangeValues. If min/max value of the uniquekey was changed by another transaction that has not yet committed, query just waits until that transaction ends and then uses the latest values.

```	query := fmt.Sprintf(`
      select /* gh-ost %s.%s */ %s
				from
					%s.%s
				order by
					%s
				limit 1 lock in share mode```

**Comment by shaohk** [comment]
https://github.com/github/gh-ost/pull/1054
No need to use lock.
 And add a heartbeat between the `addDMLEventsListener` and `ReadMigrationRangeValues` to fix this bug.

**Comment by Ualidali21** [comment]
😓

**Comment by tivenwang** [comment]
> 
rowcopy是分批次的。
如果update的数据已经rowcopy过了，事务依然是会丢失的。

**Comment by wangzihuacool** [comment]
> > 
> 
> rowcopy是分批次的。 如果update的数据已经rowcopy过了，事务依然是会丢失的。

no data will be lost when adding a read lock to the query in ReadMigrationRangeValues

**Comment by dibrother** [comment]
Will this problem be fixed?

**Comment by timvaillancourt** [comment]
@wangzihuacool / @zhongliangkang / @dibrother it is likely this is resolved by the merge of https://github.com/github/gh-ost/pull/1141

Please lookout for an upcoming 1.1.5 release that will have this change included. Any feedback is appreciated!

**Comment by timvaillancourt** [comment]
I believe this issue was resolved by https://github.com/github/gh-ost/pull/1141. Closing
