### ISSUE TITLE
[Question] What if BinLog has been applied before data insert?

### ISSUE THREAD

**Issue by zkEloHub** [github/gh-ost#1062]
Hi,
I think of such a scenario, it contains the following steps：

1. select rows from the original table，for example, include the **record with id=1** (rowcopy behavior)

2. then someone update this record on the original table

3. **the relevant binlog event is applied on the gh-ost table (extreme case)，and affectedRows==0 of course**

4. insert this record into the gh-ost table  this time (rowcopy behavior)

5. and we permanently inserted this outdated data in gh-ost table

Forgive my bad English，thanks sincerely

**Comment by shaohk** [comment]
![image](https://user-images.githubusercontent.com/16531687/144697761-a360c044-5631-4569-a5e7-73a443988583.png)

Look here.

**Comment by zkEloHub** [comment]
> ![image](https://user-images.githubusercontent.com/16531687/144697761-a360c044-5631-4569-a5e7-73a443988583.png)
> 
> Look here.

Thank you for your answer
