### ISSUE TITLE
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by FoundationPresent** [github/gh-ost#1067]
Thanks for opening this issue. A GitHub docs team-mate should be by to give feedback soon. In the meantime, check out the [contributing guidelines](https://github.com/github/docs/blob/main/PARTICIPATING.md).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/13044#issuecomment-995523335_

**Comment by timvaillancourt** [comment]
@FoundationPresent this is a final warning to stop spamming this repo with garbage

Any future spam will have repercussions
