### ISSUE TITLE
wave flag white or transgender?

### ISSUE THREAD

**Issue by FoundationPresent** [github/gh-ost#1068]
https://github.com/googlefonts/noto-emoji/blob/main/.gitignore
‍‍‍‍‍‍‍‍‍‍⚲⚲⚲⚲⚲⚲⚲⚲⚲⚲⚲⚲ neutral or nuetrer? 🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️This is not transgender or trigender!!!!! is it? well, its transexuality as well. Hetrosexuality as well, not homosexuals or transexuals...is it not? Problem and i'm just the issuer, just a nuetral man or a child or a kid. clone molester as well, predator for sure......

**Comment by FoundationPresent** [comment]
Figure it in and help him make sure and I'll make sense of the it of Richie

**Comment by timvaillancourt** [comment]
@FoundationPresent please stop spamming this repo with garbage. Your account will be reported if this continues

**Comment by FoundationPresent** [comment]
> https://github.com/googlefonts/noto-emoji/blob/main/.gitignore
> ‍‍‍‍‍‍‍‍‍‍⚲⚲⚲⚲⚲⚲⚲⚲⚲⚲⚲⚲ neutral or nuetrer? 🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️This is not transgender or trigender!!!!! is it? well, its transexuality as well. Hetrosexuality as well, not homosexuals or transexuals...is it not? Problem and i'm just the issuer, just a nuetral man or a child or a kid. clone molester as well, predator for sure......

It's AGender the ReGenderedless. Both Masculine and Feminine Words of English.
