### ISSUE TITLE
Trying to get in touch regarding security matter

### ISSUE THREAD

**Issue by dwisiswant0** [github/gh-ost#1071]
Hi,

I found a potential vulnerability in this project. Since this project doesn't have its own `SECURITY.md`; and when I see the [security policy](https://github.com/github/gh-ost/security/policy) that this repository is not covered by the [bug bounty program](https://bounty.github.com/), so what are the proper steps/instructions to responsibly disclose the details?

Thank you for your consideration, and I look forward to hearing from you!

**Comment by rashiq** [comment]
Hi @dwisiswant0,
Thanks for reaching out! 

Can you please email us at `rashiq@github.com` with `database-infrastructure@github.com` in CC?  

Thank you very much.

**Comment by dwisiswant0** [comment]
Thank you for the response, @rashiq. Will be in touch soon.

**Comment by dwisiswant0** [comment]
Looks like my mail bounced due to organizational settings.

Can you draft [Security Advisories](https://github.com/github/gh-ost/security/advisories) and invite me in to further disclose and discuss the vulnerability details and potential fix, @rashiq?

Thanks!

**Comment by dwisiswant0** [comment]
Thanks for drafting!
