### ISSUE TITLE
Allow customizing gh-ost-on-status hook interval

### ISSUE THREAD

**Issue by tknodell-recurly** [github/gh-ost#1082]
We'd like to customize how often the `gh-ost-on-status` hook is called
Right now it looks like its [hardcoded to 60 seconds](https://github.com/github/gh-ost/blob/d6c83638d70dbfdad9e076ee61f8bbf062e09129/go/logic/migrator.go#L1019-L1021)

We'd like to make this a flag, so we can call our script to post status to slack at longer intervals
Happy to open a PR for this

**Comment by dm-2** [comment]
PR merged 🚀
