### ISSUE TITLE
Can the original table & ghost table swap happen manually? 

### ISSUE THREAD

**Issue by geddamurisatish** [github/gh-ost#1093]
> This is the place to report a bug, ask a question, or suggest an enhancement.

> This is also the place to make a discussion before creating a PR.

> If this is a bug report, please provide a test case (e.g., your table definition and gh-ost command) and the error output.

> Please use markdown to format code or SQL: https://guides.github.com/features/mastering-markdown/

> Please label the issue on the right (bug, enhancement, question, etc.).

> And please understand if this issue is not addressed immediately or in a timeframe you were expecting.

> Thank you!

**Comment by dm-2** [comment]
The [`--postpone-cut-over-flag-file`](https://github.com/github/gh-ost/blob/master/doc/command-line-flags.md#postpone-cut-over-flag-file) (see [here](https://github.com/github/gh-ost/blob/master/doc/cheatsheet.md#a-connect-to-replica-migrate-on-master) for an example of its syntax) option will do what you're after 👍

I'll close this as answered, feel free to re-open if you have any follow-up questions!

**Comment by geddamurisatish** [comment]
Thanks a lot @dm-2 , that worked for me .
