### ISSUE TITLE
How does gh-ost handle system versioned tables?

### ISSUE THREAD

**Issue by tgross35** [github/gh-ost#1094]
Newer versions of MariaDB and MySQL support `WITH SYSTEM VERSIONING` which tracks table changes. Unfortunately, what happens with this data is somewhat obscured. I know older dump tools don't support anything with the history, but mariabackup (which works with binlogs) does.

Has gh-ost been tested on system versioned tables yet? I'm wondering if their unique operation causes any problems.

**Comment by timvaillancourt** [comment]
@tgross35 at this time `gh-ost` is not aware of `WITH SYSTEM VERSIONING` and I'm not aware of any specific testing

It's unclear how `gh-ost` will function with the use of this feature

**Comment by tgross35** [comment]
@timvaillancourt I guess I stand corrected, could have sworn I saw it was in MySQL now but I must have made that up. Per page 44 on [this slideshow](https://modern-sql.com/slides/pgcon-2018-gap-analysis.pdf) it looks like only Maria and MS SQL support it.

Rereading the gh-ost operation, it seems like it actually probably would work by default since my binlog replicas don’t have a problem.

I’m sure it’s in the MySQL roadmap (Postgres is for sure but not relevant here) so could be interesting to test with Maria. I’m sure you’ll love system & application versioning at GH when it hits My, triggerless database history has been awesome to use from my experience.

**Comment by dm-2** [comment]
It looks like this is answered, feel free to re-open if any follow up questions 👍
