### ISSUE TITLE
gh-ost doesn't have binaries for M1 mac

### ISSUE THREAD

**Issue by jecepeda** [github/gh-ost#1105]
Hi everyone,

I went to releases in order to download the binary for gh-ost and I didn't found any binary for darwin arm64 architecture.

Then, I tried to download this repository to build it myself, but it seems that the compiling process downloads a supported go version if the one we have in our machine is not supported, finding that it always downloads the go binary for amd64 (for linux and osx).

Is it planned to give support for arm64 binaries (either on linux/osx)? I'm open to help on this issue and put a PR if you like.

Thanks in advance

**Comment by timvaillancourt** [comment]
@jecepeda I don't think there were plans to add this but I'm not opposed considering Mac OSX is already supported

Any thoughts @dm-2 / @rashiq?

**Comment by dm-2** [comment]
I'm happy with adding `arm64` support, a PR would be very helpful 🙂

We use [`build.sh`](https://github.com/github/gh-ost/blob/master/build.sh) for generating `gh-ost` releases, it should be fairly straightforward to add `arm64` to this.

**Comment by jecepeda** [comment]
Perfect!

**Comment by dm-2** [comment]
I've added a macOS `arm64` binary to the [v1.1.4 release](https://github.com/github/gh-ost/releases/tag/v1.1.4), thanks for your contribution @jecepeda - much appreciated!

I'll close this as completed, but feel free to re-open if needed 🙂
