### ISSUE TITLE
printStatus causes a divide by zero error

### ISSUE THREAD

**Issue by ethankhall** [github/gh-ost#1117]
We're using gh-ost as a library, and testing 8f361f6445c2fe1d830b053e315a70a69d60e73f
I noticed that our test suite fails with

```
Unhandled error
panic: runtime error: integer divide by zero
Location
github.com/github/gh-ost/go/logic/migrator.go:1019 - (*Migrator).printStatus
```

It looks like when https://github.com/github/gh-ost/commit/fbb53f4b04359600a1b784a22803eadbfbb6a86c
was introduced if `HooksStatusIntervalSec` is set to 0, this panic will happen.

**Comment by ninest** [comment]
I was getting the same error error trying to run gh-ost as a library: `panic: runtime error: integer divide by zero`. It is necessary to set the interval

```go
// Cannot be 0
migrationContext.HooksStatusIntervalSec = 1
```
