### ISSUE TITLE
Timestamp old table with a later time value

### ISSUE THREAD

**Issue by vbalys** [github/gh-ost#1133]
We are using `--timestamp-old-table` switch for our migrations. In addition, we have background jobs that drop old tables after a certain period of time. This is done in order to let table "cool down" to avoid InnoDB locks. We are consulting timestamp in table name to decide if it is already safe to finally drop it.

The obvious problem for us is that [timestamp is of the migration start](https://github.com/github/gh-ost/blob/ed46138c06430421b44fe285a26a44398b256a1c/go/base/context.go#L316). In case of a long (multiple days) migration, this timestamp provides no information of when data from the original table was used last.

There are multiple possible solutions to this:
- Use "safe" grace period before dropping table. Not really suitable for us, though, as we have quite a lot of long-running migrations and some big tables, and we want to cleanup in a couple of days after migration, not weeks or months.
- Use other means to decide when table is safe to be dropped instead of consulting timestamp in the table name. Likely a very sensitive option, but we like current solution based on timestamp too much :grin:, and we apply it in other places, not only in `gh-ost` migrations.
- Probably many other ones ...

Another option is to add capability (probably via additional modifying switch next to `--timestamp-old-table`) to use a different timestamp, likely [one of those](https://github.com/github/gh-ost/blob/ed46138c06430421b44fe285a26a44398b256a1c/go/base/context.go#L176-L178). This way old table name would reflect not the migration start moment but a moment closer to the cut-over and the factual "deprecation" of the table. 

The obvious downside would be that these timestamps are set rather late in the process, so old table name would not be defined up to that moment. This could, for example, affect hooks that make use of [old table name env variable](https://github.com/github/gh-ost/blob/ed46138c06430421b44fe285a26a44398b256a1c/go/logic/hooks.go#L54) earlier in the process, as this env variable would not be set.

Before continuing with this idea, I wanted to check with you if this capability is worth the effort of further investigation and attempts to raise PR, having in mind its deficiencies and limitations for its usage. It would be surely useful to us, so we are rather motivated to implement it.

Thanks in advance for your input.

**Comment by timvaillancourt** [comment]
> We are using `--timestamp-old-table` switch for our migrations. In addition, we have background jobs that drop old tables after a certain period of time. This is done in order to let table "cool down" to avoid InnoDB locks

@vbalys 👋 right, it seems `.GetOldTableName()` uses the "start time" instead of "now" time. It might be possible to add a feature to do that but I'm not sure how it would affect users of hooks, as you mentioned

To me the path of least resistance might be the `gh-ost` changelog (`_ghc`) table. I'm curious if your tool could be modified to `SELECT` from the changelog table to find the timestamp you need? I believe all changelog rows are timestamped

As an example, but just BEFORE the atomic rename [an `AllEventsUpToLockProcessed ` event is written to the changelog table](https://github.com/github/gh-ost/blob/master/go/logic/migrator.go#L560-L564). It would be pretty trivial to fire a similar changelog event (like `CutoverComplete`), perhaps [in a function like `.handleCutOverResult()`](https://github.com/github/gh-ost/blob/master/go/logic/migrator.go#L443-L471). Writing that event is harmless, so it could easily become default behaviour 🤔

**Comment by timvaillancourt** [comment]
> Writing that event is harmless, so it could easily become default behaviour 🤔

Correction here, for this to be harmless [`.onChangelogStateEvent()`](https://github.com/github/gh-ost/blob/master/go/logic/migrator.go#L217-L241) would need to be aware of the new event type and no-op on it

**Comment by timvaillancourt** [comment]
@vbalys I figured a new changelog state is useful in general/regardless, so I've made this PR to add that: https://github.com/github/gh-ost/pull/1134

**Comment by vbalys** [comment]
@timvaillancourt Thanks for the suggestion. I think this could actually work as we keep `_ghc` table around after migration, so could in theory query it to get the needed data.

**Comment by dm-2** [comment]
@vbalys

Would using a `gh-ost-on-success` hook to run `rename table ${GH_OST_OLD_TABLE_NAME} to ${GH_OST_OLD_TABLE_NAME}_${SOME_TIMESTAMP}` do what you're after?

The `onSuccess()` hook is the [last](https://github.com/github/gh-ost/blob/02258ac15dc321b9e37876fef90ce69e5077544c/go/logic/migrator.go#L445) [thing](https://github.com/github/gh-ost/blob/02258ac15dc321b9e37876fef90ce69e5077544c/go/cmd/gh-ost/main.go#L303) to run before gh-ost exits after a successful migration (excluding some logging, and if the hook doesn't return an error), so doing a rename here won't affect the migration.

**Comment by vbalys** [comment]
@dm-2 Thanks, sounds good. I will need to check if that works for us, but it could be quite a simple solution.

**Comment by dm-2** [comment]
I'm closing this as it looks like we may have a solution, feel free to re-open if needed :+1:
