### ISSUE TITLE
there is risk of data loss for the gh-ost

### ISSUE THREAD

**Issue by czxin788** [github/gh-ost#1186]
At present, I read a blog saying that in the after sync mode, when the last transaction is not committed, there is a risk of data loss. Have you fixed this bug now.

For details, see https://zhuanlan.zhihu.com/p/429758596
thank you.

**Comment by wangzihuacool** [comment]
fixed already, see #1054

**Comment by dm-2** [comment]
Thanks @wangzihuacool! :+1:
