### ISSUE TITLE
add rocksdb as transactional engine

### ISSUE THREAD

**Issue by wangzihuacool** [github/gh-ost#1189]
gh-ost now treats innodb and tokudb as transactional engine. 

We now use rocksdb as MySQL's storage engine, for its high compression ratio and write performance. Rocksdb engine also supports transactions and implements transaction concurrency control based on row locks. 

I hope gh-ost will treat rocksdb as a transactional engine as well, by adding a case option to IsTransactionalTable() .

Thank you!

**Comment by wangzihuacool** [comment]
refer:  https://github.com/facebook/mysql-5.6/wiki/Row-Locking

**Comment by dm-2** [comment]
:wave: @wangzihuacool thanks for the PR! Has this been tested? My main area of concern is whether gh-ost's [atomic cut-over](https://github.com/github/gh-ost/issues/82) still works as expected with RocksDB.

If this all works fine in testing, I'm happy to accept the PR to allow gh-ost to run against RocksDB - but we won't provide any official support for RocksDB as we don't use it here at GitHub currently.

**Comment by timvaillancourt** [comment]
> Has this been tested? My main area of concern is whether gh-ost's [atomic cut-over](https://github.com/github/gh-ost/issues/82) still works as expected with RocksDB.

I'm also curious about testing and the potential differences [due to no Gap Lock in RocksDB](https://github.com/facebook/mysql-5.6/wiki/Row-Locking#gap-locks)

Are the functional-tests in ['localtests/`] passing on RocksDB and would you be able to assist with adding a RocksDB-enabled MySQL server [to those CI jobs](https://github.com/github/gh-ost/blob/master/script/cibuild-gh-ost-replica-tests) @wangzihuacool?

We are currently testing on a Oracle Community Edition 5.7 and 8.0 server, InnoDB only. I believe RocksDB can be tested using a Percona Server for MySQL server

**Comment by wangzihuacool** [comment]
We are testing RocksDB with gh-ost in our test environment now , and I am glad to add a RocksDB-enabled MySQL server to the ci jobs.

**Comment by wangzihuacool** [comment]
> > Has this been tested? My main area of concern is whether gh-ost's [atomic cut-over](https://github.com/github/gh-ost/issues/82) still works as expected with RocksDB.
> 
> I'm also curious about testing and the potential differences due to [no Gap Lock in RocksDB](https://github.com/facebook/mysql-5.6/wiki/Row-Locking#gap-locks)
> 
> Are the functional-tests in [`localtests/`](https://github.com/github/gh-ost/tree/master/localtests) passing on RocksDB and would you be able to assist with adding a RocksDB-enabled MySQL server [to the CI jobs that run these tests](https://github.com/github/gh-ost/blob/master/script/cibuild-gh-ost-replica-tests) @wangzihuacool? This would help gain confidence of the compatibility
> 
> We are currently testing on a Oracle Community Edition 5.7 and 8.0 server, InnoDB only. I believe RocksDB [can be tested using a Percona Server for MySQL](https://www.percona.com/blog/getting-started-with-rocksdb-in-percona-server-for-mysql/) server

I have tested RocksDB using a Percona Server for MySQL 8.0. Most of the functional-tests in [localtests/](https://github.com/github/gh-ost/tree/master/localtests) for release v1.1.5 are passed on RocksDB , except a few features that RocksDB not supportted. To be specific, RocksDB does not support Foreign Key, Generated Columns,GEOMETRY and Gap Locks, refre to [MyRocks-limitations](https://github.com/facebook/mysql-5.6/wiki/MyRocks-limitations).

But tests for master branch are failed, due to the transaction isolation changed to REPEATABLE-READ in #1156. gh-ost can only run in READ_COMMITTED  isolation on RocksDB, due to no support for gap locking within RocksDB. Can you making the transaction isolation level user-configurable, or change the default isolation to READ_COMMITTED. 

Since we have modified thousands of tables using gh-ost, under READ_COMMITTED isolation level. I think it is safe to use gh-ost under READ_COMMITTED isolation level.

**Comment by dm-2** [comment]
@wangzihuacool I think this is going to be a larger piece of work. Would you mind creating a PR with all of the changes needed in a single PR?

We can then review this PR to decide whether to include it in gh-ost - however if the changes are significant then it may be best maintained as a separate fork 😅

The approach that I would prefer for adding RocksDB support would be:
- add a new `storage-engine` command line flag (defaults to `innodb`)
  - when `storage-engine` is set to `rocksdb`, this enables any changes necessary to support RocksDB (e.g. sets isolation level to `READ_COMMITTED`)
  - when `storage-engine` is set to `innodb`, gh-ost runs in the same way that it does currently
- add RocksDB migration testing
  - update existing tests to exclude any that don't work with RocksDB

**Comment by wangzihuacool** [comment]
I'm glad to do that, I'll create a PR with all the changes in a few days.

**Comment by wangzihuacool** [comment]
I have created a PR in [gh-ost-ci-env](https://github.com/github/gh-ost-ci-env) , adding PerconaServer-8.0.21 tarball so that gh-ost can run tests for RocksDB.  [#14](https://github.com/github/gh-ost-ci-env/pull/14)

And a PR #1190 with all the changes needed to support RocksDB. Hope you take the time to review it @dm-2 @timvaillancourt

**Comment by dm-2** [comment]
Thanks @wangzihuacool1 I've merged github/gh-ost-ci-env#14 and left a review on #1190 :+1:

**Comment by dm-2** [comment]
PR merged :rocket:
- #1190

Thanks again for all of your work on this @wangzihuacool! ❤️
