### ISSUE TITLE
force index in Iteration Range End Value queries to fix execution plans

### ISSUE THREAD

**Issue by wangzihuacool** [github/gh-ost#1242]
I recently found that gh-ost occasionally executes slowly in MySQL 8.0.
When copying data to the _gho table, querys for Iteration Range End Values occationally use the wrong index due to inappropriate optimizer selection.

I think we can force the unique-key index to avoid inappropriate optimizer selection, in BuildUniqueKeyRangeEndPreparedQueryViaOffset and BuildUniqueKeyRangeEndPreparedQueryViaTemptable. Just like unique key range queries do in #1237 .

I'd like to contribute the patch, if you agree.

**Comment by timvaillancourt** [comment]
@wangzihuacool thanks for this report. I believe https://github.com/github/gh-ost/pull/1237 will resolve this issue, can you please confirm?

**Comment by timvaillancourt** [comment]
>  in BuildUniqueKeyRangeEndPreparedQueryViaOffset and BuildUniqueKeyRangeEndPreparedQueryViaTemptable

@wangzihuacool sorry I misread your issue summary, this is similar but different as you mentioned 👍 

> I'd like to contribute the patch, if you agree.

A PR would be appreciated thanks!

**Comment by wangzihuacool** [comment]
> 

I have created a PR #1245 , hope you take the time to review it.

**Comment by timvaillancourt** [comment]
@wangzihuacool I believe this is resolved by https://github.com/github/gh-ost/pull/1237. Please test and re-open if this is not the case. Thanks!
