### ISSUE TITLE
gh-ost Error 1366: Incorrect string value modify charset

### ISSUE THREAD

**Issue by atanthowiz** [github/gh-ost#1249]
Hi,

I tried to run gh-ost to modify charset in specific column of table. Eventually it failed with a message like this
```
**Error 1366: Incorrect string value: '\xA0887\xA04...' for column 'comments' at row 1**
```

for my table definition: 
```
CREATE TABLE `tbtest` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `comments` text NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

and this one for gh-ost command : 
```
gh-ost --user="root" \
--password="xxxxxxx" \
--host="xxxxxxx" \
--port="3306" \
--allow-on-master \
--gcp \
--assume-rbr \
--alter="MODIFY name varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',MODIFY comments text CHARACTER SET utf8mb4"
```

I have tried the gh-ost with latest version (1.1.15), v1.1.2, and v1.0.48, but that doesn't solve the problem. I dont know this is related to this [issue 267](https://github.com/github/gh-ost/issues/267) or not, but that issue solved with v1.0.21. but I can't use v1.0.2 since I using gcp and in v1.0.2 the -gcp flag is not available.

Thank you!

**Comment by jondrummond-codeo** [comment]
We are encountering the same issue as above when changing collation to utf8mb4, is there a workaround for this?

**Comment by atanthowiz** [comment]
If I'm not mistaken, this error appears because the data contains char [windows_1252 \x80-\xFF](https://www.charset.org/charsets/iso-8859-1). if I convert char to hex, there is a difference between latin1 and utf8.

`mysql> CREATE TABLE `tbghost1` ( `id` int(11) NOT NULL AUTO_INCREMENT, `remark` text, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
Query OK, 0 rows affected (0.07 sec)

mysql> CREATE TABLE `tbghost2` ( `id` int(11) NOT NULL AUTO_INCREMENT, `remark` text, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
Query OK, 0 rows affected (0.02 sec)

mysql> insert into tbghost1(remark) values('”');
Query OK, 1 row affected (0.01 sec)

mysql> insert into tbghost2(remark) values('”');
Query OK, 1 row affected (0.00 sec)

mysql> select id,remark,hex(remark) from tbghost1;
+----+--------+-------------+
| id | remark | hex(remark) |
+----+--------+-------------+
|  1 | ”      | 94          |
+----+--------+-------------+
1 row in set (0.01 sec)

mysql> select id,remark,hex(remark) from tbghost2;
+----+--------+-------------+
| id | remark | hex(remark) |
+----+--------+-------------+
|  1 | ”      | E2809D      |
+----+--------+-------------+
1 row in set (0.00 sec)

mysql>`

**Comment by jondrummond-codeo** [comment]
It looks like a fix _may_ have been done for this (which was merged to master in September 2022) - https://github.com/github/gh-ost/pull/1158 - but there has not been a release including this fix since then.

**Comment by atanthowiz** [comment]
ah that's right, I've tried it for a small table, which has a size of ~2GB, and no problem appears. but for a large table with a size of ~70GB, I got an error `incorrect string value` for char \x80-\xFF, I don't know why.

**Comment by jondrummond-codeo** [comment]
We got ours to work using a different SQL statement in the gh-ost query, maybe try the following and see if it also works for you.

```
change column name name varchar(255) not null default '', character set utf8mb4 collate utf8mb4_unicode_ci
```

**Comment by atanthowiz** [comment]
still error, if the column contains one of \x80-\xFF

**Comment by jondrummond-codeo** [comment]
I can also confirm that we encounter the issue when the table size is large, it currently fails on a ~900GB table we are attempting to do a migration on. 😢 If I take the offending row that it fails on and add to a temp table, then gh-ost runs and completes correctly.

**Comment by timvaillancourt** [comment]
> It looks like a fix may have been done for this (which was merged to master in September 2022) - https://github.com/github/gh-ost/pull/1158 - but there has not been a release including this fix since then.

@jondrummond-codeo / @atanthowiz if possible, could you test on `HEAD` of `master` to validate #1158 fixes this? 🙇

**Comment by atanthowiz** [comment]
I'm currently using [this branch](https://github.com/wangzihuacool/gh-ost/tree/fix-charset). previously I ran gh-ost with chunk-size=100 on high traffic and tried it also on low traffic, but always got error `incorrect string value` for char `\x80-\xFF`. And yesterday i tried to increase chunk-size to 500, and ran it on low traffic, and it worked, gh-ost ran successfully. I don't know, do the "chunk-size" and "low traffic" affect the gh-ost process?

**Comment by wangzihuacool** [comment]
It has nothing to do with traffic and chunk-size. It may occurs , when an illegal latin1 character (such as windows_1252 \x80-\xFF) was inserted in a transaction just during changing the table.
#1158 is intended to fix the Error 1366 , without doing any characterset conversion.

**Comment by jondrummond-codeo** [comment]
Thanks @wangzihuacool - I see that #1158 was merged to master last year September, is there a plan to get this into a release any time soon or should we clone master and do the build ourselves to get around this?

**Comment by atanthowiz** [comment]
I think this case is already solved. 
I using [this branch](https://github.com/jbielick/gh-ost/tree/latin1-utf8mb4) as mentioned before https://github.com/github/gh-ost/pull/1158#issuecomment-1222733860, and I've tried migration several times, and it always works.
