### ISSUE TITLE
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by nekarenae18** [github/gh-ost#1256]
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/24020#issuecomment-1436109224_

**Comment by dm-2** [comment]
Reported as spam
