### ISSUE TITLE
Release v1.1.6

### ISSUE THREAD

**Issue by SocalNick** [github/gh-ost#1277]
Hi there!

We actively use gh-ost at [Gusto](https://github.com/gusto/), we built a tool that wraps gh-ost for our use case. We've maintained a fork on and off over the years, and got our largest change, the [logging interface](https://github.com/github/gh-ost/pull/789), upstreamed several years ago. However, we'd really like to get back on upstream.

I noticed in the [release notes for v1.1.5](https://github.com/github/gh-ost/releases/tag/v1.1.5) that it was created off v1.1.4 with some commits cherry-picked from `master`. Seems this has been the case for the last few releases.

In our effort to get back to upstream gh-ost, we discovered that https://github.com/github/gh-ost/pull/888 introduced a bug that we caught in our integration tests. The issue is exactly as described in https://github.com/github/gh-ost/issues/1171. This change has been present in every version of gh-ost since v1.1.1. However, the change was reverted in the [latest commit on master](https://github.com/github/gh-ost/pull/1180).

In addition to the latest commit, we'd really like to get a release cut that includes this [small change I contributed last November](https://github.com/github/gh-ost/pull/1194).

Ideally, we'd like to have `master` back in a state that it can be released more frequently. As mentioned, the release notes indicate, "as it [master] contains a known issue that is currently being investigated". Can you shed light on that issue? I can report that the integration tests for our tool pass on the latest commit on gh-ost `master`, but we wouldn't want to use that without understanding the issue being investigated.

As an alternative, would you consider cutting a release that cherry-picks https://github.com/github/gh-ost/pull/1180 and https://github.com/github/gh-ost/pull/1194?

We really appreciate your consideration and the work you all do to make this tool a viable solution for safe schema migrations. Let us know if there's anything else we can do to support it!

Thanks,

Nick

**Comment by SocalNick** [comment]
@meiji163 @rashiq @timvaillancourt wondering if you all can consider cutting a release per the above?

**Comment by timvaillancourt** [comment]
> @meiji163 @rashiq @timvaillancourt wondering if you all can consider cutting a release per the above?

Yes, a new release is sorely needed 👍. Hoping @dm-2 / @rashiq / @meiji163 can help with that 👋🙇

**Comment by meiji163** [comment]
> As mentioned, the release notes indicate, "as it [master] contains a known issue that is currently being investigated". Can you shed light on that issue? I can report that the integration tests for our tool pass on the latest commit on gh-ost master, but we wouldn't want to use that without understanding the issue being investigated.

It should be fixed in https://github.com/github/gh-ost/pull/1322. I'll work on a release this week

**Comment by meiji163** [comment]
release is live! https://github.com/github/gh-ost/releases/tag/v1.1.6
