### ISSUE TITLE
Unable to run GH-ost tool from EC2

### ISSUE THREAD

**Issue by geddamurisatish** [github/gh-ost#1281]
I have downloaded GH-ost from [here](https://github.com/github/gh-ost/releases/tag/v1.1.5)  onto a Windows machine. 

Tried to run gh-ost from cmd but it says '.' is not recognized as an internal command.

![image](https://github.com/github/gh-ost/assets/373259/ddc2bcc7-ec8c-410c-afd6-e6d22ab88181)

Here is the command for reference: 
./gh-ost --max-load=Threads_running=200 --chunk-size=100000 --max-lag-millis=1500 --user="username" --password="secret" --host=DB link --allow-on-master --database="dbname" --table="test_table" --initially-drop-ghost-table --verbose  --alter="ADD COLUMN column1 int;" --switch-to-rbr  --cut-over=default --default-retries=120  --initially-drop-ghost-table --initially-drop-old-table --exact-rowcount --execute  >test_Genlog.log 2>test_Errlog.log &

Can someone please let us know, if we are missing anything in terms of configuration setup?

Please let me know for any information required or missing.

**Comment by geddamurisatish** [comment]
Hi Team, Do we have any update on above reported issue?

**Comment by ericyan** [comment]
Hi, Windows is not supported. You might be able to get it running on WSL or a Linux virtual machine.
