### ISSUE TITLE
Run on an EC2 server (Linux)

### ISSUE THREAD

**Issue by yossicoh** [github/gh-ost#1301]
I am trying to install GH-OST on a (Linux) Server. I did the following:

sudo yum install -y git gcc-c++ make cmake openssl-devel

git clone https://github.com/github/gh-ost.git

cd gh-ost cmake.

GET ERROR CMake Error: The source directory "///temp/gh-ost" does not appear to contain CMakeLists.txt. Specify --help for usage, or press the help button on the CMake GUI.
that I check if the installation was successful I get

gh-ost --version

bash: gh-ost: command not found

When I try to run gh-ost commands I get an error.

DB = mySql 
 
Thank you

**Comment by ericyan** [comment]
gh-ost is Go project and does not use CMake as the build tool. Please consult [the docs](https://github.com/github/gh-ost?tab=readme-ov-file#downloadbinariessource) on how to built it from source.

Alternately, you can use pre-built binaries here: https://github.com/github/gh-ost/releases/tag/v1.1.5
