### ISSUE TITLE
gh-ost doesn't cleanup its socket file

### ISSUE THREAD

**Issue by dveeden** [github/gh-ost#133]
On a second run:
`2016-08-03 10:51:34 FATAL listen unix /tmp/gh-ost.sakila.rental.sock: bind: address already in use`

Check with `ss -x src /tmp/gh-ost.sakila.rental.sock` to see nobody is listening on the socket

**Comment by dveeden** [comment]
Duplicate of #95

**Comment by dacur** [comment]
for anyone else that might be trying to debug a session, we resolved it by deleting the tmp file and rerunning.
