### ISSUE TITLE
1.1.6 binary is dynamically linked

### ISSUE THREAD

**Issue by piotrbelina** [github/gh-ost#1337]
Hello,

I would like to report a difference between released file between v1.1.5 and v.1.1.6 (`gh-ost-binary-linux-amd64-20220707162303.tar.gz` and `gh-ost-binary-linux-amd64-20231103125330.tar.gz`). Previously this was statically linked, now it is dynamically. 

1. Is this change intended?
2. If not, can we revert it?

Thank you,
Piotr Belina

```bash
# v.1.1.6

bash-5.0# file /usr/local/bin/gh-ost
/usr/local/bin/gh-ost: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=gW5SscaBM4-Z5T-ZYUC_/pVTBH8gNrOxsG2CKwOL1/uoRi-wh2GRKyq5X0CU4X/1q39H5KdvuIBl178wFxL, not stripped

# 1.1.5
bash-5.0# file /usr/local/bin/gh-ost
/usr/local/bin/gh-ost: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=j3jM6UAh9CzWb-Ht75Qt/PlKIPfssXNE5WwGMMXAg/IPeW0cZqH9BsRQ-HeJ6Q/nhFjfhUKLyhP_66j5bKh, not stripped
```

**Comment by meiji163** [comment]
Thanks for opening the issue. It was not intended, I updated the binaries in the release to be statically linked.
