### ISSUE TITLE
[Potential Bug] log_slave_updates needed for master only migration

### ISSUE THREAD

**Issue by kbussche** [github/gh-ost#135]
Using gh-ost 1.0.8 on a 5.7 master, setup with (log-bin,binlog_format=ROW, sync_binlog=1).

When I try to run using the --allow-on-master and --allow-master-master it exits with:

FATAL myserver:3306 must have log_slave_updates enabled

I have read the docs but could of missed something. Its my understanding that when doing the master only migration that it should be reading from the bin log, and log_slave_updates would be un-needed in this situation.

**Comment by dveeden** [comment]
This is checked in `validateBinlogs()` in `go/logic/inspect.go`

`-allow-master-master` is stored in `AllowedRunningOnMaster`, but checking that is not enough.

Looks like if `InspectorIsAlsoApplier()` is true we should not check for log_slave_updates.

**Comment by shlomi-noach** [comment]
Thank you. This will be addressed in a few days.

**Comment by shlomi-noach** [comment]
@dveeden your analysis is correct; I will need to push the test till later, though, since the distinction of `InspectorIsAlsoApplier()` is only possible at this time after the `insupector`'s tests

**Comment by shlomi-noach** [comment]
@kbussche @dveeden , https://github.com/github/gh-ost/pull/155 will fix and close this issue; will merge tomorrow.

**Comment by shlomi-noach** [comment]
closed by https://github.com/github/gh-ost/pull/155
