### ISSUE TITLE
gh-ost should display a warning if it's run against a table with triggers defined

### ISSUE THREAD

**Issue by cswingler** [github/gh-ost#141]
From the docs:

> Triggers are not supported. They may be supported in the future.

The output of `gh-ost` should probably mention this as at least a warning if it detects any triggers on the table to be altered. As it stands now, it silently leaves them attached to the old table, and if `--ok-to-drop-table` is defined, silently deletes them.

**Comment by shlomi-noach** [comment]
`gh-ost` should fail if triggers exist on the table.

I will later open an Issue for community contribution for supporting triggers -- this is possible to do.

**Comment by shlomi-noach** [comment]
closed by https://github.com/github/gh-ost/pull/152
