### ISSUE TITLE
Too many colons in address when using IPv6 address literals for replication

### ISSUE THREAD

**Issue by Roguelazer** [github/gh-ost#142]
If replication is set up using IPv6 address literals for the master host name, `gh-ost` dies with "2016-08-05 23:25:51 ERROR dial tcp: too many colons in address fd00:aaaa:bbbb::1:3306".

As far as I can tell, the mysql driver seems to expect IPv6 addresses to be written as `[a:b:c::d]:3306`, so this may just be a matter of detecting when `Master_Host` is an IPv6 literal and adding some square brackets?

**Comment by shlomi-noach** [comment]
@Roguelazer thank you -- did you happen to confirm your change works with `ipv6`? I don't have an immediate environment to test this.

**Comment by Roguelazer** [comment]
yeah, it seems to.

**Comment by Roguelazer** [comment]
(fixed in 1.0.9)
