### ISSUE TITLE
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).

### ISSUE THREAD

**Issue by Harmonyblue** [github/gh-ost#1467]
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/35185#issuecomment-2456189217_

**Comment by Harmonyblue** [comment]
Remove

**Comment by issa536** [comment]
I just want my account deleted 

Yahoo Mail: Search, Organize, Conquer 
 
  On Mon, Nov 4, 2024 at 9:47 PM, Cheyanna ***@***.***> wrote:   

          Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).

Originally posted by @WELCOME[bot] in github/docs#35185 (comment)
