### ISSUE TITLE
Various TODOs

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#15]
At this development time there's just a gazillion things to sift through. I'm writing them down; some of these are just next steps for development; others are concepts.

**Comment by dgryski** [comment]
As there are only three items remaining in this list, maybe open issues specifically for those ideas and close this brainstorming one?

**Comment by shlomi-noach** [comment]
@dgryski yes indeed. This issue was created in the very early days of the project to lay out the development plans. Thank you
