### ISSUE TITLE
How to dynamically change execution parameters of gh-ost?

### ISSUE THREAD

**Issue by hhl419** [github/gh-ost#151]
How to dynamically change execution parameters of gh-ost? 
For example the parameters:chunk-size=1500, max-lag-millis=2000, max-load=Thread_running=30 and so on.Can you give an example?

Thank you!

**Comment by shlomi-noach** [comment]
Please refer to the documentation: https://github.com/github/gh-ost/blob/master/doc/interactive-commands.md
