### ISSUE TITLE
Tracking issue: support Amazon RDS

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#163]
**EDIT**: [Documentation for RDS is available](https://github.com/github/gh-ost/blob/master/doc/rds.md)

This is a tracking issue to discuss all things RDS and what it takes to be able to run `gh-ost` on RDS.

**Comment by shlomi-noach** [comment]
First limitation is the `SUPER` privilege. This is defined in https://github.com/github/gh-ost/issues/132 and addressed in https://github.com/github/gh-ost/pull/156

When you _know_ you are using RBR (Row Based Replication), you can specify `--assume-rbr` and this will skip the step of `STOP SLAVE; START SLAVE` which requires `SUPER` privilege.

**Comment by shlomi-noach** [comment]
I should note that I am not using RDS at the moment; will need community feedback for production issues.

**Comment by pbitty** [comment]
I am using RDS and have been trying out gh-ost with success so far.  I am happy to give feedback and contribute where possible.

I've succeeded in running a test with `--test-on-replica` (using the workaround described in #162) and table checksums matched.  And I've done a migration with `--migrate-on-replica` and did not have any significant issues.

**Comment by pbitty** [comment]
As far as I can tell, the only other blocker is the `STOP SLAVE` command that is issued in `--test-on-replica` mode (to be solved via #162).

In RDS, it is possible to start/stop replication with stored procedures they provide, ie: `CALL mysql.rds_stop_replication`.  So we could support automatic replication stop/start.

The only other thing that is not supported (that I can tell) is setting global variables, so we wouldn't be able to support auto-configuring RBR from mysql itself.  It would be possible to do it via the RDS API, but there are non-trivial concerns since multiple RDS instances can share the same configuration, so setting `binlog_format=ROW` on a shared configuration could change it on multiple RDS instances at the same time.  This could be left as a manual step and included in a doc, or a plugin from #62.

**Comment by shlomi-noach** [comment]
Thank you! You are now assigned the role of Chief RDS Officer at Gh-Ost Corp.

Chaning a `statement` replica to `row` can certainly be delegated to the user, no need to trouble `gh-ost` on this if this is an issue.

**Comment by pbitty** [comment]
Ha, thanks!

I am working on documenting the steps required for using gh-ost in our RDS environment.  I should be able to make it generic enough to help others.   When I do, I can submit a PR if you are interested.  Hopefully we can get other RDS users to provide some feedback.

**Comment by shlomi-noach** [comment]
Hooks have been merged, though not yet released.

**Comment by pbitty** [comment]
Great!  I will try them out with our next `--test-on-replica` run either today or tomorrow.

**Comment by pbitty** [comment]
The `gh-ost-on-stop-replication` worked like a charm.  I was able to stop replication the RDS way before continuing with cut-over, using the hook along with `--test-on-replica` and `--test-on-replica-skip-replica-stop`.

**Comment by shlomi-noach** [comment]
At this time, the way to run `gh-ost` on RDS is as follows:

### Real migration

- You need to make sure replication is `RBR`. `gh-ost` has no privilege to set `binlog_format=ROW` for you.
- Execute `gh-ost --assume-rbr ...` 
  This will make `gh-ost` skip the `stop slave; start slave` step, which it does not have privileges for.
- 🍕 

### Test on replica

In _addition to the above_:

- `gh-ost --assume-rbr --test-on-replica --test-on-replica-skip-replica-stop`
  The `--test-on-replica-skip-replica-stop` avoids issuing a `stop slave` at the end of migration
- However replication must be stopped. Using [hooks](https://github.com/github/gh-ost/blob/master/doc/hooks.md) you need to supply `gh-ost-on-stop-replication` hook -- where you will invoke your own RDS script to stop replication
- 🍕 

---

Once the above is tested more by the community, I will put this in documentation

**Comment by pbitty** [comment]
This is the hook we use.

At `/hooks/gh-ost-on-stop-replication-rds-command.sh`:

```shell
#!/usr/bin/env bash

statement="call mysql.rds_stop_replication"
echo "Issuing statement to stop replication: ${statement}" 1>&2
exec mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "${statement}"
```

where `--hooks-path=/hooks`.

The `DB_...` env vars are set when running the gh-ost process, and then passed by gh-ost onto the hook process.

**Comment by pbitty** [comment]
This is the minimum privilege required for that:

```sql
GRANT EXECUTE ON PROCEDURE mysql.rds_stop_replication to '<your_ghost_user>'@'<desired_host_or_wildcard>';
```

**Comment by shlomi-noach** [comment]
@pbitty thank you for this info!

To clarify, in: `GRANT EXECUTE ON PROCEDURE mysql.rds_stop_replication to '<your_ghost_user>'@...` you don't actually need the user to be the `gh-ost` user you use for running the migration. This was your personal choice.

**Comment by pbitty** [comment]
Good point.  I've updated the comment above.

**Comment by shlomi-noach** [comment]
Cool. Eventually we'll make a doc page out of this.

**Comment by drmmr763** [comment]
hey all

Just arriving here after researching tools like percona's online schema change and even @shlomi-noach's old open oak project. This project has become highly relevant to me on the back of a terrible alter-table experience last week :)

I'm curious what is the status of Amazon RDS support at this point? it looks like the biggest issue that even Percona's toolkit had with regard to the super user was resolved in #156. Is this the only known limiting issue or are there more known issues?

**Comment by pbitty** [comment]
@drmmr763 ,  I have been using `gh-ost` in RDS with no real issues.  Any issues I've had have not been related to RDS and are being addressed as we go.

**Comment by pbitty** [comment]
I should note, for `--test-on-replica` mode, you must make `read_only=0` on the replica's Parameter Group.  By default `read_only` is enabled.

**Comment by shandrew** [comment]
Has anyone tested gh-ost on RDS-Aurora?

**Comment by drmmr763** [comment]
Thanks for the reply @pbitty! Actually I have a followup based on what @shandrew said -- is Amazon RDS not the same as RDS-Aurora? Or are they the same infrastructure / architecture?

**Comment by pbitty** [comment]
@drmmr763 Amazon Relational Database Service (RDS) is the umbrella name for their relational DB offerings.  It's basically a managed DB service.  They offer Mysql, Postgres, MS-SQL server instances and maybe others.  RDS Aurora is a new offering that is Mysql wire-compatible but has a different architecture on the backend (it's not actually a mysql server).  We haven't used it yet, but they claim performance benefits in a lot of cases.

**Comment by fern4lvarez** [comment]
@shlomi-noach could you please update [this comment](https://github.com/github/gh-ost/issues/163#issuecomment-244694616) to reflect that replica's Parameter Group requires `read_only=0` set for `--test-on-replica` mode, as @pbitty pointed out in https://github.com/github/gh-ost/issues/163#issuecomment-249580779?

It can help others to have all needed information in one place, until this makes it into the official docs.

**Comment by shlomi-noach** [comment]
@fern4lvarez done, thank you!

**Comment by pbitty** [comment]
I will set aside some time before end of week to whip up a PR for RDS documentation.

**Comment by fern4lvarez** [comment]
@pbitty did you try to throttle a migration during a long period of time? I'm concerned about `expire_logs_days` value set as 0 by default on RDS instances. Furthermore, this variable is not editable via Paremeter Groups, which makes it a bit more painful to change every time I want to start new replicas. See https://forums.aws.amazon.com/thread.jspa?threadID=152786

**Comment by pbitty** [comment]
@fern4lvarez , I don't believe I've throttled one for a long period - however, we do stop replication for about 8 hours during backups on some of our instances.

RDS hides this setting behind a config option that you can set using their `mysql.rds_set_configuration` stored procedure.  eg. To set it for 24 hours, you call:

```sql
call mysql.rds_set_configuration('binlog retention hours', 24);
```

It's not very well-documented, you can find it at the bottom of [this doc](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html#USER_LogAccess.MySQL.Binarylog).

**Comment by jessicalu2016** [comment]
Hi, I am trying to do "Connect to replica, migrate on master" or "Migrate/test on replica" on RDS but having an issue complaining "<rbr_replica_host> must have binary logs enabled". The parameter group does have "log-bin" set up and "binlog_format" is set to "ROW". I would be very appreciated any suggestions how to solve it. Thank you.

**Comment by pbitty** [comment]
@jessicalu2016 The only way to enable replication in RDS is to enable backups on the replica itself.  Backup retention of 1 day is enough.  (It's even required if you want to create a replica.)

**Comment by jessicalu2016** [comment]
@pbitty Thanks so much! this solved the problem.

**Comment by fern4lvarez** [comment]
Not sure if this related to RDS, but got an issue that I'd like to share. PLease let me know if this is a duplicate.

I was in the middle of a long migration using the "Connect to replica, migrate on master"  approach, data was being copied to the ghost table:

```
...
# Migrating `...`.`...`; Ghost table is `...`.`_..._gho`
# Migrating ip-...:3306; inspecting ip-...:3306; executing on ip-...
# Migration started at Mon Oct 24 08:54:39 +0000 2016
# chunk-size: 1000; max-lag-millis: 1500ms; max-load: Threads_running=25; critical-load: Threads_running=1000; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle 
# postpone-cut-over-flag-file: /home/.../ghost.postpone.flag [set]
# panic-flag-file: /tmp/ghost.panic.flag
# Serving on unix socket: /tmp/gh-ost.....publications.sock
Copy: 392000/3459267 11.3%; Applied: 0; Backlog: 0/100; Time: 50m0s(total), 50m0s(copy); streamer: mysql-bin-changelog.000036:59478836; State: migrating; ETA: 6h31m14s
2016-10-24 09:45:00 INFO rotate to next log name: mysql-bin-changelog.000037
2016-10-24 09:45:00 INFO rotate to next log name: mysql-bin-changelog.000037
Copy: 393000/3459267 11.4%; Applied: 0; Backlog: 0/100; Time: 50m30s(total), 50m30s(copy); streamer: mysql-bin-changelog.000037:6113; State: migrating; ETA: 6h34m0s
Copy: 397000/3459267 11.5%; Applied: 0; Backlog: 0/100; Time: 51m0s(total), 51m0s(copy); streamer: mysql-bin-changelog.000037:62663438; State: migrating; ETA: 6h33m23s
Copy: 398000/3459267 11.5%; Applied: 0; Backlog: 0/100; Time: 51m30s(total), 51m30s(copy); streamer: mysql-bin-changelog.000037:84651236; State: migrating; ETA: 6h36m7s
Write failed: Broken pipe
```

As you see in the last line, connection with the server was broken, and I wasn't running `gh-ost` with any terminal muxer. So I reconnected, killed the already running `gh-ost` process, added the `--initially-drop-ghost-table` flag, and started `gh-ost` again.

The startup looked ok as usual:

```
+ ./gh-ost --assume-rbr --max-load=Threads_running=25 --critical-load=Threads_running=1000 --chunk-size=1000 --max-lag-millis=1500 --user=... --password=... --host=... --database=... --table=... --verbose --alter=engine=innodb --cut-over=default --exact-rowcount --concurrent-rowcount --default-retries=120 --panic-flag-file=/tmp/ghost.panic.flag --postpone-cut-over-flag-file=/home/.../ghost.postpone.flag --execute
2016-10-24 11:40:23 INFO starting gh-ost 1.0.21
2016-10-24 11:40:23 INFO Migrating `...`.`...`
2016-10-24 11:40:23 INFO connection validated on ...:3306
2016-10-24 11:40:23 INFO User has REPLICATION CLIENT, REPLICATION SLAVE privileges, and has ALL privileges on `...`.*
2016-10-24 11:40:23 INFO binary logs validated on ...:3306
2016-10-24 11:40:23 INFO Table found. Engine=InnoDB
2016-10-24 11:40:23 INFO Estimated number of rows via EXPLAIN: 2305459
2016-10-24 11:40:23 INFO Master found to be ...:3306
2016-10-24 11:40:23 INFO binary logs updates validated on ...:3306
2016-10-24 11:40:23 INFO connection validated on ...:3306
2016-10-24 11:40:23 INFO Registering replica at ...:3306
2016-10-24 11:40:23 INFO Connecting binlog streamer at mysql-bin-changelog.000071:120
2016-10-24 11:40:23 INFO rotate to next log name: mysql-bin-changelog.000071
2016-10-24 11:40:23 INFO connection validated on ...:3306
2016-10-24 11:40:23 INFO connection validated on ...:3306
2016-10-24 11:40:23 INFO Droppping table ...`.`_..._ghc`
2016-10-24 11:40:23 INFO Table dropped
2016-10-24 11:40:23 INFO Creating changelog table `...`.`_..._ghc`
2016-10-24 11:40:23 INFO Changelog table created
2016-10-24 11:40:23 INFO Creating ghost table `...`.`_..._gho`
2016-10-24 11:40:23 INFO Ghost table created
2016-10-24 11:40:23 INFO Altering ghost table `...`.`_..._gho`
2016-10-24 11:40:23 INFO Ghost table altered
2016-10-24 11:40:23 INFO Waiting for tables to be in place
```

But then nothing happend, `gh-ost` just kept hanging, showing logs like the following:

```
2016-10-24 11:45:00 INFO rotate to next log name: mysql-bin-changelog.000072
2016-10-24 11:45:00 INFO rotate to next log name: mysql-bin-changelog.000072
...
2016-10-24 12:00:00 INFO rotate to next log name: mysql-bin-changelog.000075
2016-10-24 12:00:00 INFO rotate to next log name: mysql-bin-changelog.000075
2016-10-24 12:05:00 INFO rotate to next log name: mysql-bin-changelog.000076
2016-10-24 12:05:00 INFO rotate to next log name: mysql-bin-changelog.000076
2016-10-24 12:10:00 INFO rotate to next log name: mysql-bin-changelog.000077
2016-10-24 12:10:00 INFO rotate to next log name: mysql-bin-changelog.000077
2016-10-24 12:15:00 INFO rotate to next log name: mysql-bin-changelog.000078
2016-10-24 12:15:00 INFO rotate to next log name: mysql-bin-changelog.000078
```

What did go wrong? Thanks in advance :star2:

**Comment by pbitty** [comment]
@fern4lvarez Is the replica configured with`binlog_format=ROW` ?

**Comment by shlomi-noach** [comment]
@pbitty thank you -- and I think you're on the spot.

@fern4lvarez may I suggest you should ask these questions in new issues; this issue is for tracking down changes to support RDS, and we cannot handle multiple problems in the same thread. Opening a new issue and linking to this issue would be the right thing to do.

**Comment by Ahmadposten** [comment]
@shlomi-noach 
I can see that the  ```binlog_format``` parameter in rds parameter groups is non-modifiable .. How did you manage to make it "ROW"? 
currently `-asume-rbr` does me no good and the `binlog_format` is set to Mixed

**Comment by shlomi-noach** [comment]
@Ahmadposten I myself am not using RDS in the first place. Hopefully @pbitty can help out -- but do see his earlier notes on the matter.

**Comment by pbitty** [comment]
@Ahmadposten What version of mysql are you using?  In our account I can only change that setting on PGs for mysql 5.6 (or higher?).  On 5.5 and 5.1 it is non-modifiable as you said.  Is this the case for you?

You would have to upgrade to 5.6 to use gh-ost.  In RDS, only mysql 5.6 or higher have support for "external replicas".  With 5.5 and lower, they don't give you the ability to grant `REPLICATION SLAVE` to a user.

**Comment by Ahmadposten** [comment]
@pbitty @shlomi-noach 
Yes this seems to be my case .. I use mysql 5.5 
I will try upgrading ... Thank you guys

**Comment by lperrin** [comment]
@shlomi-noach one thing to note is that the read replica will not honor the parameter group for the binlog _unless_ you enable automated backups (for at least 1 day). Could you add it in your comment?

**Comment by shlomi-noach** [comment]
@lperrin done. thank you!

**Comment by shlomi-noach** [comment]
@lperrin done. thank you!

**Comment by jessicalu2016** [comment]
Hi guys, we are thinking to move from RDS mysql to Aurora and is curious if anyone here knows if gh-ost works for Aurora as well or not. Thanks!

**Comment by HasMikeW** [comment]
I'm testing it with Aurora and so far so good.

**Comment by dgtized** [comment]
I've run several migrations on RDS MySQL using the directions above and had no problems.

**Comment by jessicalu2016** [comment]
@HasMikeW we have some trouble testing with Aurora. I am curious how do you set up to make it works.

We are Aurora Master and Aurora Replica structure. binlog_format=ROW and both instances have backup turned on.

- running in "connect to master" mode gave us : FATAL Error 1045: Access denied for user

- running in "connect to replica, migrate on master" mode gave us: <replica_host> must have binary logs enabled

Thanks!

**Comment by kamaljoshi** [comment]
I ran around 7-8 migrations on MySQL in December using this. Everything seemed to have worked well. 
Some minor changes I had to do with `gh-ost` were related to making `--assume-master-host` work without Tungsten. As RDS replica was using internal IPs(172.17.X.X) to communicate with master and the machine we were running `gh-ost` on couldn't access that, I had to manually pass the master hostname.

**Comment by jacobbednarz** [comment]
I've been testing this for the last couple of months using RDS and aurora as the engine. The steps here related to RDS are spot on 👍 , the only differing pain point I've found is that the aurora parameter group **doesn't allow modifying `read_only`**. It still uses the same value of `{TrueIfReplica}` however the aurora parameters are marked as a non-modifiable field which prevents connecting to replica but running on the master.

We're looking into a couple of work arounds for this and I'll report back if we get anything worth while but for now, best to just be aware you'll need to run it on the master.

**Comment by pbitty** [comment]
@jacobbednarz  That's great to hear.

From what I understand of Aurora, all nodes share the same underlying storage layer, so only one node is allowed to write to it.  You may be able to get around this by replicating to [another Aurora cluster](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Aurora.Overview.Replication.MySQLReplication.html).  From gh-ost's point of view, it would still be connecting to a "master", but this master would be on a 2nd Aurora cluster (that is receiving binlog updates from the 1st one).

I haven't tried this, just theorizing.  :)

**Comment by jacobbednarz** [comment]
> You may be able to get around this by replicating to another Aurora cluster.

This is a possibility however I don't believe it solves the issue of running on a replica but migrating the master (which is the intention here). Your comment further down explains why this is the case and right now I can't see a viable solution.

The best you can expect from RDS on Aurora at the moment is that you can run it on the cluster but only directly on the master. If you want to test, you need to stand up additional clusters - probably based on a recent snapshot.

**Comment by HasMikeW** [comment]
I migrated a 1.5 billion record table on a highly concurrent system in Aurora.  It took a couple attempts, because the inserts would slow even with no constraints added to the base command.  We had to scale back some of the load on the server to be able to complete the task in a timely manner.

**Comment by shlomi-noach** [comment]
@HasMikeW which version of `gh-ost` were you using? More specifically, does your version support `--dml-batch-size`? Introduction of this functionality (indicated by the existence of this flag) significantly improved write throughput. Generally speaking I prefer to just have some sane configuration and not try to tune too much, but if you suffer from low throughput you may try a higher value for that flag (default: `10`, try perhaps `50` or `100`).

**Comment by HasMikeW** [comment]
@shlomi-noach The version is 1.0.32    I had looked into using the --dml-batch-size but was unable to get it to work with this version.  I didn't want to go back and have to run more tests that a new version of gh-ost would have dictated at that point.  That was the next step if reducing the load did not work :-)

**Comment by jacobbednarz** [comment]
Just an update to [my comment above](https://github.com/github/gh-ost/issues/163#issuecomment-285534302) - I've managed to find a nice workaround for testing/migrating on a replica in AWS RDS using aurora as the engine.

@pbitty was pretty close to the money however you don't use Aurora replication, you need to use standard MySQL-style replication. The AWS documentation page does an OK-ish job at explaining this but it's probably better to follow non-AWS docs and just setup replication as if you would elsewhere using a separate aurora cluster in the same region.

**Comment by shlomi-noach** [comment]
@jacobbednarz do you think it would be good to write some documentation for Aurora users, and if so, would you be able and willing to write it?

**Comment by jacobbednarz** [comment]
It would definitely be worth while! I'm happy to write it (since I've already got a bunch of notes from our internal documentation that would help here too).

**Comment by jacobbednarz** [comment]
I've opened a PR to add in AWS RDS docs at #385 for anyone following along at home.

**Comment by jacobbednarz** [comment]
@shlomi-noach I think everything in this issue has been addressed either via docs or changes. We've also managed to run ~20 successful test + production migrations on RDS so I'm happy most of the annoyances are out of the way. Would it be time to close this off and expect new issues to be in a thread of their own?

**Comment by shlomi-noach** [comment]
[Documentation for RDS is available](https://github.com/github/gh-ost/blob/master/doc/rds.md)
