### ISSUE TITLE
the conf parameter can't read the mysql config file well

### ISSUE THREAD

**Issue by rj03hou** [github/gh-ost#168]
if the my.cnf have the following, would be error.
``
prompt=[\\h]\\u@\\d\\r:\\m:\\s>
``

**Comment by shlomi-noach** [comment]
Can you please run with `--debug --stack` and print the output?

**Comment by shlomi-noach** [comment]
```
2016-08-18 13:57:10 FATAL .../gh-osc.cnf:8:8: unquoted '\' must be followed by new line
```

A `gcfg` limitation

**Comment by shlomi-noach** [comment]
Fixed by https://github.com/github/gh-ost/pull/173

**Comment by rj03hou** [comment]
Thanks,very quick.
