### ISSUE TITLE
Discussion: self/scheduled adjusting of nice-ratio

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#195]
We find that `nice-ratio` is an important config. `max-lag-millis` does the job for throttling, but then a good value of `nice-ration` avoids the lags in the first place (at the cost of running the migration longer).

This is to discuss whether we can set a "dynamic" `nice-ration`. That is, `nice-ratio` is already dynamic in the sense it can be modified in runtime. But can it be self-adjusting? Say be `0.5` during day time (high traffic) and `0` during night time, etc.?

**Comment by dveeden** [comment]
Because of the binlog positions it knows the replication volume. It could use that to adjust the nice-ratio

**Comment by shlomi-noach** [comment]
@dveeden so we're able to both _count_ events as well as estimate _volume_. Great idea!

**Comment by shlomi-noach** [comment]
> We find that nice-ratio is an important config.

Now that we do [subsecond lag resolution](https://github.com/github/gh-ost/issues/203) we find that `nice-ratio` is not needed.

It's a great relief, because we felt `nice-ratio` was making us pick a number. Should it be `0.5`? Should it be `1.0`?

But now, we use subsecond lag resolution and set `--max-lag-millis=500` or less, and this is, if I'm allowed a superlative, _insane_. Migration keeps replication lag well below `1s`, and we do this with `nice-ratio=0`.

I'm going to close this because I think not-needing-a-variable is a way better solution than how-to-auto-adjust-a-variable.
