### ISSUE TITLE
Split "ETA" into "ETA" and "Status"

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#197]
When `ETA` is `N/A` (throttling, counting rows, whatever), indicate the reason in `Status` and just write `N/A` for ETA

cc @ggunson

**Comment by shlomi-noach** [comment]
This will also allow showing `ETA` when throttling. Right now I'm running a migration with subsecond lag resolution and `max-lag-millis=500` on one of our busiest tables. The migration throttles a LOT, which is _fine_, but then the status message rarely says what the `ETA` is; it mostly says it's throttling.

**Comment by jonahberquist** [comment]
> This will also allow showing ETA when throttling. Right now I'm running a migration with subsecond lag resolution and max-lag-millis=500 on one of our busiest tables. The migration throttles a LOT, which is fine, but then the status message rarely says what the ETA is; it mostly says it's throttling.

That's going to be really nice. I found it a bit annoying to have to `sup` gh-ost a few times in a row to get an ETA while it was throttling a lot.

**Comment by shlomi-noach** [comment]
See sample output: https://github.com/github/gh-ost/pull/218#issuecomment-244018295

**Comment by shlomi-noach** [comment]
closed by https://github.com/github/gh-ost/pull/218
