### ISSUE TITLE
"Invalid connection" message

### ISSUE THREAD

**Issue by borizio** [github/gh-ost#207]
During the modification on one busy server the following appears in the outup:

```
Copy: 55000/5635122 1.0%; Applied: 32778; Backlog: 100/100; Time: 2m55s(total), 2m52s(copy); streamer: mysql-bin.023720:1007371740; ETA: N/A
Copy: 55000/5635122 1.0%; Applied: 34520; Backlog: 100/100; Time: 3m0s(total), 2m57s(copy); streamer: mysql-bin.023720:1013156978; ETA: N/A
[MySQL] 2016/08/28 09:08:05 statement.go:27: Invalid Connection
[MySQL] 2016/08/28 09:08:12 statement.go:27: Invalid Connection
[MySQL] 2016/08/28 09:08:18 statement.go:27: Invalid Connection
```

What does it mean and how one can avoid it?

**Comment by shlomi-noach** [comment]
This is being printed by the [go-mysql driver](https://github.com/go-sql-driver/mysql). There is no control over printing this that I'm aware, unless I modify the code. I can modify the code, but do not wish to, since I want to be able to upgrade this package without worrying about repatching.

The error could come from a `wait_timeout` setting or other. The driver performs multiple attempts, and typically resumes work without interruption.

The golden rule is: if `gh-ost` itself does not complain -- you can keep on living your life.

**Comment by Roguelazer** [comment]
I also do get a tone of these. I don't have any timeouts in my config and they start within a few seconds of starting gh-ost, and continue for the duration of the execution.

It hasn't resulted in any data corruption (I've checked all the tables we've migrated to make sure that they're identical before and after), but it's very strange.

**Comment by shlomi-noach** [comment]
It never propagates to `gh-ost` and so there is no error on `gh-ost`'s side.

**Comment by palexvs** [comment]
I have the same situation on AWS RDS MySQL 5.7.11:
```
[MySQL] 2016/09/22 17:52:34 statement.go:27: Invalid Connection
[MySQL] 2016/09/22 17:52:37 statement.go:27: Invalid Connection
Copy: 58585300/175522009 33.4%; Applied: 85099; Backlog: 1/100; Time: 2h57m30s(total), 2h57m30s(copy); streamer: mysql-bin-changelog.010872:42003744; State: migrating; ETA: 5h54m17s
[MySQL] 2016/09/22 17:52:59 statement.go:27: Invalid Connection
[MySQL] 2016/09/22 17:53:03 statement.go:27: Invalid Connection
[MySQL] 2016/09/22 17:53:04 statement.go:27: Invalid Connection
[MySQL] 2016/09/22 17:53:12 statement.go:27: Invalid Connection
[MySQL] 2016/09/22 17:53:22 statement.go:27: Invalid Connection
[MySQL] 2016/09/22 17:53:24 statement.go:27: Invalid Connection
```

DB server is not overloaded and I connect to it without any difficulties

**Comment by shlomi-noach** [comment]
_fine_ 😛 I'll remove this message from the go-mysql driver...

**Comment by zmoazeni** [comment]
I don't think you need to modify the driver anymore: https://github.com/go-sql-driver/mysql/pull/512

I think we just need to pull in the latest go-mysql driver code.

**Comment by shlomi-noach** [comment]
oh nice!

**Comment by shlomi-noach** [comment]
this was done.
