### ISSUE TITLE
Any idea about delete operation

### ISSUE THREAD

**Issue by gywndi** [github/gh-ost#215]
Hi~

I have some question about data copy operation.

This is kind of CDC tool, using binlog parser.
Any change on source table applied by binlog (ROW FORMAT) event, then copy data from source to target with query operation. I understand like this.. (Right?)

But what I concern is "DELETE" operation.
Actually, there's "NO LOCK" between source and target table, only async copy & apply.
Then.. many delete&insert operation, any possibilities "NOT DELLETED", even though last binlog event is "DELETE EVENT".

1. SELETE CHUNK DATA
2. COPY TO TARGET | DELETED ON SOURCE
3. COPY TO TARGET | DELETED ON TARGET
4. COPY TO TARGET - DELETED DATA

This is from "NO LOCK mechanism" copy & apply logic.
It's ok there's no delete operation, but many delete??

Do you have any idea to solve this kind of problems?

Thanks.
Chan.

**Comment by shlomi-noach** [comment]
I'm sorry, I cannot understand the question.
I'm in particular unsure if this is a question/concern about `gh-ost`'s operation, or if this is a general purpose question.

**Comment by gywndi** [comment]
Hi~ I think.. both. :)

"DELETE DATA" is really general operation.
Without "Lock" on specific  row.. how to prevent  the "DELETED DATA" revive.
(I also have similar concerns.. processing streaming log and copy data.)

**Comment by shlomi-noach** [comment]
Sorry, I'm still unsure I understand the question. 

But if I interpret correctly, you believe the algorithm is flawed, and that there is a situation where data is deleted on the original table, but then shows up on the _ghost_ table?
I disagree, here's why:

1. SELETE CHUNK DATA
2. COPY TO TARGET | DELETED ON SOURCE
3. COPY TO TARGET | DELETED ON TARGET
4. COPY TO TARGET - DELETED DATA

Say row 17 exists on `source`. You read/copy it on steps 1,2
it is _then_ deleted, in which case you will _later_ find out about it in the binary log and apply the `delete` on `target`
That row will not be copied again; the entire chunk (say, rows 1-100) will not be iterated again.

(Actually, even if the chunk is reiterated, this is still fine. If the row is not there, it is not copied. If the chunk is reiterated while the row is still there, then the `delete` event will be in its future, and will be applied in the future of the copy)

I'm not sure what steps 3/4 mean.

**Comment by gywndi** [comment]
Recent binlog event remove row, but small chunk contained the removed data, then removed data revived again. (chunk copy->binlog apply: OK, binlog -> chuck copy? I'm not sure.)

I know you never entire rows from source table, divide specific chunk size, and copy data.
This is kind data flow under different databases (event though, it's same host different table name.)
No lock. So it's very hard to prevent "copy data row" changed by binlog applier.

**Comment by shlomi-noach** [comment]
> Recent binlog event remove row, but small chunk contained the removed data, then removed data revived again. (chunk copy->binlog apply: OK, binlog -> chuck copy? I'm not sure.)

if I'm iterating the chunk _now_, and the row is removed _in the future_, then as I'm copying the row, the copy is valid, and a future binlog event will tell me I need to delete it on the _ghost_ table.

if I'm iterating the chunk _now_, and the row has already been removed, then I don't copy it in the first place.

if I'm iterating the chunk _now_, and while my read transaction is open someone is deleting the row, then the binlog event for that deletion will happen in my _future_, and I will apply it _after_ having copied the row to the _ghost_ table.

> I know you never entire rows from source table, divide specific chunk size, and copy data.
This is kind data flow under different databases (event though, it's same host different table name.)
No lock. So it's very hard to prevent "copy data row" changed by binlog applier.

I'm sorry, I do not understand the above sentence.

**Comment by gywndi** [comment]
hm.. kind of difficult.

As you know.. mysql support full MVCC. And default level is REPEATABLE READ.
This means, a transaction only see the only the snapshot data, even though other session committed. 
I'm not sure how you define the chunk size. But, how can you guarantee **all rows in the chunk**  be copied **BEFORE** binlog event applied? (WITHOUT LOCK - 2-pc or something else..)

I agree with your mention "WILL BE REMVED", but must be prerequisite to "COPY DATA" -> "BINLOG DATA".

This means.. 
1) write current binlog position in source machine
2) coply all data from source to target - chunk,chunk,chunk....
3) apply binlog event from source (to target)

**Comment by shlomi-noach** [comment]
> I'm not sure how you define the chunk size. But, how can you guarantee all rows in the chunk be copied BEFORE binlog event applied? (WITHOUT LOCK - 2-pc or something else..)

I think we've narrowed down the misunderstanding point. Great clarification on your side. I actually don't mind much about when the binlog event was _applied_. I care more about _when I read & handle it_, and that is _known_ to happen in the _future_ of the rowcopy.

`gh-ost` serializes everything. It does not apply binlog event while copying rows. I complete copying 100 rows, then see if there's binlog events I need to handle. If not, I copy another 100 rows, then see if I have binlog events to handle. Are there binlog events? I apply them sequentially, and meanwhile I'm not copying rows.

Does this clarify the answer?

**Comment by gywndi** [comment]
I've got it.
I thought everything would be same time. (Also I love it.)
Thanks. :-)
