### ISSUE TITLE
Missing package golang.org/x/text/encoding

### ISSUE THREAD

**Issue by pbitty** [github/gh-ost#229]
Hello,

I've been trying to build master (to work around a latin1 charset issue issue similar to #226), and I'm getting a "cannot find package" error:

```
~/repos/gopath/src/github.com/github/gh-ost $ ./build.sh
Building macOS binary
go/sql/encoding.go:9:2: cannot find package "golang.org/x/text/encoding" in any of:
       	/Users/pbitty/repos/gopath/src/github.com/github/gh-ost/vendor/golang.org/x/text/encoding (vendor tree)
       	/usr/local/Cellar/go/1.6/libexec/src/golang.org/x/text/encoding (from $GOROOT)
       	/Users/pbitty/repos/gopath/src/golang.org/x/text/encoding (from $GOPATH)
go/sql/encoding.go:10:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
       	/Users/pbitty/repos/gopath/src/github.com/github/gh-ost/vendor/golang.org/x/text/encoding/charmap (vendor tree)
       	/usr/local/Cellar/go/1.6/libexec/src/golang.org/x/text/encoding/charmap (from $GOROOT)
       	/Users/pbitty/repos/gopath/src/golang.org/x/text/encoding/charmap (from $GOPATH)
Build failed for macOS
```

I can get around it by fetching the package manually with `go get` for now.  I'm wondering, should this be vendored in?

**Comment by shlomi-noach** [comment]
Thanks -- this should be vendored in

**Comment by shlomi-noach** [comment]
I _really_ dislike the golang package management. Or the lack of it. Or how it puts everything in this big pile of files.

**Comment by pbitty** [comment]
It took me some time to come to terms with it.

At Wattpad we've been using Godep to track our dependencies.  They're still vendored in, with Godep tracking each package's git revision.

**Comment by shlomi-noach** [comment]
Fixed in https://github.com/github/gh-ost/pull/234
