### ISSUE TITLE
RDS: must have binary logs enabled

### ISSUE THREAD

**Issue by araines** [github/gh-ost#237]
When trying to use on a master-only RDS environment, I'm coming up against a problem which I can't figure out.

Here is my command:

```
./gh-ost --host somedb.eu-west-1.rds.amazonaws.com --user=myuser --password=mypass --allow-on-master --database=mydb --table=mytable --verbose --alter="engine=innodb" --exact-rowcount --concurrent-rowcount
2016-09-16 12:57:32 INFO starting gh-ost 1.0.20
2016-09-16 12:57:32 INFO Migrating `mydb`.`mytable`
2016-09-16 12:57:32 INFO connection validated on somedb.eu-west-1.rds.amazonaws.com:3306
2016-09-16 12:57:32 INFO User has REPLICATION CLIENT, REPLICATION SLAVE privileges, and has ALL privileges on `mydb`.*
2016-09-16 12:57:32 FATAL somedb.eu-west-1.rds.amazonaws.com:3306 must have binary logs enabled
```

From hunting around my RDS set up, I believe I've got binary logs enabled and in ROW mode, thanks to the following parameters:
```
log-bin = /rdsdbdata/log/binlog/mysql-bin-changelog
binlog_format = ROW
```

Am I missing something else here?  I've seen some other threads on here which suggest that this should work on RDS (or at least people have had some success).

Really looking forward to using this tool :)

**Comment by tomkrouper** [comment]
Run the query shown here: https://github.com/github/gh-ost/blob/c3e65d45e25a7334487551d0f34e48ee5e2b932a/go/logic/inspect.go#L272 and post what the results are. I'm not familiar with RDS, but maybe this will shed some light on the issue you are running into.

**Comment by araines** [comment]
Thanks @tomkrouper - it looks like I'm still missing a setting somewhere because the results show its still not on:

```
@@global.log_bin	@@global.binlog_format
0	ROW
```

I think we can probably close this off - its clearly my error, not to do with the tool!  Cheers for the help.

**Comment by aleemb** [comment]
@araines were you able to work around this for RDS? My master shows 1 while the slave shows 0 for `log_bin`.

**Comment by aleemb** [comment]
@tomkrouper does the slave need binlogs enabled? in my case the master has binlogs enabled but not the slave. Using:

```
./gh-ost \
  --database="tmp" \
  --table="test" \
  --verbose \
  --alter="force" \
  --switch-to-rbr \
  --execute
```

And seeing the same error `slave.foo.bar must have binary logs enabled`.

**Comment by shlomi-noach** [comment]
@aleemb if your master uses RBR, you can run the migration directly on the master; see [option b](https://github.com/github/gh-ost/blob/master/doc/cheatsheet.md).

Our preferred way of running it to connect to replica, see option a in same page. If your master runs with SBR (statetemt based replication) that is your only option.
