### ISSUE TITLE
Can't remove foreign keys with alter statement

### ISSUE THREAD

**Issue by Frank-Leemkuil** [github/gh-ost#262]
> This is the place to report a bug, ask a question, suggest an enhancement.

> This is the place to make a discussion before creating a PR.

> Please label your Issue

> Please understand if this Issue is not addressed immediately or in a timeframe you were expecting.

> Thank you!

**Comment by Frank-Leemkuil** [comment]
When we want to remove two foreign keys from the table we get an error that we can't remove it.
This is needed to use the gh-ost tool.

**Comment by ggunson** [comment]
@Frank-Leemkuil You're just trying to run a straight "ALTER TABLE" statement to remove the foreign keys, so that then you can use gh-ost for future migrations? Or are you trying to use gh-ost to remove the foreign keys?

What is the error?

**Comment by Frank-Leemkuil** [comment]
We need to remove the foreign keys with gh-ost. Just spoken on percona europe 2016 with your colleges regarding this issue. They told is an bug/feature.

**Comment by shlomi-noach** [comment]
The request is to be able to get rid of foreign keys via `gh-ost` migration. Today `gh-ost` says: "oh you have foreign keys therefor I bail out", but these people actually want to get rid of their FK.

This is basically a `--yes-ok-to-completely-ignore-foreign-keys`

**Comment by tomkrouper** [comment]
@Frank-Leemkuil,

During our discussion you showed the output. Could you please add that here? Possibly with a sanitized output of `show create table ...\G` If you aren't aware, it's best to put the output in triple back ticks for a code block.

**Comment by Frank-Leemkuil** [comment]
The create table of the table:

       Table: alarm
Create Table: CREATE TABLE `alarm` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Guid` char(36) NOT NULL,
  `AssetId` int(11) unsigned NOT NULL,
  `EventId` int(11) unsigned NOT NULL,
  `CreatedOn` datetime NOT NULL,
  `AcknowledgedOn` datetime DEFAULT NULL,
  `ProcessedOn` datetime DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `alarm_ibfk_2` (`EventId`),
  KEY `Guid` (`Guid`) USING BTREE,
  KEY `AssetIdCreatedOn` (`AssetId`,`CreatedOn`) USING BTREE,
  CONSTRAINT `alarm_ibfk_1` FOREIGN KEY (`AssetId`) REFERENCES `asset` (`Id`) ON UPDATE CASCADE,
  CONSTRAINT `alarm_ibfk_2` FOREIGN KEY (`EventId`) REFERENCES `event` (`Id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=261029 DEFAULT CHARSET=latin1

The drop foreign key command:

 ./gh-ost --alter="DROP FOREIGN KEY _alarm_ibfk_1,DROP FOREIGN KEY _alarm_ibfk_2, MODIFY COLUMN EventId bigint SIGNED NOT NULL" --table="alarm" --database="myfms" --host="hostname" --user="user" --password="password"

Error message:

2016-10-05 13:02:51 ERROR Found 2 foreign keys related to `database`.`alarm`. Foreign keys are not supported. Bailing out
2016-10-05 13:02:51 FATAL 2016-10-05 13:02:51 ERROR Found 2 foreign keys related to `database`.`alarm`. Foreign keys are not supported. Bailing out

**Comment by shlomi-noach** [comment]
Please be advised that as we fix this, you will not need, nor be _able_ to specify `DROP FOREIGN KEY ...`. Foreign keys will just not exist on the ghost table.

**Comment by Frank-Leemkuil** [comment]
Does this mean that he will skip automatically the foreign keys? So it's an improvement?

**Comment by shlomi-noach** [comment]
"skip automatically" is a nice description. To elaborate: current status is that `gh-ost` does not do foreign keys. When it creates the _ghost_ table, it does not create it with foreign keys.

Your mission statement is to get rid of foreign keys.

The fix I'm suggesting is to merely allow `gh-ost` to do the migration, and not warning you about dropping all your foreign keys. Your foreign keys will be dropped as a side effect of `gh-ost`'s existing no-support-for-foreign-keys limitation.

In the future, `gh-ost` may actually support foreign keys, at which time the behavior will change and you will indeed need to add `drop foreign key...`

**Comment by Frank-Leemkuil** [comment]
Yes that's what I mean, when do you think this change is pulled so we can test the newest version that will ignore the foreign-keys.

**Comment by shlomi-noach** [comment]
@Frank-Leemkuil like we said yesterday when we met, this is likely to go out sometime next week

**Comment by shlomi-noach** [comment]
https://github.com/github/gh-ost/pull/264 addresses this

**Comment by shlomi-noach** [comment]
@Frank-Leemkuil please see full discussion in #264. Also, are you able to test this branch?

**Comment by shlomi-noach** [comment]
https://github.com/github/gh-ost/pull/264 closes this.

Only child-FK-side tables can be migrated. To migrate a parent-FK-side, you must first remove all references to table from children.

There is no support right now for self-referencing tables.
