### ISSUE TITLE
gh-ost fails to insert a row with error Error 1366: Incorrect string value

### ISSUE THREAD

**Issue by mizioumt** [github/gh-ost#267]
Hi,

I tried to run gh-ost to add a column to a table. Eventually it failed with a message like this:

FATAL Error 1366: Incorrect string value: '\xFF' for column 'col' at row 1; query= replace.....

The column is VARCHAR(N) with latin1 character set and \xFF is indeed bad but it exists in the row of the original table so it has to be inserted/replaced to the new table. This is the issue.

SQL_MODE is NO_ENGINE_SUBSTITUTION on both master and slave [that was with -test-on-replica]
so I'd expect gh-ost to find WARNING 1366 instead of an error. 

My only guess is that internally gh-ost enforces STRICT_ALL_TABLES.

A subproblem is gh-ost's reaction to this error: it reported the same error for the same row a few times, then disappeared without any error message, core dump or any other trace.

**Comment by shlomi-noach** [comment]
This issue has been fixed (merged into `master`), but not yet tagged/released, see:

- https://github.com/github/gh-ost/issues/235
- https://github.com/github/gh-ost/pull/236
- https://github.com/github/gh-ost/issues/228

`latin1` is supported, with other charsets not yet supported.

`gh-ost` does indeed add `STRICT_ALL_TABLES` to `sql_mode` as per https://github.com/github/gh-ost/issues/164

> it reported the same error for the same row a few times, then disappeared without any error message, core dump or any other trace.

This is the behavior of `default-retries`. However did you run with `--debug`? Or, rather, `--debug --stack`? You'll get all the stack trace you can wish for.

Anyway, if you like to, pease checkout `master` and build a binary. I will release a new binary at the end of this week.

**Comment by mizioumt** [comment]
OK, 60 is the default for default-retries. However I did not see a clear 'we are panicking' message.
I tried with -debug -stack -verbose. To a bit of my surprise after the original error it started to mention

FATAL Error 1205: Lock wait timeout exceeded; try restarting transaction; query=
 >··>···>···update /* gh-ost `database`.`_Table_gho` */

but this is not an immediate concern

**Comment by mizioumt** [comment]
I think there is a bit of misunderstanding here. I don't think any of the character set issues are at play here. My problem is this:

* I do not attempt to change a column's character set. I have -alter 'add column ...'
* gh-ost sets STRICT_ALL_TABLES
* the table has rows with problematic columns that would not have been possible to INSERT with STRICT_ALL_TABLES. But we do not / did not use STRICT modes.
* gh-ost tries to copy a row with dirty data, receives ERROR 1366 and panics.
* so gh-ost can not be used unless all existing table data conforms to a STRICT sql_mode. 

So this would seem a regression caused by https://github.com/github/gh-ost/issues/164

I would propose a solution [if not there yet in the current code] of either of:

* adding an option with the semantics -do-not-set-strict-sql-mode
* (maybe) if SQL_MODE is set in the config file supplied in -conf, use that one, do not add STRICT_ALL_TABLES.

**Comment by shlomi-noach** [comment]
I disagree that the problem is with the `strict_all_tables`, explaining why:

> the table has rows with problematic columns that would not have been possible to INSERT with STRICT_ALL_TABLES. But we do not / did not use STRICT modes.

But the table has _some_ values nonetheless; we don't care how the values got there. But once those values are _in the table_, they are valid for the column types in that table. When we migrate the table, we copy _existing_ values from that table onto the _ghost_ table. Because those values were valid in your original table, they must be valid in the _ghost_ table.

If you know otherwise, please let me know what values these are.

On my side, I see this as a known problem that has been fixed but not yet released (release expected tomorrow)

**Comment by mizioumt** [comment]
'Because those values were valid in your original table, they must be valid in the ghost table.' - this is a problem. gh-ost refused to see them as valid in the ghost table.

My strict mode considerations is a speculation. The evidence is that the offending character was 0xFF in a VARCHAR(40) latin1 column. Without strict mode, inserting that caused warning 1366. With strict mode it caused error 1366 and gh-ost panicked.

 So let's see what happens with the new version to be relesed.

**Comment by shlomi-noach** [comment]
> gh-ost refused to see them as valid in the ghost table.

This is not because of the strict mode (the strict mode should be _thanked_ in this case). This is because of `gh-ost`'s previous inability to write `latin1` characters to `latin1` columns.

Without the strict mode, and with your version, `gh-ost` would silently insert the wrong text into your text columns.

**Comment by shlomi-noach** [comment]
Please check https://github.com/github/gh-ost/releases/tag/v1.0.21

**Comment by mizioumt** [comment]
no such error with v1.0.21
