### ISSUE TITLE
-default-retries 0 uses default value (60), not 0

### ISSUE THREAD

**Issue by mizioumt** [github/gh-ost#270]
v 1.0.21

I ran gh-ost with -default-retries 0, the intention being to not have any retries and panic right after an error. The result was 60 retries, that is, as if -default-retries were not on the invocation line at all.
Not terrible but a minor inconvenience.

-default-retries 1 works as expected, 1 retry.
-default retry -1 works the same as -default-retrues 0.

**Comment by shlomi-noach** [comment]
This is expected behavior. Perhaps the problem is with the term "retry" ; anyway `1` is the minimal value.

See https://github.com/github/gh-ost/blob/c11c611755057a794dd0b901e6f69177903714ee/go/base/context.go#L290-L292

I'm happy to change the documentation if you'd like to present with better wording.

**Comment by mizioumt** [comment]
this is most definitely a 'retry'. I can't see why I can't have 0 retries but it's no big deal.

**Comment by shlomi-noach** [comment]
perhaps it should have been named `num-tries` or `num-attempts`. The value `1` means "1 attempt".

**Comment by mizioumt** [comment]
but so far as I noticed with '1' it does 2 attempts: one original failure, then 1 retry.

**Comment by shlomi-noach** [comment]
Then this is a bug. I'll look into.

**Comment by shlomi-noach** [comment]
> but so far as I noticed with '1' it does 2 attempts: one original failure, then 1 retry.

I do not observe this behavior and the code seems very clear to not behave so. Can you please provide an example of such behavior?

**Comment by mizioumt** [comment]
see file problemn.txt attached to https://github.com/github/gh-ost/issues/272.
gh-ost was run with --default-retries 2 yet there are two ERROR messages in the output, for the same DML.
So I interpret that as the DML in error being issued twice and filed this issue. If you say this is impossible than maybe there is something with the logging.

**Comment by shlomi-noach** [comment]
> `--default-retries 2` yet there are two ERROR messages in the output

`2 == two` so that's the expected behavior 😉 

What you saw were two `ERROR` messages (because the operation failed twice, as per `--default-retries`), followed by a `FATAL` message, which is to explain why we bailed out -- but that wasn't a third attempt.

Behavior is as expected.

**Comment by mizioumt** [comment]
I made another multitasking kind of mistake. As mentioned in #272 it was in fact --default-retries 1, not default-retries 2, sorry about the mess.

**Comment by shlomi-noach** [comment]
@mizioumt a deeper look shows that the two `ERROR` messages were produced in different stack traces, which means the error was _reported_ twice, but the 2nd report does not mean the operation was actually attempted. It's just that somewhere along the backtrack we logged the same error again.
