### ISSUE TITLE
v1.0.21 gh-ost fails attempting to insert NULL into a NON NULL column.

### ISSUE THREAD

**Issue by mizioumt** [github/gh-ost#272]
100M rows table, gh-ost with -test-on-replica, to add a couple of columns, fails very fast. 

1.  ERROR Error 1048: Column 'column_name' cannot be null; query=

and indeed column_name is an existing column which is NOT NULL yet gh-ost attempts to REPLACE a NULL into it.

2. messages like this: Err: runtime error: slice bounds out of range

not sure about the correlation between 1. and 2.

I can reproduce 1. easily but only on the original huge table.

I managed to reproduce 2. [without 1.] on a 50K row subset but sanitizing of this data for upload is difficult.

There is also a 3. but it's not a concern at the moment, an occasional

3. 

2016-10-14 15:31:27 DEBUG Done streaming
2016-10-14 15:31:27 FATAL {%!!(MISSING)d(string=binlog.010194) 97527743 0} successive failures in streamer reconnect at coordinates %!!(MISSING)v(MISSING)

**Comment by mizioumt** [comment]
s/^\s+1./ with 1,2,3 but I don't know the editor yet.

**Comment by shlomi-noach** [comment]
Please consider styling with Markdown, this will make reading your comments so much easier: https://guides.github.com/features/mastering-markdown/

Re: 3, please download latest release `1.0.21`

Re: 1, please indicate table structure + `gh-ost` invocation command, or else I have no information to work with

Re: 2, this certainly shouldn't happen, but you say you reproduce it? Can you at least provide with table schema?

**Comment by mizioumt** [comment]
I think that was already 1.0.21... I'll double check if I accidentally invoked an earlier version when reproducing.
To clear some confusion I saw in email, the column where gh-ost attempts to insert a NULL is an existing column. It is not part of the ALTER statement.

**Comment by shlomi-noach** [comment]
Please paste table schema and alter statement

**Comment by mizioumt** [comment]
table definition:

```SQL
*************************** 1. row ***************************
       Table: Table_name
Create Table: CREATE TABLE `Table_name` (
  `column_1` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `column_2` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `column_3` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_4` varchar(80) DEFAULT NULL,
  `column_5` varchar(255) DEFAULT NULL,
  `column_6` date DEFAULT NULL,
  `column_7` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_8` varchar(255) DEFAULT NULL,
  `column_9` date DEFAULT NULL,
  `column_10` tinyint(3) unsigned DEFAULT NULL,
  `column_11` int(10) unsigned DEFAULT NULL,
  `column_12` int(10) unsigned NOT NULL DEFAULT '0',
  `column_13` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_14` char(2) NOT NULL DEFAULT '',
  `column_15` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_16` varchar(15) NOT NULL DEFAULT '',
  `column_17` varchar(255) NOT NULL DEFAULT '',
  `column_18` varchar(10) DEFAULT NULL,
  `column_19` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_20` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_21` varchar(80) NOT NULL DEFAULT '',
  `column_22` varchar(80) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_23` varchar(80) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_24` varchar(15) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_25` char(2) NOT NULL DEFAULT '',
  `column_26` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_27` varchar(40) DEFAULT NULL,
  `column_28` varchar(20) DEFAULT NULL,
  `column_29` tinyint(4) NOT NULL DEFAULT '0',
  `column_30` tinyint(4) NOT NULL DEFAULT '0',
  `column_31` tinyint(4) NOT NULL DEFAULT '0',
  `column_32` char(3) DEFAULT NULL,
  `column_33` varchar(255) DEFAULT NULL,
  `column_34` tinyint(4) DEFAULT '1',
  `column_35` varchar(100) DEFAULT NULL,
  `column_36` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_37` text CHARACTER SET utf8mb4,
  `column_38` tinyint(4) NOT NULL DEFAULT '1',
  `column_39` enum('','enum_value1') NOT NULL DEFAULT '',
  `column_40` varchar(255) NOT NULL DEFAULT '',
  `column_41` varchar(255) NOT NULL DEFAULT '',
  `column_42` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_43` char(1) NOT NULL DEFAULT '',
  `column_44` int(10) unsigned NOT NULL,
  `column_45` int(10) unsigned DEFAULT NULL,
  `column_46` char(2) DEFAULT NULL,
  `column_47` varchar(8) DEFAULT NULL,
  `column_48` int(10) unsigned DEFAULT NULL,
  `column_49` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_50` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_51` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_52` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_53` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_54` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_55` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_56` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_57` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_58` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_59` bigint(20) unsigned DEFAULT NULL,
  `column_60` bigint(20) unsigned DEFAULT NULL,
  `column_61` bigint(20) unsigned DEFAULT NULL,
  `column_62` bigint(20) unsigned DEFAULT NULL,
  `column_63` bigint(20) unsigned DEFAULT NULL,
  `column_64` bigint(20) unsigned DEFAULT NULL,
  `column_65` bigint(20) unsigned DEFAULT NULL,
  `column_66` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`column_1`),
  KEY `column_12` (`column_12`),
  KEY `column_3` (`column_3`),
  KEY `column_16` (`column_16`),
  KEY `column_17` (`column_17`),
  KEY `column_11` (`column_11`),
  KEY `column_31` (`column_31`),
  KEY `column_36` (`column_36`),
  KEY `just_a_name` (`column_39`),
  KEY `column_44` (`column_44`),
  KEY `column_46` (`column_46`),
  KEY `column_45` (`column_45`),
  KEY `column_30` (`column_30`,`column_2`),
  KEY `column_48` (`column_48`),
  KEY `column_15` (`column_15`(10)),
  KEY `column_58` (`column_58`),
  KEY `column_21__column_3` (`column_21`,`column_3`),
  KEY `column_52__column_3` (`column_52`,`column_3`),
  KEY `column_61` (`column_61`),
  KEY `column_62` (`column_62`),
  KEY `column_63` (`column_63`),
  KEY `column_64` (`column_64`),
  KEY `column_65` (`column_65`),
  KEY `column_66` (`column_66`)
) ENGINE=InnoDB AUTO_INCREMENT=966783334 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC
```

**Comment by mizioumt** [comment]
ALTER:

alter /* gh-ost */ table `database_name`.`_Table_name_gho` add column x bigint unsigned null default null, add column y bigint unsigned null default null

**Comment by mizioumt** [comment]
I'll try to prepare the complete sanitized log tomorrow. For now the errors.
Each !SNIP! may correspond to more than one value.
It would be good to have a log with would quote the values:

foo 'bar zog'

instead of 

foo bar zog

```
...
Copy: 0/98199724 0.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: binlog.010185:47471332; State: migrating; ETA: N/A
2016-10-14 11:27:48 INFO StreamEvents encountered unexpected error: Err: runtime error: slice bounds out of range
 Stack: goroutine 34 [running]:
github.com/github/gh-ost/vendor/github.com/scolumn_1dontang/go-mysql/mysql.Pstack(0x0, 0x0)
...
Copy: 0/98199724 0.0%; Applied: 0; Backlog: 34/100; Time: 1s(total), 1s(copy); streamer: binlog.010185:47516982; State: migrating; ETA: N/A
2016-10-14 11:27:48 ERROR Error 1048: Column 'column_31' cannot be null; query=
>···>···>···replace /* gh-ost `rescore`.`_Table_name_gho` */ into
>···>···>···>···`rescore`.`_Table_name_gho`
>···>···>···>···>···(`column_1`, `column_2`, `column_3`, `column_4`, `column_5`, `column_6`, `column_7`, `column_8`, `column_9`, `column_10`, `column_11`, `column_12`, `column_13`, `column_14`, `column_15`, `column_16`, `column_17`, `column_18`, `column_19`, `column_20`, `column_21`, `column_22`, `column_23`, `column_24`, `column_25`, `column_26`, `column_27`, `column_28`, `column_29`, `column_30`, `column_31`, `column_32`, `column_33`, `column_34`, `column_35`, `column_36`, `column_37`, `column_38`, `column_39`, `column_40`, `column_41`, `column_42`, `column_43`, `column_44`, `column_45`, `column_46`, `column_47`, `column_48`, `column_49`, `column_50`, `column_51`, `column_52`, `column_53`, `column_54`, `column_55`, `column_56`, `column_57`, `column_58`, `column_59`, `column_60`, `column_61`, `column_62`, `column_63`, `column_64`, `column_65`, `column_66`)
>···>···>···>···values
>···>···>···>···>···(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
>···>···; args=[!SNIP! <nil> <nil> <nil> <nil> <nil> !SNIP! <nil> !SNIP! <nil> <nil> <nil> 0 <nil> <nil> !SNIP! <nil> <nil> <nil> <nil> <nil> !SNIP! <nil> th <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>]
goroutine 55 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
```

**Comment by mizioumt** [comment]
I could run a debugging version of gh-ost while I still have the table. I planned to look at the code but this is not for short term.

**Comment by shlomi-noach** [comment]
> It would be good to have a log with would quote the values: foo 'bar zog' instead of foo bar zog

Sorry, what do "foo", "bar" and "zog" stand for in your example?

**Comment by shlomi-noach** [comment]
Oh I think you mean the `args=` values.

**Comment by mizioumt** [comment]
yes, if the values are like so:
```
col1 => 'foo'
col2 => 'bar zog'
```
they would appear in the args= list as
```
foo bar zog
```
quoted values like 'bar zog' look better and could help in investigating string truncation, empty strings, this kind of stuff.

**Comment by mizioumt** [comment]
[problemn.txt](https://github.com/github/gh-ost/files/536919/problemn.txt)

**Comment by mizioumt** [comment]
the problem is reproducible still. The attached log is for this command:

 ./gh-ost-20161013142859 -conf ~/.my_gh-ost.cnf -database database_name -table table_name -alter 'add column x bigint unsigned null default null, add column y bigint unsigned null default null' -test-on-replica -host `hostname` -initially-drop-ghost-table -initially-drop-socket-file -debug -verbose -stack -default-retries 1 --initially-drop-old-table -execute

it does not insert any records into the new table, none.
Each !SNIP! may correspond to several values, however, the count of <nil> remains correct.

**Comment by shlomi-noach** [comment]
Thank you for all the input, I will continue to look into this!

**Comment by mizioumt** [comment]
there is something that skipped my mind because of multitasking, sorry.

**The table in question has a different structure on the replica that it does on the master.**

It is still compatible wrt replication. Specifically, tailing columns column_59 to column_66 do not exist on the master.

So maybe it's more of a feature request. I have two question.

A. Is this case supported: table on replica has a different but replication compatible structure with that on the master? Especially in the case of extra columns. If it is supported, we have this bug. If it is not supported, the bug is that gh-ost should have spotted that and aborted at once.

B. I also saw an occasional 'slice out of bounds' error followed by 'FATAL.*MISSING' error, problems 2 and 3 in the bug. As I now realize **that table did not exist on the master at all*. Same question, is any such thing supported? If not, the bug is again that the situation was not spotted.

If none of this is supported, maybe you could consider supporting that. In this case **B** is more important in our environment. It can be something like this multimaster replication graph:

```
M1 -> M2 -> S1 S2...
```

M2 has its own tables that are not present on M1, and receive its own DML for those. Suppose we want to change a table only exists on M2, would gh-ost be able to help?

**Comment by shlomi-noach** [comment]
> The table in question has a different structure on the replica that it does on the master.

This is not supported and I don't expect it to ever be supported.

> A. Is this case supported: table on replica has a different but replication compatible structure with that on the master? Especially in the case of extra columns. If it is supported, we have this bug. If it is not supported, the bug is that gh-ost should have spotted that and aborted at once.

What we can certainly have is a master-replica comparison mechanism, and let the user know when master and replica schemas are not identical.

> B. I also saw an occasional 'slice out of bounds' error followed by 'FATAL.MISSING' error, problems 2 and 3 in the bug. As I now realize *that table did not exist on the master at all*. Same question, is any such thing supported? If not, the bug is again that the situation was not spotted.

I don't wish to pursue the reasons for `slice out of bounds` given this unsupported scenario. However "that table did not exist on the master at all" confuses me. What table didn't exist on the master?

> M2 has its own tables that are not present on M1, and receive its own DML for those. Suppose we want to change a table only exists on M2, would gh-ost be able to help?

You can migrate directly on the master, if it uses RBR. Use `--allow-on-master` and set `--host-the.master.host`. If the master does not have RBR, you can perhaps setup a new, special replica just for that. If not, no game.

**Comment by mizioumt** [comment]
OK let's close it then. The table that did not exist on the master at all was a differently named table with the same structure. I used that for some experiments related to the original bug.
