### ISSUE TITLE
Investigate how gh-ost (via go-lang) handles non-alphabetical enums in primary keys

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#273]
Based on the bug report for pt-online-schema-change: https://bugs.launchpad.net/percona-toolkit/+bug/1613915

tl;dr: For pt-osc, enums in primary keys weren't handled correctly (the enum values were seen as their names vs their index numbers) if the values weren't in alphabetical order already. http://dev.mysql.com/doc/refman/5.6/en/enum.html#enum-sorting

The fix for pt-osc is already merged: https://github.com/percona/percona-toolkit/pull/131

It's worth testing if this is handled correctly here with gh-ost too.

**Comment by shlomi-noach** [comment]
closed by #277
