### ISSUE TITLE
Stopped read mysql-bin-changelog without any notifications

### ISSUE THREAD

**Issue by palexvs** [github/gh-ost#275]
gh-ost: 1.0.21
MySQL 5.7.11 (AWS RDS: master<->slave)
Operation mode: connect to replica, migrate on master

I tried to migrate big table (>200M records) and after 28 hours of migration I got message that everything is ready for switching:

```
2016-10-18 20:43:16 DEBUG Getting nothing in the write queue. Sleeping...
Copy: 237640472/237640472 100.0%; Applied: 586055; Backlog: 0/100; Time: 28h35m0s(total), 27h32m0s(copy); streamer: mysql-bin-changelog.001124:14196316; State: postponing cut-over; ETA: due
2016-10-18 20:43:17 DEBUG Getting nothing in the write queue. Sleeping...
```

I compared the original table with the copy and found that they are not identical: >100K records do not exist in the copy.

Log does not show any errors but says that gh-ost was reading `mysql-bin-changelog` from the same file 001124 from the same position 14196316) for the last 21 hours, so all updates were not copied:

```
Copy: 69330000/230650433 30.1%; Applied: 585401; Backlog: 4/100; Time: 6h57m0s(total), 6h57m0s(copy); streamer: mysql-bin-changelog.001124:4394961; State: migrating; ETA: 16h10m17s
Copy: 69416000/230650433 30.1%; Applied: 585964; Backlog: 3/100; Time: 6h57m30s(total), 6h57m30s(copy); streamer: mysql-bin-changelog.001124:12757012; State: migrating; ETA: 16h9m44s
Copy: 69526000/230650433 30.1%; Applied: 586055; Backlog: 0/100; Time: 6h58m0s(total), 6h58m0s(copy); streamer: mysql-bin-changelog.001124:14196316; State: migrating; ETA: 16h8m42s
....
Copy: 237640472/237640472 100.0%; Applied: 586055; Backlog: 0/100; Time: 28h40m30s(total), 27h32m0s(copy); streamer: mysql-bin-changelog.001124:14196316; State: postponing cut-over; ETA: due
```

Command:

```
./gh-ost \
  --tungsten \
  --assume-master-host='sql01.xxxx.amazonaws.com' \
  --assume-rbr \
  --chunk-size=1000 \
  --nice-ratio=1 \
  --throttle-control-replicas='sql02.xxxx.amazonaws.com' \
  --max-lag-millis=2000 \
  --host='sql02.xxxx.amazonaws.com' \
  --user='root' \
  --password='***' \
  --database='production' \
  --table='t1' \
  --verbose \
  --alter="ADD COLUMN c10 tinyint unsigned" \
  --cut-over=default \
  --allow-master-master \
  --default-retries=1200 \
  --panic-flag-file=/tmp/ghost.panic.flag \
  --postpone-cut-over-flag-file=/tmp/ghost.postpone.flag \
  --throttle-additional-flag-file=/tmp/ghost.throttle.flag \
  --initially-drop-ghost-table \
  --debug \
  --stack \
  --execute > gh.log 2>&1
```

**Comment by shlomi-noach** [comment]
> Log does not show any errors but says that gh-ost was reading mysql-bin-changelog from the same file 001124 from the same position 14196316) for the last 21 hours, so all updates were not copied:

So this was a `tungsten` cluster, correct?

To complete the story, I assume binary logs did in fact advance on the replica, but `gh-ost` did not pursue those changes?

Since I'm not a `tungsten` user I have no immediate insight on this.

Referencing https://github.com/github/gh-ost/issues/258#issuecomment-252196241 -- likely unrelated, because `gh-ost`'s reported position does not advance.

I wonder if you could run a `--test-on-replica` ; this would typically run faster. If this reproduces, maybe we can have a better chance at finding the problem.

**Comment by palexvs** [comment]
I found probably something useful in `mysql-error-running.log`
```
2016-10-21 09:10:05 513831 [Note] Aborted connection 513831 to db: 'information_schema' user: 'root' host: '10.0.2.104' (Got timeout reading communication packets)
2016-10-21 09:10:05 513833 [Note] Aborted connection 513833 to db: 'production' user: 'root' host: '10.0.2.104' (Got timeout reading communication packets)
2016-10-21 09:54:44 513832 [Note] Aborted connection 513832 to db: 'unconnected' user: 'root' host: '10.0.2.104' (Failed on my_net_write())
```

10.0.2.104 - server on which I run './gh-ost ...'
I see the same the same value for `streamer: ` and `Applied:` in gh.log after '09:54:06'

**Comment by shlomi-noach** [comment]
@palexvs would you mind trying out https://github.com/github/gh-ost/pull/286? This fetches the latest `go-mysql` library, which hopefully solves your issue.

**Comment by palexvs** [comment]
I tried two times and results are the same:
migration is going but `streamer: XXX` and `Applied: XXX` are the same after some moment

During the last migration `streamer` stopped update between `2016-10-27 10:31:17` and `2016-10-27 10:31:47`
In MySQL err log I see:
```
2016-10-27T10:32:38.352336Z 552846 [Note] Aborted connection 552846 to db: 'unconnected' user: 'root' host: '10.0.2.104' (Failed on my_net_write())
```
In same moment a monitoring shows CPU load increasing from ~1-5% up to 60%

I don't know what can be result and what can be a reason

**Comment by palexvs** [comment]
@shlomi-noach, https://github.com/github/gh-ost/pull/286 - it has not resolved my issue, but https://github.com/github/gh-ost/pull/286 + https://github.com/siddontang/go-mysql (master) has resolved it - I have smoothly migrated a few large tables (> 100M records)

I really love your tool and appreciate your work. Thanks!

**Comment by shlomi-noach** [comment]
@palexvs thank you so much for the information.

FYI, a couple days ago I merged https://github.com/github/gh-ost/pull/375, which is merge of up-to-date go-mysql -- I expect this to work for you in exact same way as you solved it -- can you confirm?

**Comment by palexvs** [comment]
Cool. I am going to start migration today and I will write about results in ~4 days

**Comment by palexvs** [comment]
I tried v1.0.35 and I have not got this issue, so close it

P.S: But v1.0.35 lost 1M records from 400M, but it's another story

**Comment by shlomi-noach** [comment]
> P.S: But v1.0.35 lost 1M records from 400M, but it's another story

WAT 😱

**Comment by hhyo** [comment]
try set  [ReadTimeout time.Duration](https://github.com/go-mysql-org/go-mysql/blob/33ea963610607f7b5505fd39d0955b78039ef783/replication/binlogsyncer.go#L85)

https://github.com/github/gh-ost/blob/ed46138c06430421b44fe285a26a44398b256a1c/go/binlog/gomysql_reader.go#L43-L53

https://github.com/github/gh-ost/issues/179
