### ISSUE TITLE
Add flag to ignore triggers if they exist

### ISSUE THREAD

**Issue by akshaychhajed** [github/gh-ost#284]
As discussed in issue #153 's [comment] (https://github.com/github/gh-ost/issues/153#issuecomment-247869197)
Currently gh-ost exits if triggers are detected.
If this flag is set, triggers will be ignored and gh-ost will continue without working on them.
Credit: @allixsenos

I would like to try and submit a pull request for this feature.

**Comment by allixsenos** [comment]
thanks for picking this up

**Comment by shlomi-noach** [comment]
@akshaychhajed thank you, let's first clarify the following:

- will the table be migrated without triggers? Thus, the _ghost_ table will be triggerless?

- in which case, why wouldn't you just drop the triggers before running the migration?

- or, do you mean triggers will be ignored by migration, and created on the _ghost_ table at the very end?

- in which case I'd rather implement https://github.com/github/gh-ost/issues/153 is possible.

**Comment by akshaychhajed** [comment]
- Reading from the [comment](https://github.com/github/gh-ost/issues/153#issuecomment-247869197), I was aiming for the 1st one with this flag.
- we cannot drop them because user might want them to move them manually
- Implementing #153 by creating triggers in the end seems like better solution as it will not slow down the operation. 
I am worried about inconsistency when applying events on ghost before triggers are in place. Will the changes by triggers on master be moved to ghost table during migration ?

Just to be clear, are you suggesting we implemeant #153 and remove the need for this flag entirely?

**Comment by allixsenos** [comment]
for my use case I'd like to use this in combination with delayed cutover which would allow me to run a migration on a table that has triggers and then manually take care of them at the time when I trigger the cutover

this would be a stopgap measure to being able to migrate tables with triggers where I'd like gh-ost to offer the ability to add the same triggers to the new table and optionall remove them from the source table

**Comment by shlomi-noach** [comment]
> we cannot drop them because user might want them to move them manually

I'm just clarifying that the migration will effectively drop them via your suggestion.

> Implementing #153 by creating triggers in the end seems like better solution as it will not slow down the operation. I am worried about inconsistency when applying events on ghost before triggers are in place. Will the changes by triggers on master be moved to ghost table during migration

As per #153 if we create the triggers on the _ghost_ table while in the cut-over phase, there is no inconsistency. There is a point in time when there are no writes on the _ghost_ table.

> Just to be clear, are you suggesting we implemeant #153 and remove the need for this flag entirely?

If you like to :)

If you feel there's a strong case to the "ignore" approach, that's also valid, and may be removed in the future should #153 be fully implemented.

**Comment by shlomi-noach** [comment]
@allixsenos 

> for my use case I'd like to use this in combination with delayed cutover which would allow me to run a migration on a table that has triggers and then manually take care of them at the time when I trigger the cutover

but you would get an inconsistency. Postponing cut-over means changes are still being intercepted and applied on the _ghost_ table. Triggers are still in place.

**Comment by allixsenos** [comment]
honestly I could live with a few seconds of trigger downtime, or a few seconds of both tables running them, and would appreciate the opportunity to handle it myself over gh-ost saying "oh, nope, not touching that" and forcing me to swallow days of trigger downtime

**Comment by akshaychhajed** [comment]
Currently, there is no way around to use gh-ost with triggers (other than removing them from master). We build the ignore option which will atleast give them a way around it. This flag will default to false, so users who explicitly use it would understand the risks(probably a message on screen when this option is exercised).

**Comment by tomkrouper** [comment]
I really don't like the idea of introducing a feature that would knowingly lose data. Even if we had warnings and special options. Any data loss (unless you are dropping a column) from a gh-ost migration, I would call a failure.

**Comment by akshaychhajed** [comment]
Looking at greater purpose of the tool is to ensure all data integrity and this option may not be inline with that. I understand the issue is more about keeping the tool predictable and offer a level of confidence to the user when it comes to data integrity. Lets close this issue and start working towards implementing #153.
Thank you @tomkrouper @shlomi-noach for your insight!
@allixsenos I will try #153 and it would be great if you can provide feedback. Sorry your wait got little longer.

**Comment by allixsenos** [comment]
of course :)

On Fri., 21 Oct. 2016 at 07:55, Akshay Chhajed <notifications@github.com>
wrote:

Looking at greater purpose of the tool is to ensure all data integrity and
this option may not be inline with that. I understand the issue is more
about keeping the tool predictable and offer a level of confidence to the
user when it comes to data integrity. Lets close this issue and start
working towards implementing #153
<https://github.com/github/gh-ost/issues/153>.
Thank you @tomkrouper <https://github.com/tomkrouper> @shlomi-noach
<https://github.com/shlomi-noach> for your insight!
@allixsenos <https://github.com/allixsenos> I will try #153
<https://github.com/github/gh-ost/issues/153> and it would be great if you
can provide feedback. Sorry your wait got little longer.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/github/gh-ost/issues/284#issuecomment-255299958>, or mute
the thread
