### ISSUE TITLE
Make `-concurrent-rowcount` default to true

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#285]
Based on conversations as a result of the Pythian blog post https://www.pythian.com/blog/using-gh-ost-online-schema-changes/ 

Right now if you choose `--exact-rowcount` the migration will wait until the select finishes because it's only if you also use `--concurrent-rowcount` that it'll do the select in a separate thread. And if the non-concurrent select takes 5 minutes, the count is 5 minutes old when the migration starts, which can leave the progress calculations inaccurate (hence the FR https://github.com/github/gh-ost/issues/194). 
- do we want `--concurrent-rowcount` to default to true if `--exact-rowcount` is true?
- or do we want both of these defaulting to true?
- or do we want `--exact-rowcount` to just be concurrent and drop the other flag?
- how is babby formed?

Is there any use case for having a not-concurrent count run and finish before the migration starts?

**Comment by shlomi-noach** [comment]
Let's begin by defaulting `concurrent-rowcount` to `true`, and take it in small steps.
