### ISSUE TITLE
data divergent between original and ALTERed table: stale records in gh-ost table after ALTER

### ISSUE THREAD

**Issue by mizioumt** [github/gh-ost#287]
v1.0.21

attempted to change a table's PK with `--test-on-replica`.
gh-ost finished without errors but the data diverged considerably.
Reproduced this twice.

invocation:

```
 ./gh-ost-20161013142859 -conf ~/.my_gh-ost.cnf -database db_name -table table_name -alter "row_format=dynamic,drop primary key, add primary key(id,another_column),add unique key(id)" -test-on-replica -host `hostname` -initially-drop-ghost-table -initially-drop-socket-file -serve-socket-file ~/gh-ost.rr.socket -assume-rbr -default-retries 1 -verbose -debug -stack -execute
```

`add primary key(id,another_column)`: original PK was on `id` so this is guaranteed to be UNIQUE

`add unique key(id)`: without that gh-ost would complain about lack of common UNIQUE index on original and gh-ost tables. So I added this.

Difference in at least one record:

```
diff record.orig record.gho
17c17
<             last_change: 2016-10-20 16:45:31
---
>             last_change: 2015-10-02 16:29:28
...
a few more columns...
```

with last_change being

```
  `last_change` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
```

so in the original table the record is updated while in the _gho table an old version of the record is present.

There are many more differences that this one. For example the number of rows in the original table and the _gho table differs by some 300000. Furthermore if we consider the count N of rows that are common (by equal `id`) between the original and the _gho tables, it is different from either of count(*) found in the original table and the _gho table.

I'll post the log and the table structure separately.

**Comment by mizioumt** [comment]
table structure. I did verify it is the same on the replica and on the master

```
*************************** 1. row ***************************
       Table: Table_name
Create Table: CREATE TABLE `Table_name` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `another_column` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_1` int(10) unsigned NOT NULL DEFAULT '0',
  `column_2` date NOT NULL DEFAULT '0000-00-00',
  `column_3` date NOT NULL DEFAULT '0000-00-00',
  `column_4` int(10) unsigned DEFAULT NULL,
  `column_5` int(10) unsigned DEFAULT NULL,
  `column_6` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `column_8` double NOT NULL DEFAULT '0',
  `column_9` varchar(1024) DEFAULT NULL,
  `column_10` varchar(1024) DEFAULT NULL,
  `column_11` varchar(1024) DEFAULT NULL,
  `column_12` enum(value_list) NOT NULL DEFAULT 'a_string',
  `column_13` char(3) NOT NULL DEFAULT '',
  `last_change` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `column_14` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_15` varchar(255) DEFAULT NULL,
  `column_16` float NOT NULL DEFAULT '0',
  `column_17` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `column_18` int(11) DEFAULT NULL,
  `column_19` int(11) NOT NULL DEFAULT '0',
  `column_20` double DEFAULT NULL,
  `column_21` double DEFAULT NULL,
  `column_22` date DEFAULT NULL,
  `column_23` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_24` varchar(40) DEFAULT NULL,
  `column_25` char(1) DEFAULT NULL,
  `column_26` text,
  `column_27` enum(value_list) DEFAULT NULL,
  `column_28` text CHARACTER SET utf8mb4,
  `column_29` text CHARACTER SET utf8mb4,
  `column_30` tinyint(4) NOT NULL DEFAULT '1',
  `column_31` double NOT NULL DEFAULT '0',
  `column_32` varchar(512) DEFAULT NULL,
  `column_33` varchar(255) DEFAULT NULL,
  `column_34` tinyint(4) NOT NULL DEFAULT '1',
  `column_35` int(11) DEFAULT NULL,
  `column_36` tinyint(3) unsigned DEFAULT NULL,
  `column_37` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `column_38` bigint(20) unsigned DEFAULT NULL,
  `column_39` varchar(8) DEFAULT NULL,
  `column_40` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_41` int(10) unsigned NOT NULL DEFAULT '0',
  `column_42` smallint(5) unsigned NOT NULL DEFAULT '0',
  `column_43` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'points_to_elsewhere',
  `column_44` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'points_to_elsewhere',
  `column_45` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'points_to_elsewhere',
  PRIMARY KEY (`id`),
  KEY `column_3` (`column_3`,`column_2`),
  KEY `column_12` (`column_12`),
  KEY `another_column` (`another_column`),
  KEY `column_30` (`column_30`),
  KEY `column_14` (`column_14`),
  KEY `column_1` (`column_1`),
  KEY `column_2` (`column_2`,`column_3`),
  KEY `column_40` (`column_40`),
  KEY `last_change` (`last_change`),
  KEY `column_41_2` (`column_41`,`last_change`),
  KEY `column_43` (`column_43`),
  KEY `column_41` (`column_41`,`column_2`)
) ENGINE=InnoDB AUTO_INCREMENT=N DEFAULT CHARSET=latin1
```

**Comment by mizioumt** [comment]
[out.txt](https://github.com/github/gh-ost/files/551000/out.txt)

gh-ost output uploaded

**Comment by mizioumt** [comment]
the `id` of the diverging record I showed above is 777455597

**Comment by mizioumt** [comment]
I reproduced this for a more conventional ALTER: no PK change, just a bunch of DROP column and one MODIFY COLUMN. The pattern is the same, different record counts and at least one record 'older' in the ghost table than in the replica table, based on value for `last_changed` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

**Comment by shlomi-noach** [comment]
Please share your more conventional `ALTER`

**Comment by mizioumt** [comment]
for the no-PK-change ALTER, this is not the same table. Here is the structure:

```
*************************** 1. row ***************************
       Table: Table_name
Create Table: CREATE TABLE `Table_name` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `last_change` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `column_1` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_2` varchar(80) DEFAULT NULL,
  `column_3` varchar(255) DEFAULT NULL,
  `column_4` date DEFAULT NULL,
  `column_5` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_6` varchar(255) DEFAULT NULL,
  `column_7` date DEFAULT NULL,
  `column_8` tinyint(3) unsigned DEFAULT NULL,
  `column_9` int(10) unsigned DEFAULT NULL,
  `column_10` int(10) unsigned NOT NULL DEFAULT '0',
  `column_11` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_12` char(2) NOT NULL DEFAULT '',
  `column_13` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_14` varchar(15) NOT NULL DEFAULT '',
  `column_15` varchar(255) NOT NULL DEFAULT '',
  `column_16` varchar(10) DEFAULT NULL,
  `column_17` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_18` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_19` varchar(80) NOT NULL DEFAULT '',
  `column_20` varchar(80) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_21` varchar(80) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `column_22` varchar(15) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_23` char(2) NOT NULL DEFAULT '',
  `column_24` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `column_25` varchar(40) DEFAULT NULL,
  `column_26` varchar(20) DEFAULT NULL,
  `column_27` tinyint(4) NOT NULL DEFAULT '0',
  `column_28` tinyint(4) NOT NULL DEFAULT '0',
  `column_29` tinyint(4) NOT NULL DEFAULT '0',
  `column_30` char(3) DEFAULT NULL,
  `column_31` varchar(255) DEFAULT NULL,
  `column_32` tinyint(4) DEFAULT '1',
  `column_33` varchar(100) DEFAULT NULL,
  `column_34` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_35` text CHARACTER SET utf8mb4,
  `column_36` tinyint(4) NOT NULL DEFAULT '1',
  `column_37` enum('','enum_value1') NOT NULL DEFAULT '',
  `column_38` varchar(255) NOT NULL DEFAULT '',
  `column_39` varchar(255) NOT NULL DEFAULT '',
  `column_40` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `column_41` char(1) NOT NULL DEFAULT '',
  `column_42` int(10) unsigned NOT NULL,
  `column_43` int(10) unsigned DEFAULT NULL,
  `column_44` char(2) DEFAULT NULL,
  `column_45` varchar(8) DEFAULT NULL,
  `column_46` int(10) unsigned DEFAULT NULL,
  `column_47` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_48` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_49` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_50` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_51` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_52` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_53` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_54` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_55` bigint(20) unsigned NOT NULL DEFAULT '0',
  `column_56` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `column_10` (`column_10`),
  KEY `column_1` (`column_1`),
  KEY `column_14` (`column_14`),
  KEY `column_15` (`column_15`),
  KEY `column_9` (`column_9`),
  KEY `column_29` (`column_29`),
  KEY `column_34` (`column_34`),
  KEY `just_a_name` (`column_37`),
  KEY `column_42` (`column_42`),
  KEY `column_44` (`column_44`),
  KEY `column_43` (`column_43`),
  KEY `column_28` (`column_28`,`last_change`),
  KEY `column_46` (`column_46`),
  KEY `column_13` (`column_13`(10)),
  KEY `column_56` (`column_56`),
  KEY `column_19__column_1` (`column_19`,`column_1`),
  KEY `column_50__column_1` (`column_50`,`column_1`)
) ENGINE=InnoDB AUTO_INCREMENT=N DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC
```

and gh-ost invocation is as follows:

```
 ./gh-ost-20161013142859 -conf ~/.my_gh-ost.cnf -database database_name -table Table_name -alter " drop column column_2,drop column column_3,drop column column_4,drop column column_5,drop column column_6,drop column column_11,drop column column_13,drop column column_38,drop column column_39,drop column column_35,drop column column_31,drop column column_30,modify column_46 bigint unsigned default null" -test-on-replica -host `hostname` -initially-drop-ghost-table -initially-drop-socket-file -serve-socket-file ~/gh-ost.hr.socket -assume-rbr --default-retries 1 --debug --verbose --stack -execute
```

**Comment by shlomi-noach** [comment]
The output is quite interesting. The TL;DR is:

```
Copy: 0/111243668 0.0%; Applied: 0; Backlog: 0/100; Time: 22s(total), 0s(copy); streamer: binlog.012921:93146850; State: migrating; ETA: N/A
...
Copy: 116397431/116397431 100.0%; Applied: 0; Backlog: 0/100; Time: 4h0m41s(total), 4h0m18s(copy); streamer: binlog.013220:81076275; State: migrating; ETA: due
```

Note `Applied: 0`

This means `gh-ost` did not process _any events_ from the binary logs. However it clearly _did_ process the binary logs since the binlog name increases throughout the migration. So `gh-ost` didn't find the relevant table entries in the binary logs.

I wonder: do you happen to have `replicate-rewrite-db` or `replicate-rewrite-table` in place?

**Comment by shlomi-noach** [comment]
Also, you use `assume-rbr`. Are you _sure_ the replica uses RBR? 

As you may know, `set global binlog_format='row'` is not enough -- because thr replication threas uses its own session `binlog_format`. You'd need to `stop slave; start slave` for this to take effect.

`assume-rbr` is useful for RDS users, where `gh-ost` is not allowed to switch into `binlog_format=ROW`.

**Comment by mizioumt** [comment]
I have this in my.cnf

```
log-bin          = ../log/binlog
binlog_format    = ROW
binlog_row_image = full
sync_binlog      = 1
expire_logs_days = 1
log_slave_updates = 0
```

I should stop using assume-rbr, though.

No, I don't have any replicate-rewrite-db|table or similar replication filters.

**Comment by mizioumt** [comment]
the idea that no binlogs records have been processed is viable. The overall amount of data divergence is rather large so it does look as if few if any binlog records have been used.
BTW does gh-ost need log_slave_updates by any chance?

**Comment by shlomi-noach** [comment]
> BTW does gh-ost need log_slave_updates by any chance?

Yes it does! But I'm surprised now, because `gh-ost` bails out when it is not the case. I'm looking into why `gh-ost` didn't tell you the settings were insufficient.

This clearly explains your problem.

**Comment by shlomi-noach** [comment]
Can you please paste the exact output you get from `select @@global.log_slave_updates` ?

**Comment by shlomi-noach** [comment]
Also: do you happen to have both master and replica on same host? 
If not, and since I'm unfamiliar with your setup, can you suspect why `gh-ost` would assume both master and replica are the same server?

**Comment by shlomi-noach** [comment]
For reference, this is what `gh-ost` says when I execute on a server without `log_slave_updates`:

```
2016-10-28 14:09:17 INFO starting gh-ost
2016-10-28 14:09:17 INFO Migrating `test`.`sample_data_0`
2016-10-28 14:09:17 INFO executing gh-ost-on-startup hook: /path/to/dev/go/src/github.com/github/gh-ost/resources/hooks-sample/gh-ost-on-startup-hook

2016-10-28 14:09:17 INFO connection validated on test-box:22297
2016-10-28 14:09:17 INFO User has ALL privileges
2016-10-28 14:09:17 INFO test-box:22297 has STATEMENT binlog_format. I will change it to ROW, and will NOT change it back, even in the event of failure.
2016-10-28 14:09:17 INFO binary logs validated on test-box:22297
2016-10-28 14:09:17 INFO Restarting replication on test-box:22297 to make sure binlog settings apply to replication thread
2016-10-28 14:09:17 DEBUG Replication restarted
2016-10-28 14:09:17 DEBUG 'ROW' binlog format applied
2016-10-28 14:09:17 INFO Table found. Engine=InnoDB
2016-10-28 14:09:17 DEBUG Estimated number of rows via STATUS: 2915
2016-10-28 14:09:18 DEBUG Validated no foreign keys exist on table
2016-10-28 14:09:18 DEBUG Validated no triggers exist on table
2016-10-28 14:09:18 INFO Estimated number of rows via EXPLAIN: 2915
2016-10-28 14:09:18 DEBUG Potential unique keys in sample_data_0: [PRIMARY (auto_increment): [id]; has nullable: false]
2016-10-28 14:09:18 DEBUG Looking for master on test-box:22297
2016-10-28 14:09:18 DEBUG Master of test-box:22297 is test-box:22293
2016-10-28 14:09:18 DEBUG Looking for master on test-box:22293
2016-10-28 14:09:18 INFO Master found to be test-box:22293
2016-10-28 14:09:18 INFO executing gh-ost-on-failure hook: /path/to/dev/go/src/github.com/github/gh-ost/resources/hooks-sample/gh-ost-on-failure-hook

2016-10-28 14:09:18 FATAL test-box:22297 must have log_slave_updates enabled
```

**Comment by mizioumt** [comment]
for log-slave-updates I'm pretty sure I had this:

```
[mizioumtchen@rescoredb-gh-ost-1 ~]$ grep slave.upd vars.out
log_slave_updates       OFF
```

currently I've set it to ON and I'm running another experiment.
However I can't remember gh-ost ever bailing ot with 'must have log_slave_updates enabled'.
I'll do another experiment when this one is over.

As for the master hostname it is of course different from the replica. There is another master in between.
If you mean that the logs I supply say HOSTNAME:3306, in my sanitizaer script any thing that looks like a hostname is cast to HOSTNAME, foo1.zoo.com, foo2.zoo.com, everything.

**Comment by shlomi-noach** [comment]
> However I can't remember gh-ost ever bailing out with 'must have log_slave_updates enabled'.
I'll do another experiment when this one is over.

It's really important that I get the answer for `select @@global.log_slave_updates`. Actually, make that `select @@global.log_slave_updates, version()`

> There is another master in between.

then perhaps _that_ master doesn't have `log_slave_updates`?

**Comment by mizioumt** [comment]
the master in between does have log_slave_updates

```
select @@log_slave_updates,@@version;
+---------------------+------------+
| @@log_slave_updates | @@version  |
+---------------------+------------+
|                   1 | 5.6.27-log |
+---------------------+------------+
```

what the replica had when the issue was reported is log_slave_updates=OFF to the best of my knowledge. To find out precisely what it had requires some digging, I'd rather rerun a carefully controlled experiment with and without log_slave_updates on the replica.
The replica's version is 5.7.15-log.

**Comment by shlomi-noach** [comment]
thank you.

coming to think of this more, it must have had `log_slave_updates`. Otherwise an internal hint `gh-ost` sends to itself wouldn't have been detected and the migration would not have started in the first place.

So we're looking at other directions then...

**Comment by mizioumt** [comment]
well I currently have a case where gh-ost is happily running with this:

```
root@rescoredb-gh-ost-2 [(none)]> select @@version,@@log_slave_updates;show variables like 'log_slave_updates';
+------------+---------------------+
| @@version  | @@log_slave_updates |
+------------+---------------------+
| 5.6.33-log |                   0 |
+------------+---------------------+
1 row in set (0.00 sec)

+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| log_slave_updates | OFF   |
+-------------------+-------+
1 row in set (0.00 sec)
```

I could file an issue for this next week. It would also be interesting to see if this run will result in divergent data.

**Comment by shlomi-noach** [comment]
Of course this test will result with divergent data, I'm happy to save you the experiment time. 

Now to understand _why_ ghost said nothing about `@@log_slave_updates=0`. I was hoping you'd show me a `OFF` like in the `show variables`, in which case I would be able to understand how that happened. But its a `0` and shouldn't happen.

**Comment by mizioumt** [comment]
I like to set var=0 where it's usually done through var=OFF or skip-var. So this is a bit of MySQL trickery combined with my abuse thereof.
I am happy though that this is not a true data divergence issue.
Maybe you could close this one and create one for log_slave_updates. I think if gh-ost simply insists on SELECT @@log_slave_updates being ON it should be good enough for everyone.

**Comment by shlomi-noach** [comment]
> I think if gh-ost simply insists on SELECT @@log_slave_updates being ON it should be good enough for everyone.

That's the problem though: it _does_

https://github.com/github/gh-ost/blob/master/go/logic/inspect.go#L332-L344

**Comment by mizioumt** [comment]
I can't quite understand the process of selecting into a Boolean. How would it decide that 'OFF' is not a true value, for example. I can imagine '0' being a True value, though, on the basis of that not being an empty string. This is speculation, of course. Maybe @@log_slave_updates should be selected into a kind of string and inspected as a string.

**Comment by shlomi-noach** [comment]
I believe I've found the fallacy. I've introduced the wrong behavior in https://github.com/github/gh-ost/pull/155. While it correctly solved https://github.com/github/gh-ost/issues/135, it now missed the check for `test-on-replica`. Fixing.

> I can't quite understand the process of selecting into a Boolean. How would it decide that 'OFF' is not a true value, for example.

It's not an `OFF` in the first place. It's `0` or `1` and that translates correctly into a `bool`.

**Comment by shlomi-noach** [comment]
@mizioumt if you're able to build from #298 , this should quit with error when you execute on a replica without `log_slave_updates`.

**Comment by mizioumt** [comment]
I'm not building gh-ost yet... I will be

**Comment by shlomi-noach** [comment]
@mizioumt this has already been merged and released in https://github.com/github/gh-ost/releases/tag/v1.0.28
