### ISSUE TITLE
"Binlog Dump" thread not close after the schema change

### ISSUE THREAD

**Issue by rj03hou** [github/gh-ost#292]
gh-ost get binlog from the slave, after the ddl the "Binlog Dump" thread not close.
Another question, can you edit the readme.md add the build step? so I can try to solve this problem.

**Comment by shlomi-noach** [comment]
> gh-ost get binlog from the slave, after the ddl the "Binlog Dump" thread not close.

I'm sorry, not following you. How do you mean "after the ddl"? `gh-ost` is reading the binary logs throughout the entire operation.

> Another question, can you edit the readme.md add the build step? so I can try to solve this problem.

It's really best to open a new issue for this or else it's difficult to track down what's handled and what isn't. But, just run the `build.sh` script to build.

**Comment by rj03hou** [comment]
after the ddl, means the gh-ost has successful do the job.
but the connection to the slave to get binlog does not close.

**Comment by shlomi-noach** [comment]
@rj03hou please elaborate more, I'm failing to understand your description.

"after the ddl" is a description I do not understand. You and I may relate to different things here. What do you mean by "afetr the ddl"? Which ddl? The `alter` that is running on the _ghost_ table at the very beginning of the migration? 

> means the gh-ost has successful do the job

So, at the very end? I'm really not following you. As I explain, `gh-ost` continues to read the binary logs throughout the operation. There is no occasion where the connection would be closed.

Or do you mean after the cut-over?

Please, elaborate, or else I cannot answer.

**Comment by rj03hou** [comment]
Sorry.
After the gh-ost complete the schema change job, and the program quit. 
But the connection to the slave(which get the binlog) is not close.

**Comment by shlomi-noach** [comment]
@rj03hou you mean MySQL still sees the connection _after gh_ost is terminated_? Wow, this is insane. I mean, TCP is broken.

How long does it take for mysql to notice `gh-ost` is gone?

I can look into closing the connection on the `gh-ost` side, which is of course the nicer thing to do.

**Comment by rj03hou** [comment]
> How long does it take for mysql to notice gh-ost is gone?
After 4 hour, still can see the connection. I don't know gh-ost should execute some command like "stop slave" or just close the connection on the gh-ost side.

Good job, thank you. We prepare to use gh-ost to instead of pt-online-schenma-change.

**Comment by shlomi-noach** [comment]
addressed by https://github.com/github/gh-ost/pull/294

**Comment by shlomi-noach** [comment]
closed by #294

**Comment by rj03hou** [comment]
In the following case, streamer connection is still leak. 

```
create table xu_test( 
id_1 int ,
id_2 int,
PRIMARY KEY (id_1)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter xu_test table DROP PRIMARY KEY ,ADD PRIMARY KEY (id_2)";
```

I think there is a simple solution.
add the following code after Migrate::initiateStreaming
```
	defer func(){
		if err := this.eventsStreamer.Close(); err != nil {
        	log.Errore(err)
    	}
	}
```

and remove the eventsStreamer.Close from finalCleanup.

**Comment by shlomi-noach** [comment]
Is `finalCleanup()` not invoked? Why would the code work via `defer` and not via `finalCleanup()`?

**Comment by rj03hou** [comment]
because finalCleanup just work if there is no err.
if inspectOriginalAndGhostTables return err, finalCleanup don't work.

**Comment by shlomi-noach** [comment]
@rj03hou you're right. Go for it!

**Comment by rj03hou** [comment]
reopen this issue, and pull request to this issue?

**Comment by rj03hou** [comment]
I make the following change

```go
        }
+
+       //make sure the stream connection to be closed.
+       defer func() {
+               if err := this.eventsStreamer.Close(); err != nil {
+                       log.Errore(err)
+               }
+       }()
+
        if err := this.initiateApplier(); err != nil {
                return err
        }
```

and test, the log is like following:

```
2016-12-21 11:19:57 DEBUG ghost table migrated
2016-12-21 11:19:57 INFO Handled changelog state GhostTableMigrated
2016-12-21 11:19:57 DEBUG Potential unique keys in _xu_test_gho: [PRIMARY: [id_2]; has nullable: false]
2016-12-21 11:19:57 INFO StreamEvents encountered unexpected error: connection was bad
2016-12-21 11:19:57 INFO Closed streamer connection. err=<nil>
2016-12-21 11:19:57 FATAL No shared unique key can be found after ALTER! Bailing out
```

But I login the mysql and execute "show processlist", the connection is still in.
"| 68246 | root | :62048 | NULL | Binlog Dump |   32 | Master has sent all binlog to slave; waiting for binlog to be updated | NULL"

**Comment by rj03hou** [comment]
I test a success alter_sql, find the connection leak is not resolve.
I use netstat find ghost was in FIN_WAIT_2 state, this explain ghost close the connection to mysql, but mysql don't close the connection.

so I think we should send COM_QUIT to mysql, before we just close the tcp connection.

**Comment by shlomi-noach** [comment]
@siddontang do you have any thoughts on this?

**Comment by siddontang** [comment]
Hi @shlomi-noach 

Maybe this is the same for https://github.com/siddontang/go-mysql/issues/102, or https://github.com/siddontang/go-mysql/issues/82.

Event the client closes the socket, the MySQL server may still keep this connection. Maybe sending `COM_QUIT` can work, but I haven't tested it. Another way is to send `KILL CONNECTION ID` in another connection to force MySQL close it.

**Comment by siddontang** [comment]
I think this is not a urgent bug, so I don't handle it now. 😭
