### ISSUE TITLE
 if the "host" is lag, then the ghost is hang, and the log is not clear.

### ISSUE THREAD

**Issue by rj03hou** [github/gh-ost#304]
when the host(which the parameter host is set) is  lag, then run the gh-ost, the gh-ost create the change log and ghost table in the master, and the binlog is not execute by the gh-ost.

then the ghost is hang, and the log is

> 2016-11-01 10:03:40 INFO Waiting for tables to be in place

I think we can add a new parameter, when it set, we check the lag before we run, if lag we fail.
or we change the log to "Waiting for tables to be in place, the host is lag.", the log more clear.

**Comment by shlomi-noach** [comment]
PR merged, next release (current is `1.0.28`) will include the change
