### ISSUE TITLE
Best practices to drop (a large) old table after cut-over

### ISSUE THREAD

**Issue by fern4lvarez** [github/gh-ost#307]
Hi gh-ost'ers!

We plan to use gh-ost to perform online migrations on big tables that will allow us to reclaim a big amount of disk space. On our tests, the migration, copy, and cut-over work like a charm. The problem we face is when `DROP`-ing the old table, i.e. `_mytable_del`, which has a size of ~18GB. It totally blocks all queries, causing a downtime on our applications that consume our database.

As we are using 5.6.21 on Amazon RDS, and `innodb_file_per_table=1` set, we understand that this is what is happening (see [1](https://www.percona.com/blog/2011/02/03/performance-problem-with-innodb-and-drop-table/)):

>The problem is basically if you’re running innodb_file_per_table=1 the tablespace is dropped when you’re running DROP TABLE, and Innodb has to go through LRU list and discard the pages which belong to this tablespace. This can take a lot of time with large buffer pool. Worst of all this is done while table_cache lock is being held so no other queries can start.

I guess we are not the only ones facing this challenge, and I'd like to hear how other gh-ost users are doing to `DROP` the old table. We have basically two options: schedule a maintenance window and drop the old the table in the meantime, or DELETEs in small batches first, then TRUNCATE it and finally a DROP TABLE (inspired by [2](http://serverfault.com/questions/558693/how-to-drop-an-8-gb-innodb-table-smoothly-without-global-locks)). The former is not convenient at all, as we want to keep _online_, and the latter sounds reasonable, as long as the DELETEs load is not too high.

Any recommendations on this?

[1] https://www.percona.com/blog/2011/02/03/performance-problem-with-innodb-and-drop-table/
[2] http://serverfault.com/questions/558693/how-to-drop-an-8-gb-innodb-table-smoothly-without-global-locks

**Comment by shlomi-noach** [comment]
> I guess we are not the only ones facing this challenge, and I'd like to hear how other gh-ost users are doing to DROP the old table. We have basically two options: schedule a maintenance window and drop the old the table in the meantime, or DELETEs in small batches first, then TRUNCATE it and finally a DROP TABLE (inspired by 2). The former is not convenient at all, as we want to keep online, and the latter sounds reasonable, as long as the DELETEs load is not too high.

We suffer from the same. We've recently met with Oracle engineers who said this shouldn't be happening, and might relate to our file systems' `unlink` time. Nonetheless dropping tables only works well for us after slowly deleting all table data, then wait a couple days, then directly `drop` (no `truncate`).

There is also the [hard link hack](http://blog.balazspocze.me/2015/01/13/how-to-drop-table-in-a-hacky-way/) which we also find useful, but still nibbling the rows is more trusted.

What we of course don't like about nibbling is that it takes so much time and needs to be controlled so as not to cause lags, and it bloats the binlogs.

**Comment by SuperQ** [comment]
What filesystem are you using on the host?

If deleting rows and then dropping is ok, I'm doubting the `unlink` is the problem.

One of the issues I've been told, and seen, is that even with file per table, there is still a large amount of metadata in ibdata1 that needs cleanup to drop a table.  This seems to be supported by the delete-rows-first performance.

**Comment by shlomi-noach** [comment]
> If deleting rows and then dropping is ok, I'm doubting the unlink is the problem.

We reached the same conclusion. We suspect maybe it has to do with multiple `innodb_buffer_pool_instances` but have not tested. Frankly, we have just one ultimate testing environment, and that's our busiest production master. All other masters or servers do not manifest the problem in the same way. So any experiment on our side is unreliable unless it's on the master. So... not many experiments.

We use `ext4`.

**Comment by xiepaup** [comment]
we got the same 

when droping the old _xxx_del table,which has 16GB , It totally blocks all queries,  and the processlist shows opening tables stats.

As we are using Perconat 5.6.27 on CentOS 6.5, and innodb_file_per_table=1 set,

**Comment by shlomi-noach** [comment]
A quick not that it has been suggested to us by Oracle that the locking in dropping the table may be related to the use of `innodb_adaptive_hash_index`. We were looking to disable it, but noticed performance degragation on our serving replicas when doing so; so we never got to disable it on the master to test.

**Comment by SuperQ** [comment]
We disabled `innodb_adaptive_hash_index` based on the recommendation of Percona.  There was a short period of degradation.  Afterwards performance was better as we had more innodb memory for table pages, and reduced CPU use not being spent on the AHI.

**Comment by shlomi-noach** [comment]
@SuperQ we had adaptive hash index enabled for over two weeks before measuring. We saw higher latencies in table access where AHI was disabled throughout that time. Minutes after re-activating it we saw an immediate decrease in latencies, making the server on-par with its fellow replicas where AHI was always ON.

**Comment by SuperQ** [comment]
Interesting.  I wonder how much the table size/active dataset/memory constraints have to do with the resulting performance change.  The tables we were testing against were already too large to fit in the available ram, I don't have the graphs on-hand anymore, but we did see a small IO reduction afterwards, which is what we were going for.

**Comment by shlomi-noach** [comment]
This latency was seen overall on all tables (anyway all tables we were looking at), some of which are very unlikely to be all in RAM, and all of which cannot be all in RAM.

**Comment by rtreffer** [comment]
I've been using the DELETE followed by DROP method in the past to avoid server stalls (up to 7s). IIRC the stall were mainly dominated by the bufferpool size (smaller servers experienced a proportional smaller stall).

**Comment by OlegSmelov** [comment]
We are also experiencing this with Percona Server 5.6.32.

The only thing that seems to have worked is 1) `delete` all records, 2) wait some time (a day in our case), 3) `drop`.

Has anyone tried upgrading to MySQL 5.7.6 or newer? There have been some performance optimizations for `drop table`. [MySQL 5.7.6 release notes](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-6.html):

> The metadata locking subsystem (see Metadata Locking) has been extended to cover concurrent access to tablespaces.

I tried reproducing this behavior locally with both 5.6.34 and 5.7.17 to see if there was any difference, but couldn't. The lock wasn't being held long enough to check.

**Comment by fern4lvarez** [comment]
After my personal experience, which involves using `gh-ost` with AWS RDS only, I can say that slowly deleting the content of the `_xxx_del` table and waiting few days, so all the references in the InnoDB pool are gone, makes the `DROP` a trivial operation, taking normally around 0.04 sec.

I feel we all are coming to the same conclusion, and this issue can be already closed. @shlomi-noach what do you think?

**Comment by shlomi-noach** [comment]
Agreed.

**Comment by rbroemeling** [comment]
@shlomi-noach It seems like the "best practices" have been settled on in this ticket -- I'm curious whether there is room here for an open-source tool to purge large tables out of MySQL safely? It feels like there _is_, and I'm curious if you either know of one or whether GitHub might have one internally that I could talk you into open-sourcing?

The collaboration of the tool with gh-ost is self-evident, I think. Thanks!  Let me know what you think.

**Comment by ggunson** [comment]
> I'm curious whether there is room here for an open-source tool to purge large tables out of MySQL safely?

@rbroemeling Are you suggesting creating a new tool?

At GitHub our general (automated) process is:

1. Make the table BLACKHOLE on the replicas (a slightly blocking operation, but our read replicas can handle it)
1. Start the "nibble" process on the master (using [pt-archiver](https://www.percona.com/doc/percona-toolkit/LATEST/pt-archiver.html) and with sql_log_bin=0 so that the deletes aren't recorded to the binary log and replicated).
1. Wait several days after the nibble process ends.
1. Drop the table. 

We do it this way so that the slow purging of the table rows doesn't affect replication or use up binary log disk space, the former being especially important because we have so many processes relying on up-to-date replicas (whose status is reported by [freno](https://github.com/github/freno)). 

We've been generally hoping that the buffer pool table drop bug gets resolved in a later version of MySQL and have considered this process good enough. I don't know how well our automated process could be packaged up to work for other systems, though we are happy to share what we do.

**Comment by rbroemeling** [comment]
@ggunson Hi Gillian,

Yeah -- I was more or less wondering how GitHub handles this problem internally (thanks for the explanation of the internal process!) and whether a new tool would make sense. Using `pt-archiver` makes sense, though, and I can see the argument for it being a "good enough" approach that it isn't worth the time to implement a new tool that will effectively replicate the flow (even if the additional tool might be a little more graceful about things).

The use of `BLACKHOLE` on the slave server(s) is interesting and clever -- what happens if the master MySQL server is lost (i.e., crash, power loss, or whatever else) during this operation? Since the slaves are technically out-of-sync with the master while this is happening, I'm curious how GitHub recovers in that case?

**Comment by ggunson** [comment]
>  what happens if the master MySQL server is lost (i.e., crash, power loss, or whatever else) during this operation?

In the event of a master failover (as that would happen if the master died; there's a new GitHub Engineering blog post coming that mentions our failover process and how we minimize data loss) the old master would be pulled out of replication altogether and likely rebuilt from a backup, in which case we don't care about any running pt-archiver jobs on it. We'd now have a promoted replica with a blackhole table for that to-be-purged table. Our automation keeps track of the tables outside of the cluster, and on the next check would see that the table is now empty via whether `select 1 from table limit 1` returns any rows on the master. It would then do the waiting process and eventually drop the table as before (we don't have failovers that often, so we haven't considered checking whether it's a blackhole on the master and can be dropped immediately).

I've left out a bit of the details of our exact process (e.g. the blackholing of the table isn't a straight `alter table tbl engine=blackhole`, there's a create table, swap and drop table with the adaptive_hash_index temporarily turned off, though we still have several seconds of InnoDB blocking even with that). I don't think we've ever written up the whole process in detail.

**Comment by Jericon** [comment]
At blizzard we recently ran into some issues with dropping large tables like this. We reached out to oracle and they were able to reproduce and, surprisingly, found that they did not have a bug to track this. It happens on the current latest build of 5.6, 5.7 and 8.0. 

https://support.oracle.com/epmos/faces/ui/km/BugDisplay.jspx?id=28489686

**Comment by Jericon** [comment]
Here is the public bug report for what I mentioned:
https://bugs.mysql.com/bug.php?id=91977
