### ISSUE TITLE
gh-ost hang with no more information

### ISSUE THREAD

**Issue by rj03hou** [github/gh-ost#311]
gh-ost output is like this:
```
Copy: 101310000/606657995 16.7%; Applied: 474141; Backlog: 1/100; Time: 1h55m0s(total), 1h55m0s(copy); streamer: mysql-bin.004536:911475423; State: migrating; ETA: 9h33m38s
Copy: 101852000/606657995 16.8%; Applied: 475326; Backlog: 0/100; Time: 1h55m30s(total), 1h55m30s(copy); streamer: mysql-bin.004536:1017379184; State: migrating; ETA: 9h32m26s
```

and is hang, with no more information.

**using interactive and strace is like this:**
```
echo status | nc -U xxx.sock
```
there is nothing output

```
[~]# strace -p 12653
Process 12653 attached
futex(0xa164a8, FUTEX_WAIT, 0, NULL
```

change log table is still insert, but the ghost don't have any new data more.

**Comment by shlomi-noach** [comment]
Does this reproduce for you?

**Comment by rj03hou** [comment]
Yes, already have some times; now we open the debug mode, next time it will have more log.
We don't have any clue to this problem.

**Comment by rj03hou** [comment]
We have find the problem, because the  python.subprocess hang after proc.communicate().
This hang the gh-ost.

**Comment by shlomi-noach** [comment]
thank you
