### ISSUE TITLE
Not support for dirty replication

### ISSUE THREAD

**Issue by rj03hou** [github/gh-ost#323]
Find a bug not  support for clean replication:

1. DBA using reset slave rather than reset slave all. The Master_Host and Master_Port exist.
1. DBA not execute reset slave or reset slave all when they promote the slave to master. The Master_Host and Master_Port exist, but the replication is break.

In the above case, we using recursive to execute show slave status from the host to find the master but not check the slave status, may find the wrong master.

So we can check the Master_Log_File and Slave_IO_Running Slave_SQL_Running.

```
if show slave status output is not empty:
    if Master_Log_File is empty:
        return
    else    Slave_IO_Running or Slave_SQL_Running not yes:
       exit
    else
       this may be the master
```

**Comment by shlomi-noach** [comment]
Thank you,

`Slave_IO_Running` and `Slave_SQL_Running` being `No` is certainly not a reliable indicator that a server is a master.

I'm OK to consider an empty `Master_Log_File` as an indicator that a server is a master.

**Comment by rj03hou** [comment]
In the second case:
DBA not execute reset slave or reset slave all when they promote the slave to master, just execute stop slave. The Master_Host and Master_Port exist, but the replication is break.

In this case, we can find the stale master, and try to write to id.

**Comment by shlomi-noach** [comment]
Also in that same 2nd case, some intermediate master may just have replication broken; it's unsafe to assume that it is the master.

**Comment by rj03hou** [comment]
In that same 2nd case, if the Slave_IO_Running and Slave_SQL_Running being No, we can stop and remind the user to check.
otherwise will find the wrong master.

**Comment by shlomi-noach** [comment]
> we can stop and remind the user to check.

yes, that's an excellent sanity check.

**Comment by rj03hou** [comment]
@shlomi-noach I make a pull request to solve this problem,  can you review the code.

**Comment by shlomi-noach** [comment]
closed by https://github.com/github/gh-ost/issues/324
