### ISSUE TITLE
Allow for a `--ask-pass` parameter?

### ISSUE THREAD

**Issue by austinhalpin** [github/gh-ost#328]
`pt-online-schema-change` has a parameter `--ask-pass` which will prompt for the DB password at runtime. 

We run migrations from a single ec2 host & the thoughts of leaving our DB password in a plain text file (or passing it as a parameter to a command in plaintext) genuinely terrifies me. 

Is this something you would be willing to add?

**Comment by shlomi-noach** [comment]
Sure, we can certainly support this.

However you might also be interested in the following: `gh-ost` recognizes environment variables, such that you may create a config file:

```shell
$ cat /etc/mysql/gh-ost.cnf
[client]
user=${GHOST_USER}
password=${GHOST_PASSWORD}
```

Run `gh-ost` via:

```
gh-ost --conf=/etc/mysql/gh-ost.cnf ...
```

and then just make sure the environment variable is set.

e.g. you can

```
GHOST_USER=usr GHOST_PASSWORD=12345 gh-ost --conf=/etc/mysql/gh-ost.cnf ...
```

**Comment by austinhalpin** [comment]
Sure, that could work. But someone is still going to need to run a command passing the password in plaintext. That's the part that gives me the heebie jeebies 😅 

Thanks for the quick reply btw!

**Comment by shlomi-noach** [comment]
`shell` has yet magic for you:

```shell
$ read -s GHOST_PASSWORD
<type in your password, it doesn't echo back>
$ echo $GHOST_PASSWORD
12345
```

**Comment by shlomi-noach** [comment]
https://github.com/github/gh-ost/pull/334 adds `--ask-pass` flag.

**Comment by shlomi-noach** [comment]
fixed by https://github.com/github/gh-ost/issues/334, released in https://github.com/github/gh-ost/releases/tag/v1.0.32
