### ISSUE TITLE
Feature Request: different user/password for master vs replica

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#338]
Not all replication topologies replicate the mysql system tables, so there are scenarios where there are different users and passwords set up on masters vs replicas. gh-ost assumes that the same user can be used to connect to both the master and the replicas (used for binlog parsing or for replication lag checks). 

I'd like to request a feature where it's possible to specify different usernames and passwords on a per-host basis, or at least between master and replica(s). 

Percona Toolkit, for example, requires the DSN format if the user/passwords need to be different depending on the host queried. https://www.percona.com/doc/percona-toolkit/2.2/dsn_data_source_name_specifications.html

/cc https://github.com/github/gh-ost/issues/336#issuecomment-266588768

**Comment by shlomi-noach** [comment]
closed by https://github.com/github/gh-ost/issues/339
