### ISSUE TITLE
Updating failed when gh-ost reducing varchar column length

### ISSUE THREAD

**Issue by kerrigell** [github/gh-ost#344]
Hi,
   There has a error ,looks like a bug.
   A column has be definded 'varchar(130)', and filled with 120 length data.
   Gh-ost is running with --alter =`modify v2 varchar(100) not null default ''`, then change another column value, a error appear in gh-ost logs, and the update statment will be looped to execute,and it will fail every time.
   The error not appeared , if not to update other column value during gh-ost running.

1. gh-ost error logs
<pre>
2016-12-22 15:14:22 ERROR Error 1406: Data too long for column 'v2' at row 1; query=
             update / gh-ost oddl._testfull_gho /
                     oddl._testfull_gho
                set
                    id=?, v1=?, v2=?, t1=?, v3=?, v4=?
                where
                     ((id = ?))
         ; args=[6213262 92c14292c14292c14292c142 270cc78ece5a270cc78ece5a270cc78ece5a270cc78ece5a270cc78ece5a270cc78ece5a270cc78ece5a270cc78ece5a270cc78ece5a270cc78ece5a 5050   6213262]
</pre>

2. update seatment
<pre>
 update testfull inner join (select id from _testfull_gho order by id desc limit 10) as b on testfull.id=b.id set testfull.t1=5050;
</pre>

3. Table define
<pre>
create table testfull (
id bigint(10) not null auto_increment,
v1 char(32) not null default '',
v2 varchar(130) not null default '',
t1 int(4) not null default '0',
primary key(id),
key idx_v1_t1(v1,t1),
key idx_v1_v2(v1,v2)
) engine=innodb default charset=utf8;
</pre>

 Thank you!

**Comment by tomkrouper** [comment]
Can you tell me the `sql_mode`  for your host? I think this is a function of MySQL to prevent this.

```
mysql> create table t1 (id int not null auto_increment primary key, data varchar(10));
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t1 (data) values ('1234567890');
Query OK, 1 row affected (0.01 sec)

mysql> insert into t1 (data) values ('12345678901');
ERROR 1406 (22001): Data too long for column 'data' at row 1
mysql> show session variables like 'sql_mode';
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                                |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

**Comment by kerrigell** [comment]
@tomkrouper 
Thank you for your reply.
My sql_mode is NO_ENGINE_SUBSTITUTION. Excuting your statments, mysql repeat a warning.
I think wether  the session variable of  gh-ost binlog redo thread is different.

<pre>
mysql> create table t1 (id int not null auto_increment primary key, data varchar(10));
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 (data) values ('1234567890');
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 (data) values ('12345678901');
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------+
| Level   | Code | Message                                   |
+---------+------+-------------------------------------------+
| Warning | 1265 | Data truncated for column 'data' at row 1 |
+---------+------+-------------------------------------------+
1 row in set (0.00 sec)

mysql> show session variables like 'sql_mode';
+---------------+------------------------+
| Variable_name | Value                  |
+---------------+------------------------+
| sql_mode      | NO_ENGINE_SUBSTITUTION |
+---------------+------------------------+
1 row in set (0.00 sec)

</pre>

**Comment by shlomi-noach** [comment]
`gh-ost` explicitly sets session `sql_mode` to `STRICT_ALL_TABLES` is order to protect your data: https://github.com/github/gh-ost/blob/d13049b41e9da9798b83958b51f8ecf6620bb100/go/logic/applier.go#L449-L467

Now, you say:

> A column has be definded 'varchar(130)', and filled with 120 length data.
> Gh-ost is running with --alter =modify v2 varchar(100) not null default ''

In the above you are asking `gh-ost` to corrupt your data, and it refuses. This behavior is as expected and desired.

If you insist on truncating your texts, then your best option would be to first truncate them yourself (do an iterative `update my_table set vs=left(v2,100)`) and then run the migration again.

Regardless of `gh-ost`, I find data truncation appalling, and one of MySQL's biggest design mistakes. I would strongly suggest to use `STRICT_ALL_TABLES` where possible.

**Comment by shlomi-noach** [comment]
I'm closing this having received no comments, and seeing that behavior is as expected.
