### ISSUE TITLE
Make possibility to configure serverId

### ISSUE THREAD

**Issue by cypiszzz** [github/gh-ost#350]
In a case where I want to run several gh-ost processes in parallel it seems to be not possible due to all of the processes show up with the same serverId: 99999 (it's const in the code).

Possibility to pass serverId as an option with command line (with default set to 99999) would solve the problem.

Example PR: #349

**Comment by shlomi-noach** [comment]
Thank you. This should ideally be submitted on https://github.com/siddontang/go-mysql, and of course we can diverge from that library a bit.

Having said that, we've been running multiple concurrent migrations without problem. What is the error you saw?

**Comment by shlomi-noach** [comment]
Where is my mind... This of course has nothing to do with the `go-mysql` library.
Further comments on the PR review

**Comment by shlomi-noach** [comment]
closed by https://github.com/github/gh-ost/pull/349
