### ISSUE TITLE
Identical PK or unique key between old and new tables

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#357]
This is coming out of the issue https://github.com/github/gh-ost/issues/353 but unrelated to the bug it reported. 

In that issue, there's an alter statement within the gh-ost command:

```
--alter="ADD UNIQUE INDEX (id), 
DROP COLUMN column5, DROP INDEX column1_column2, 
DROP PRIMARY KEY, ADD PRIMARY KEY(column1,column2), 
MODIFY column2 SMALLINT UNSIGNED NOT NULL, MODIFY column3 INT NOT NULL"
```

In that case, the primary key becomes a unique key and a non-unique index becomes the new primary key. All columns involved in these indexes are not-null. 

The docs, however, state (https://github.com/github/gh-ost/blob/master/doc/requirements-and-limitations.md):

> The two before & after tables must share some UNIQUE KEY. Such key would be used by gh-ost to iterate the table.

The issue is, is this particular alter statement still okay, given there's technically no shared unique key between the two tables (since it's "renamed" from PK to unique)?

If this is determined to be okay, it might be worth clarifying the docs, because they give an example of a unique key becoming a PK (requiring two migrations) but not the other direction:

> As an example, if your table has a single UNIQUE KEY and no PRIMARY KEY, and you wish to replace it with a PRIMARY KEY, you will need two migrations: one to add the PRIMARY KEY (this migration will use the existing UNIQUE KEY), another to drop the now redundant UNIQUE KEY (this migration will use the PRIMARY KEY).

**Comment by shlomi-noach** [comment]
Fixed by #358
