### ISSUE TITLE
Throttler sticks when changing throttle-control-replicas during lag

### ISSUE THREAD

**Issue by jonahberquist** [github/gh-ost#361]
Today we changed `throttle-control-replicas` during a migration to remove a host from service.

This worked fine. Then I commanded the socket `throttle-control-replicas` with no arguments, because I couldn't remember if that would return the current list of throttle control replicas. (For the record, it does not. It clears the list, unless you hit this bug.)

After doing that, I issued a `status`, and everything seemed fine. The migration was throttled, seeing one replica had `0.700882s` of lag, which I interpreted as perfectly normal behavior, and also figured that with no arguments `throttle-control-replicas` just didn't do anything.

The next several migration status outputs in chat displayed exactly the same throttled state. The same replica, the same lag, no progress was being made. Then we noticed. We reset throttle-control-replicas to its previous list (minus the one we removed) and everything proceeded normally.

I was able to reproduce this behavior by manually stopping replication on a control replica and then issuing a `throttle-control-replicas` command. The migration gets stuck in a throttled state. It does not reproduce when there is not lag.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/github/gh-ost/pull/364. Thank you @jonahberquist and @tomkrouper for analyzing the problem and actively reproducing it (as seen in internal logs)!
