### ISSUE TITLE
Unable to retrieve current throttle-control-replicas list

### ISSUE THREAD

**Issue by jonahberquist** [github/gh-ost#362]
Currently this is dynamically settable through commands to the socket, but unlike other such settings, it does not show up in `status` output.

This could either be added to `status` output, or because it is often a large list, output via a new command, like `list-throttle-control-replicas`.

**Comment by shlomi-noach** [comment]
https://github.com/github/gh-ost/pull/363 addresses this Issue.

**Comment by shlomi-noach** [comment]
closed by #363
