### ISSUE TITLE
problems with Tungsten scenarios

### ISSUE THREAD

**Issue by groenewold-pythian** [github/gh-ost#371]
When running gh-ost against a replica in a Tungsten-based setup as follows:

```
./gh-ost \
--assume-master-host=192.168.56.145 \
--tungsten \
--max-load=Threads_running=25 \
--critical-load=Threads_running=1000 \
--chunk-size=1000 \
--throttle-control-replicas="192.168.56.144" \
--max-lag-millis=1500 \
--user="ghost" \
--password="ghost" \
--host=192.168.56.144 \
--database="mysqlslap" \
--table="test" \
--verbose \
--alter="add index(created)" \
--switch-to-rbr \
--cut-over=default \
--default-retries=120 \
--panic-flag-file=/tmp/ghost.panic.flag \
--postpone-cut-over-flag-file=/tmp/ghost.postpone.flag \
--initially-drop-ghost-table \
--initially-drop-old-table \
--execute
```

One needs to make sure Tungsten is configured with `--log-slave-updates`, otherwise changes are not logged into Tungsten slaves binlogs. 
This can cause silent data corruption if not considered, as the database `--log-slave-updates `setting is irrelevant here and that is what gh-ost checks as a safety precaution.

Another problem is `--switch-to-rbr` is ineffective in a Tungsten setup, as gh-ost can't stop and start replication to make the change effective, so RBR needs to be set up beforehand.

I  propose some documentation updates to address these

**Comment by shlomi-noach** [comment]
closed by #372
