### ISSUE TITLE
Error 1146 during "droppping" support tables 

### ISSUE THREAD

**Issue by plapythian** [github/gh-ost#377]
Error 1146 found in the final stages of a long running gt-ost:

```
2017-02-22 05:24:29 INFO Droppping table `client_db`.`_table_modified_del`
2017-02-22 05:24:31 ERROR Error 1146: Table 'client_db._table_modified_gho' doesn't exist; query=
			replace /* gh-ost `client_db`.`_table_modified_gho` */ into
				`client_db`.`_table_modified_gho`
					(`table_modified_id`, `date`, `field1_id`, `field2_id`, `field3_id`, `field_date`, `field5`)
				values
					(?, ?, ?, ?, ?, ?, ?)
		; args=[2924386954 2017-02-22 13:24:29 2924386184 2753990708 2753990708 <nil> 1]
```

We used Version 1.0.21. This was supposed to be fixed in 1.0.14:
https://github.com/github/gh-ost/issues/180
https://github.com/github/gh-ost/pull/192

These are the parameters/command line:
```
gh-ost \
--assume-master-host=server-db5.client-domain.com \
--tungsten \
--max-load=Threads_running=25 \
--critical-load=Threads_running=1000 \
--chunk-size=250 \
--max-lag-millis=20000 \
--user=<user> \
--password=<password> \
--host=server-db6.client-domain.com \
--database="client_db" \
--table="table_modified" \
--alter="MODIFY COLUMN date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP" \
--cut-over=default \
--default-retries=120 \
--panic-flag-file=/tmp/ghost.panic.flag \
--postpone-cut-over-flag-file=/tmp/ghost.postpone.flag \
--initially-drop-ghost-table \
--initially-drop-old-table \
--verbose \
--exact-rowcount \
--concurrent-rowcount \
--ok-to-drop-table \
--execute
```

Extended log attached (The names have been changed to protect the innocent.)
[gh-ost-issue.txt](https://github.com/github/gh-ost/files/793906/gh-ost-issue.txt)

**Comment by shlomi-noach** [comment]
@plapythian thank you -- just to verify, can you please test with the latest version, https://github.com/github/gh-ost/releases/tag/v1.0.34 ?

This assumes you're able to reproduce the problem. I will meanwhile examine your logs.

**Comment by plapythian** [comment]
@shlomi-noach I'll try, but the change took a few days to complete and not sure I'll be allowed to test it. We've been running gh-ost for several changes and AFAIK this is the first time this happened.

**Comment by shlomi-noach** [comment]
@plapythian very good, thanks!

**Comment by shlomi-noach** [comment]
yes, it seems like there's still a race condition.

To clarify that this does not pose a data integrity problem. The migration is cut-over when all relevant data is in place. These superfluous queries relate to data applied _after_ cut-over, thus obviously already in the table.

**Comment by shlomi-noach** [comment]
addressed by https://github.com/github/gh-ost/pull/379

**Comment by shlomi-noach** [comment]
#379 has been merged. It mitigates but does not fully solve the problem -- I believe there will _always_ be a race condition on this. I think the solution in #379 is good enough.

Just to clarify that these errors do not actually imply a problem with the migration -- the migration still runs good and well. They're wrong to be generated and that's the race condition problem.

FWIW I've never seen them, but then again I'm never watching the migration output anymore, it's all abstracted away.
