### ISSUE TITLE
How to config  dml-batch-size  on Running gh-ost

### ISSUE THREAD

**Issue by linuxgood1230** [github/gh-ost#395]
How to config  dml-batch-size  on Running gh-ost
We have a largs table ,and table update ops about 2-5K TPS
gh-ost so slow
>Copy: 0/636031839 0.0%; Applied: 992013; Backlog: 100/100; Time: 43m24s(total), 43m16s(copy); streamer: yxmysql-bin.004861:450816029; State: migrating; ETA: N/A

**
How to optimize this ?
Thanks

**Comment by shlomi-noach** [comment]
The largest supported `dml-batch-size` is `100`, try that. The default is `10`.
I'm curious to see more of the log: 

- Is `gh-ost` throttling a lot? 
- If so, on what condition?
- How is replication doing? What's the common lag? What's the lag threshold you used?

I can't tell from this single line output.

What's the disk I/O utilization on that poor master? If you're already close to the limit, you may just not have the capacity to run a migration.

Consider alleviating disk I/O at the expense of durability, and set `innodb_flush_logs_at_trx_commit=2, sync_binlog=0` in case they're set otherwise, for the duration of the migration.

**Comment by linuxgood1230** [comment]
>Copy: 0/636180037 0.0%; Applied: 2173293; Backlog: 100/100; Time: 1h35m30s(total), 1h35m23s(copy); streamer: yxmysql-bin.004862:715606924; State: migrating; ETA: N/A
--------
>Copy: 0/636181259 0.0%; Applied: 2182054; Backlog: 100/100; Time: 1h36m0s(total), 1h35m53s(copy); streamer: yxmysql-bin.004862:723121331; State: migrating; ETA: N/A
--------
>Copy: 0/636182536 0.0%; Applied: 2191325; Backlog: 100/100; Time: 1h36m30s(total), 1h36m23s(copy); streamer: yxmysql-bin.004862:731086538; State: migrating; ETA: N/A
---------
>Copy: 0/636183975 0.0%; Applied: 2202136; Backlog: 100/100; Time: 1h37m0s(total), 1h36m53s(copy); streamer: yxmysql-bin.004862:740450693; State: migrating; ETA: N/A
---------
>Copy: 0/636185512 0.0%; Applied: 2213680; Backlog: 100/100; Time: 1h37m30s(total), 1h37m23s(copy); streamer: yxmysql-bin.004862:750447226; State: migrating; ETA: N/A
---------
>Copy: 0/636186970 0.0%; Applied: 2225217; Backlog: 100/100; Time: 1h38m0s(total), 1h37m53s(copy); streamer: yxmysql-bin.004862:760348015; State: migrating; ETA: N/A
---------
>Copy: 0/636188384 0.0%; Applied: 2236614; Backlog: 100/100; Time: 1h38m30s(total), 1h38m23s(copy); streamer: yxmysql-bin.004862:770135751; State: migrating; ETA: N/A
---------
>Copy: 0/636189727 0.0%; Applied: 2247552; Backlog: 100/100; Time: 1h39m0s(total), 1h38m53s(copy); streamer: yxmysql-bin.004862:779506664; State: migrating; ETA: N/A
---------
[MySQL] 2017/04/05 22:14:14 statement.go:27: Invalid Connection
>Copy: 0/636191271 0.0%; Applied: 2259521; Backlog: 100/100; Time: 1h39m30s(total), 1h39m23s(copy); streamer: yxmysql-bin.004862:789441118; State: migrating; ETA: N/A
-------
> Migrating `gifshow`.`gift_sent_record_index`; Ghost table is `gifshow`.`_gift_sent_record_index_gho`
> Migrating d12.zw:3334; inspecting d21.zw:3334; executing on ai-vm20.zw
> Migration started at Wed Apr 05 20:34:52 +0800 2017
> chunk-size: 10000; max-lag-millis: 1500ms; max-load: Threads_running=25; critical-load: Threads_running=100; nice-ratio: 0.000000
> throttle-additional-flag-file: /tmp/gh-ost.throttle
> postpone-cut-over-flag-file: /tmp/ghost.postpone.flag
> panic-flag-file: /tmp/ghost.panic.flag
> Serving on unix socket: /tmp/gh-ost.gifshow.gift_sent_record_index.sock
------
Copy: 0/636192777 0.0%; Applied: 2271648; Backlog: 100/100; Time: 1h40m0s(total), 1h39m53s(copy); streamer: yxmysql-bin.004862:799532753; State: migrating; ETA: N/A
Copy: 0/636194347 0.0%; Applied: 2283428; Backlog: 100/100; Time: 1h40m30s(total), 1h40m23s(copy); streamer: yxmysql-bin.004862:809426814; State: migrating; ETA: N/A
Copy: 0/636195612 0.0%; Applied: 2293548; Backlog: 100/100; Time: 1h41m0s(total), 1h40m53s(copy); streamer: yxmysql-bin.004862:818179048; State: migrating; ETA: N/A

**Comment by shlomi-noach** [comment]
Pro tip: use three backticks "```" to begin and end a multiline block. Like this:

```
one line
two lines
three lines
```

**Comment by shlomi-noach** [comment]
Any answers to my questions above?

**Comment by shlomi-noach** [comment]
I'm curious. The issue has just been closed. What are the conclusions?
