### ISSUE TITLE
`StopSlaveIOThread` causing issues on RDS with `--test-on-replica`

### ISSUE THREAD

**Issue by jacobbednarz** [github/gh-ost#396]
I'm running some noop migrations on a RDS aurora replica (true replication, not aurora) however I'm hitting the following errors during the `--test-on-replica` cut over phase.

**Command**

```
$ gh-ost \
--user="master_user" \
--password="master_password" \
--port=3306 \
--host="db.host" \
--database="db" \
--table="tableA" \
--alter="engine=innodb" \
--assume-rbr \
--hooks-path="hooks" \
--panic-flag-file=/tmp/ghost.panic.flag \
--postpone-cut-over-flag-file=/tmp/ghost.postpone.flag \
--test-on-replica \
--execute
```

**Output**

```
2017-04-06 08:56:58 DEBUG Iteration complete: no further range to iterate
2017-04-06 08:56:58 DEBUG Getting nothing in the write queue. Sleeping...
Copy: 33/33 100.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: mysql-bin-changelog.018585:110393970; State: migrating; ETA: due
2017-04-06 08:56:58 DEBUG checking for cut-over postpone
2017-04-06 08:56:59 DEBUG Getting nothing in the write queue. Sleeping...
Copy: 33/33 100.0%; Applied: 0; Backlog: 0/100; Time: 1s(total), 0s(copy); streamer: mysql-bin-changelog.018585:110544467; State: postponing cut-over; ETA: due
2017-04-06 08:57:00 DEBUG Getting nothing in the write queue. Sleeping...
Copy: 33/33 100.0%; Applied: 0; Backlog: 0/100; Time: 2s(total), 0s(copy); streamer: mysql-bin-changelog.018585:110607732; State: postponing cut-over; ETA: due
2017-04-06 08:57:01 DEBUG Getting nothing in the write queue. Sleeping...
Copy: 33/33 100.0%; Applied: 0; Backlog: 0/100; Time: 13s(total), 0s(copy); streamer: mysql-bin-changelog.018585:111214012; State: postponing cut-over; ETA: due
Copy: 33/33 100.0%; Applied: 0; Backlog: 0/100; Time: 14s(total), 0s(copy); streamer: mysql-bin-changelog.018585:111224644; State: postponing cut-over; ETA: due
2017-04-06 08:57:12 DEBUG Getting nothing in the write queue. Sleeping...
2017-04-06 08:57:12 DEBUG checking for cut-over postpone: complete
2017-04-06 08:57:12 INFO executing gh-ost-on-stop-replication hook: hooks/gh-ost-on-stop-replication-call-rds
Copy: 33/33 100.0%; Applied: 0; Backlog: 0/100; Time: 15s(total), 0s(copy); streamer: mysql-bin-changelog.018585:111248433; State: migrating; ETA: due
2017-04-06 08:57:13 DEBUG Getting nothing in the write queue. Sleeping...
+ statement='call mysql.rds_stop_replication;'
+ echo '[hook] 2017-04-06 08:57:13 issuing statement to stop replication: call mysql.rds_stop_replication;'
[hook] 2017-04-06 08:57:13 issuing statement to stop replication: call mysql.rds_stop_replication;
+ exec mysql -h db.host -u master_user -predacted -e 'call mysql.rds_stop_replication;'
Warning: Using a password on the command line interface can be insecure.
Message
Slave is down or disabled

2017-04-06 08:57:13 DEBUG testing on replica. Stopping replication IO thread
2017-04-06 08:57:13 INFO Stopping replication IO thread
2017-04-06 08:57:13 ERROR Error 1045: Access denied for user 'master_user'@'%!'(MISSING) (using password: YES)
2017-04-06 08:57:13 ERROR replication not running; Slave_IO_Running=No, Slave_SQL_Running=No
```

The "Slave is down or disabled" looks 👌  since that is what happens when replication is stopped in RDS.

Looking at the [`StopSlaveIOThread`](https://github.com/github/gh-ost/blob/f3fb0ea24a5db852ea0496b3bb00cbf747cb3af0/go/logic/applier.go#L594-L602) it wants to issue `stop /* gh-ost */ slave io_thread` which I believe requires the same privileges as STOP REPLICATION and not available in RDS.

**Versions information**

- `gh-ost`: 1.0.35
- RDS: aurora 5.6

I'm digging into the AWS documentation at the moment to see if there is a comparable RDS call for this. My question is how do we want to handle this _if_ there is a call available? Another hook?

**Comment by jacobbednarz** [comment]
I also tried to label the issue under RDS - aurora but I don't seem to have the magic to do so.

**Comment by jacobbednarz** [comment]
List of all available routines for posterity 

```
mysql> select SPECIFIC_NAME from information_schema.routines;
+-----------------------------------+
| SPECIFIC_NAME                     |
+-----------------------------------+
| lambda                            |
| rds_collect_global_status_history |
| rds_disable_gsh_collector         |
| rds_disable_gsh_rotation          |
| rds_enable_gsh_collector          |
| rds_enable_gsh_rotation           |
| rds_external_master               |
| rds_kill                          |
| rds_kill_query                    |
| rds_next_master_log               |
| rds_reset_external_master         |
| rds_rotate_general_log            |
| rds_rotate_global_status_history  |
| rds_rotate_slow_log               |
| rds_set_configuration             |
| rds_set_external_master           |
| rds_set_gsh_collector             |
| rds_set_gsh_rotation              |
| rds_show_configuration            |
| rds_skip_repl_error               |
| rds_start_replication             |
| rds_stop_replication              |
+-----------------------------------+
``

**Comment by jacobbednarz** [comment]
I've heard back from AWS regarding this and as suspected this isn't supported due to it being a managed service (similar to the SUPER privileges). Their argument here is that `rds_{start,stop}_replication` should be the only entrypoint to interact with the threads because stopping slave threads individually could lead to data inconsistency which is something they don't want their customers accidentally falling into.

I'm going to push this one through to our AWS TAM and see if we can tee up some time with an RDS engineer to see whether we could get this requested as it seems like a sane request providing the risks are understood.

**Comment by shlomi-noach** [comment]
@jacobbednarz if no solution is available, I'll issue a normal `start slave` in the case of RDS(?).

**Comment by jacobbednarz** [comment]
I'd like to have as few provider (in this case AWS RDS) specific code paths as possible to limit the testing and maintenance burden on everyone. 

Would you be open to considering a full replication stop for all providers? I understand stopping them independently allows the slave to keep receiving events and subsequently have less to receive when it does start replicating again however I just want to be sure I'm not missing anything else here too that might have been a driver for this behaviour.

**Comment by shlomi-noach** [comment]
> Would you be open to considering a full replication stop for all providers?

Let me look into that. FYI I'm out for the next few days so this will be stalled a bit.

**Comment by shlomi-noach** [comment]
I believe I'd rather have a `--rds` flag, similar to `--tungsten`. 

There is a struggle between having a single flow of code that applies to everything, and doing the right thing for particular setups.

For disclosure, I still haven't looked deeply into the particulars of `stop slave` in the above. However already I prefer `--rds` over `--test-on-replica-skip-replica-stop`.

**Comment by jacobbednarz** [comment]
> I believe I'd rather have a `--rds` flag, similar to `--tungsten`.

Just to clarify here, RDS using MySQL is 👌 , it's only RDS using Aurora that is the issue so the flag would probably be more suited as `--aurora` (but that's splitting hairs here). I agree it's always about finding that healthy balance however I feel we should be able to roll this up into a non-aurora specific flag for those who might not be running on aurora yet don't have this functionality available to them.

> However already I prefer `--rds` over `--test-on-replica-skip-replica-stop`.

Oh! I didn't even see [`--test-on-replica-skip-replica-stop`](https://github.com/github/gh-ost/blob/master/go/cmd/gh-ost/main.go#L74) was a thing. :man_facepalming: If I'm reading [migrator.go#L458-L474](https://github.com/github/gh-ost/blob/master/go/logic/migrator.go#L458-L474) correctly, I should just be able to use `--test-on-replica-skip-replica-stop` and my usual replication-stop hook to resolve this. Does this sound right to you or am I barking up the wrong tree?

**Comment by shlomi-noach** [comment]
Give it a shot! I do believe this only applies to testing-on-replica though. I'll look further into.

**Comment by jacobbednarz** [comment]
This seems to have worked as suspected 🎉  I'll open a PR for discussion about adding this to the RDS docs.

For my use case, restricting this to `--test-on-replica` is fine (I don't think I'd want to use this anywhere else).
