### ISSUE TITLE
Provide a checksum on the release

### ISSUE THREAD

**Issue by eredi93** [github/gh-ost#398]
would be nice to have a checksum for every release that allows me to check that the binary is valid

**Comment by shlomi-noach** [comment]
Good idea. I will at first provide such checksums manually, but let me see how this can be automated.
I'm leaving this Issue open. Please help me out by pinging on this issue in case I forget to add a checksum on the next release!

**Comment by MrMauricioLeite** [comment]
Ping! =)

**Comment by shlomi-noach** [comment]
I remember 😆

**Comment by shlomi-noach** [comment]
checksum included in https://github.com/github/gh-ost/releases/tag/v1.0.40

**Comment by arthurnn** [comment]
SHA1 and MD5 are not that hard to brute force these days.
Rails uses sha256 for release, might be a better option here.

**Comment by shlomi-noach** [comment]
Checksums are, I believe, merely to confirm the download is sound, and not to counter an evil binary. After all, he binaries are downloaded directly from github, not from some unknown 3rd party distributor. 

I do not mind at all to provide any other checksum (preferably one that is available via unic command line)
