### ISSUE TITLE
gh-ost temp table

### ISSUE THREAD

**Issue by sumonsun** [github/gh-ost#399]
Hi  

Can we add one parameter to control the three ghost table name ,we want to control the table name

**Comment by shlomi-noach** [comment]
Hi,

This is certainly possible, however it would introduce three new command line flags. In another project I'm maintaining I head the number of configuration options was intimidating to people. So I wish to be careful adding new flags.

Can you please illustrate why you need this feature and how it would help you?

**Comment by sumonsun** [comment]
We have a plan to build mutil data center, we use binlog stream to process data replicate ,not original replication m-s.For DDL change ,we will push to mutil data center executer, so we want to filter the binlog that gh-ost produce, filter rule is table name

**Comment by shlomi-noach** [comment]
> so we want to filter the binlog that gh-ost produce, filter rule is table name

So you probably want the name to always be the same? So that you can hard code it? What will you do if you want to run two concurrent migrations?

**Comment by sumonsun** [comment]
we have two data center for disaster backup ,we hope table structure are same .any way,we hope we can filter gh_xx_del table,yes ,have a special name

**Comment by sumonsun** [comment]
ok, we will try to modify source code of gh-ost ,and build again

**Comment by shlomi-noach** [comment]
Can you do with wildcard table names, `_*_del`, `_*_gho`, `_*_ghc`?

**Comment by sumonsun** [comment]
Bad news, I can't ,many product table name like _*_del

**Comment by shlomi-noach** [comment]
OK, I'm open to adding a single command line flag, such as `--force-table-names=<chosenname>`. For example:

`gh-ost --force-table-names=migration_tbl`, which will result with 
- `_migration_tbl_ghc`
- `_migration_tbl_gho`
- `_migration_tbl_del`

Would that solve your problem?

**Comment by sumonsun** [comment]
yeap,thanks so much~
