### ISSUE TITLE
Add `ghost-on-test-on-replica-complete` hook

### ISSUE THREAD

**Issue by jacobbednarz** [github/gh-ost#406]
As I've been setting up continuously running migrations, I've managed to accumulate a few scripts that I have been running following  the completion of a `--test-on-replica` run that I think are worth automating. Here are some of the actions I've been taking:

- Run `pt-table-checksum` against the two tables, post the row and diff results to our metrics collector
- Run MySQL checksums against the two tables, post the results checksum results to our metrics collector
- Update the originating pull request with the results (tables, checksum output, run time)
- Snapshotting replica lag during the migration from our metrics collector
- Post results to our chat to inform everyone that everything is 👌  and isn't on 🔥 

Being the fan of automation that I am, I checked the [hook definitions](https://github.com/github/gh-ost/blob/master/go/logic/hooks.go#L20-L34) however I couldn't find anything that was appropriate for this use case. The [gh-ost-on-before-cut-over](https://github.com/github/gh-ost/blob/master/go/logic/hooks.go#L27) is close however I'm only interested in doing this for test on replica runs at the moment - not all of them.

Is this something you'd be looking to add to `gh-ost` hooks? I'm happy to open a PR with the changes but just wanted to check and make sure I wasn't missing anything obvious before spending time on it.

**Comment by jacobbednarz** [comment]
I had some time free today, so instead I put up a PR putting this idea into code at #407.

**Comment by shlomi-noach** [comment]
Thank you!
I'm out for https://www.percona.com/live/17/ this week, so reviewing will be delayed.

**Comment by jacobbednarz** [comment]
Very jealous! Have fun!
