### ISSUE TITLE
Easier development setup

### ISSUE THREAD

**Issue by jessbreckenridge** [github/gh-ost#412]
## Overview

When cloning the repo for the first time, I attempted to bootstrap and run tests. 

Errors were encountered:

```# _/Users/jessbreckenridge/github/gh-ost/go/base
./context.go:654: undefined: gcfg.RelaxedParserMode
./context.go:655: undefined: scanner.RelaxedScannerMode
FAIL	_/Users/jessbreckenridge/github/gh-ost/go/base [build failed]
../../../../go/src/github.com/outbrain/golib/sqlutils/sqlutils.go:24:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/github.com/go-sql-driver/mysql (from $GOROOT)
	/Users/jessbreckenridge/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
encoding.go:9:2: cannot find package "golang.org/x/text/encoding" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/golang.org/x/text/encoding (from $GOROOT)
	/Users/jessbreckenridge/go/src/golang.org/x/text/encoding (from $GOPATH)
encoding.go:10:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/golang.org/x/text/encoding/charmap (from $GOROOT)
	/Users/jessbreckenridge/go/src/golang.org/x/text/encoding/charmap (from $GOPATH)

```

After debugging for a while, there were multiple barriers to getting the environment up and running. 

I would like to simplify the process of developing in `gh-ost` to downloading, bootstrapping, coding and testing. 

Hopefully I am not barking up the wrong tree here and missing something simple. Please let me know. 

I have branch with some changes in it, but I am holding off on submitting the PR until we have a discussion in the issue.

**Comment by shlomi-noach** [comment]
@jessbreckenridge this is very strange, since `gh-ost` is fully self contained, along with all dependencies, and the CI tests ensure that.

My only thought is you might be using golang <= `1.5`? If so, please upgrade to latest (or at least `1.7`). 

If that is not the case, please output the exact command you were using for running tests, and we'll take it from there.

**Comment by shlomi-noach** [comment]
BTW the way to run the tests CI runs, is to invoke `script/build`.

**Comment by jessbreckenridge** [comment]
@shlomi-noach I think I have it working now. Firing off `ci-build` builds and tests properly.

Could I put together a documentation PR for people getting started with gh-ost? Just the basics, running `ci-build`, and how the build system works?

**Comment by shlomi-noach** [comment]
> I think I have it working now.

Now I'm curious to know what the problem was!

> Could I put together a documentation PR for people getting started with gh-ost? Just the basics, running ci-build, and how the build system works?

Yes, please!

**Comment by jessbreckenridge** [comment]
I haved opened a PR (Placeholder).

I was wondering if a change in the PR template is in order as well:

```
- [ ] contributed code is using same conventions as original code
- [ ] code is formatted via `gofmt` (please avoid `goimports`)
- [ ] code is built via `./build.sh`
- [ ] code is tested via `./test.sh`
```

Should we replace this with running `cibuild`? I believe it performs all these steps, except perhaps running `tests.sh`.

**Comment by shlomi-noach** [comment]
> Should we replace this with running cibuild? 

Yes.

**Comment by shlomi-noach** [comment]
@jessbreckenridge it just occurred to me that your setup issue is likely a `golang` setup: `golang` is very picky about the path where you clone your repo to.  What you want is:

1. Have `GOPATH` set

```
	cd $GOPATH
	mkdir -p {src,bin,pkg}
	mkdir -p src/github.com/github/
	cd src/github.com/github/
	git clone git@github.com:github/gh-ost.git
	cd gh-ost/
```

**Comment by jessbreckenridge** [comment]
PR related to this was merged.

**Comment by jessbreckenridge** [comment]
This was a self created issue, closing.
