### ISSUE TITLE
Demote --critical-load from exiting process to pausing it

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#418]
I discussed this with @shlomi-noach on Monday: 

`--critical-load` is currently a copy of a flag from pt-online-schema-change: in the event that that value is hit (e.g. high threads_running), gh-ost panics and dies. 

This behaviour makes sense in pt-online-schema-change because it has triggers on the master/host that copy writes from the old to new table, so on things going badly, you want those triggers removed since they impede performance.

With gh-ost, however, if its copy thread is paused, there's no extra load on the master (the gh-ost tables are there, but no write activity is going to them). So pausing gh-ost for a period of time looks the same to the master as gh-ost not running at all.

On that note, I suggest a new feature, where `--critical-load` is treated as a more severe `--max-load`, where gh-ost is paused for, say, an hour (or some other default value). This is on the idea that whatever bad thing just happened is temporary and/or fixable and we'd rather not lose hours/days of table copying because of it. And if things were fixed before that hour is up, gh-ost could be unpaused.

**Comment by shlomi-noach** [comment]
We can introduce this new behavior without breaking backwards compatibility by adding some `--critical-load-sleep-seconds`

- would default `0`
- if nonzero, then it overrides the `panic` executed today on `critical-load`, and instead go to sleep. During that sleep, `gh-ost` will not issue _any queries_. At the end of the sleep, `gh-ost` resumes work as usual (and of course may hit `critical-load` again and go to sleep again).

**Comment by tomkrouper** [comment]
When I first read the title of this, I was thinking... I don't like it. Then I read the explanation, and I'm like :+1: :+1:. I like the idea and the implementation idea.

**Comment by vjanelle** [comment]
Instead of a specific amount of time, you could also implement an exponential backoff.

**Comment by shlomi-noach** [comment]
> Instead of a specific amount of time, you could also implement an exponential backoff.

that could work well, too.

**Comment by shlomi-noach** [comment]
For now, #424 is merged with a CLI flag `--critical-load-hibernate-seconds`, and without exponential backoff. We will be running this in production for some time before re-considering whether we need a more elaborate backoff or whether the pre-set hibernation time is good enough.
