### ISSUE TITLE
stuck at "Waiting for ghost table to be migrated. Current lag is 0s"

### ISSUE THREAD

**Issue by gongfangjun** [github/gh-ost#421]
Hi all,when I use the command below,it stucked at 
   "INFO Waiting for ghost table to be migrated. Current lag is 0s"

  the command is : 

`./gh-ost -host="127.0.0.1" -port=3306 -database="mydb" -table="ghost_test_table"  -user="admin" -password="123456" -alter="add index my_index(uname,addr(10)) USING BTREE" --allow-on-master -execute  -initially-drop-ghost-table -exact-rowcount --initially-drop-old-table -chunk-size=10 -verbose`

  The mysql  version I use is "5.7.13-log", the gh-ost is "gh-ost-binary-linux-20170403125842.tar.gz" on the page "https://github.com/github/gh-ost/releases/tag/v1.0.36"

 So, how can I solve this problem? Please give me a hand, Thanks a lot!

**Comment by shlomi-noach** [comment]
@gongfangjun are you migrating on the master? Or on a replica?

If on a replica, is all chain up to master configured with `log_slave_updates`? Are you using replication filters?

Can you please confirm the _ghost_ table (should be called `_ghost_test_table_gho`) has been created on the master?

**Comment by shlomi-noach** [comment]
What is the table structure? Is it using `JSON` or `POINT` types?

**Comment by gongfangjun** [comment]
@shlomi-noach  
   It has been solved by change the mysql master config file. A few days ago, I set the "binlog-do-db" to another db, so, after I changed this configuration, it worked.
   Anyway, thank youe very much for your help!

**Comment by mahemoff** [comment]
In case it helps anyone searching, same issue and resolution here. If you encounter ghost hanging on something like `binlogsyncer.go:573: [info] rotate to (mysql-bin.000001, 100101)`, run ghost again with `--verbose` flag, and if it hangs on "Waiting for ghost table to be migrated. Current lag is 0s", it's possible the specified database isn't setup for replication.

Ensure mysql config's `binlog_do_db` is pointing to the right database and verify that bin logs update when changes are made to the database.
