### ISSUE TITLE
 StreamEvents encountered unexpected error: data len 628 < expected 14598

### ISSUE THREAD

**Issue by chenmi319** [github/gh-ost#428]
The version is 1.0.36 build with the latest master code(Also get same error on latest release version).
The mysql server is mysql 5.7.16 on AWS RDS .
My command after symplified is
```
./gh-ost --allow-on-maste --alter="ADD INDEX \`updated_at_index\` (\`updated_at\` ASC)"  --assume-rbr --allow-master-master --cut-over=default --exact-rowcount --concurrent-rowcount --default-retries=10 --execute
```
It works well at first 30%. Soon the command failed with
```
2017-06-11 06:16:20 DEBUG Skipping handled query at mysql-bin-changelog.056652:110935060
2017-06-11 06:16:20 DEBUG Skipping handled query at mysql-bin-changelog.056652:110943258
2017-06-11 06:16:20 DEBUG Skipping handled query at mysql-bin-changelog.056652:110951456
2017/06/11 06:16:20 binlogstreamer.go:47: [error] close sync with err: data len 628 < expected 14598
2017-06-11 06:16:20 INFO StreamEvents encountered unexpected error: data len 628 < expected 14598
2017-06-11 06:16:22 DEBUG Issued INSERT on range: [323950439]..[324050439]; iteration: 4657; chunk-size: 100000
Copy: 324050000/1002760629 32.3%; Applied: 0; Backlog: 0/100; Time: 3h13m10s(total), 3h13m3s(copy); streamer: mysql-bin-changelog.056652:110951456; State: migrating; ETA: 6h44m20s
2017-06-11 06:16:25 DEBUG Done streaming
2017-06-11 06:16:25 FATAL 11 successive failures in streamer reconnect at coordinates mysql-bin-changelog.056652:4
```
I have run this command about 4 times with both release code and the latest master code. Is there and clues about what happened and how to fix it? Thanks!

**Comment by shlomi-noach** [comment]
@chenmi319 what is the table structure?

**Comment by chenmi319** [comment]
The table structure is
```
| course_unit_exercise_progress | CREATE TABLE `course_unit_exercise_progress` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `course_unit_progress_id` bigint(20) NOT NULL,
  `exercise_id` int(11) NOT NULL,
  `is_subjective` tinyint(1) NOT NULL,
  `score` float DEFAULT NULL,
  `first` float DEFAULT NULL,
  `highest` float DEFAULT NULL,
  `sum` float NOT NULL DEFAULT '0',
  `times` int(11) NOT NULL DEFAULT '0',
  `avg` int(11) DEFAULT NULL,
  `rating` float DEFAULT NULL,
  `audio_urls` json DEFAULT NULL,
  `audio_durations` json DEFAULT NULL,
  `image_urls` json DEFAULT NULL,
  `mark_times` int(11) NOT NULL DEFAULT '0',
  `upload_times` int(11) NOT NULL DEFAULT '0',
  `mark_teachers` json DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IX_course_unit_progress_id_exercise_id` (`course_unit_progress_id`,`exercise_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1002772015 DEFAULT CHARSET=utf8 |

```
Thanks!

**Comment by shlomi-noach** [comment]
@chenmi319 unfortunately `gh-ost` does not yet support the `json` format, as per https://github.com/github/gh-ost/blob/master/doc/requirements-and-limitations.md

todo:

- [ ] support JSON columns
- [ ] until then, have `gh-ost` recognize `json` columns and bail out with a clear message.

**Comment by chenmi319** [comment]
Yeah I see. Thank you very much for your reply !

**Comment by shlomi-noach** [comment]
For `JSON` support we could possibly switch to the new `vitess` binlog parser.

**Comment by chenmi319** [comment]
Sounds great. I have no experience in 'go' and maybe have a try in future. It is appreciate that you can help to edit just a few codes and push a new branch if you are free. I can help to run a test. Thanks all the way!

**Comment by shlomi-noach** [comment]
@chenmi319 unfortunately this fix involves a library that I use, rather than own, and am less familiar with the code. We'll see. My estimate is that you shouldn't expect this in the next few days, for sure.

**Comment by chenmi319** [comment]
@shlomi-noach That's fine. I'll skip the table structure change and find another way first. Thanks all the way!
