### ISSUE TITLE
Can gh-ost be used to optimize tables ?

### ISSUE THREAD

**Issue by nirbd** [github/gh-ost#432]
We use pt_online_schema_change like this:

 pt-online-schema-change --alter "ENGINE=InnoDB" D=db_users,t=users_extra_info --execute

where the engine is already InnoDB to begin with, to optimize the tables.

Can ghost be used for table optimization in a similar way?

10X Nir

**Comment by shlomi-noach** [comment]
Yes, in the exact same way. Specify `engine=innodb` as your `alter` statement.

**Comment by nirbd** [comment]
Thanks Shlomi,

Now my only problem is lack of Triggers support... Show stopper for me.

Thanks again,
- Nir

**Comment by shlomi-noach** [comment]
I'm happy if anyone wants to contribute trigger support... It's possible to do, though of course not trivial.
