### ISSUE TITLE
FR: Support JSON datatype

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#434]
The `go-mysql` library may be good to support `JSON` at this time; if not, work towards making that happen. If not, also look at the vitess parser (that would be a major refactor).

Related: 
- https://github.com/github/gh-ost/issues/428
- https://github.com/github/gh-ost/issues/268#issuecomment-290979747

**Comment by arthurnn** [comment]
I guess go-mysql now supports JSON types https://github.com/siddontang/go-mysql/issues/138 .
Is it just matter of us implementing it?

**Comment by shlomi-noach** [comment]
I'll look into it.
