### ISSUE TITLE
about Switching Table operation in Gh-ost

### ISSUE THREAD

**Issue by bckim2** [github/gh-ost#436]
Hello, this is Bckim2.

Could you please tell us about Switching Table operation in Gh-ost ?

It Just execute "alter rename table" like this?

ex)
alter table original-table rename to original-table-backup;
alter table original-table-gho rename to original-table;

if then, What are the measures against meta-locks?

if there is long transacntion in the altering table, 
Gh-ost has to occur meta-lock until finish the long transaction.

thanks.

**Comment by shlomi-noach** [comment]
The table cut-over operation is described [here](https://github.com/github/gh-ost/issues/82) and [here](http://code.openark.org/blog/mysql/solving-the-non-atomic-table-swap-take-iii-making-it-atomic). It is not a two-step rename but a single, atomic, blocking rename of both tables.

The measures against meta-locks are https://github.com/github/gh-ost/pull/90, namely `set session lock_wait_timeout` which works very well (starting MySQL `5.6`). The default timeout is `3` seconds.

In the event of timeout `gh-ost` retries multiple times, up to `--default-retries` times.

`gh-ost` does not kill queries operating on the table. If you wish to do so (the Facebook tool does that), you can use your own custom [hooks](https://github.com/github/gh-ost/blob/master/doc/hooks.md).

**Comment by bckim2** [comment]
thank you for your answer.
