### ISSUE TITLE
the gh-ost is case-sensitive,a columns data loss....

### ISSUE THREAD

**Issue by luoxiaocai91** [github/gh-ost#446]
test table ：
```
Create Table: CREATE TABLE `sbtest` (
  `id` int(10) unsigned NOT NULL,
  `k` int(10) unsigned NOT NULL DEFAULT '0',
  `c` char(120) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `pad` char(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `k` (`k`),
  KEY `idx_c` (`c`(10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

```sql
alter table sbtest modify K bigint unsigned NOT NULL DEFAULT '0';
```
the data:
```
select k,count(*)  from sbtest group by k;
+-----+----------+
| k   | count(*) |
+-----+----------+
|   0 |     9900 |
|  10 |      207 |
|  15 |        1 |
|  20 |        5 |
| 100 |        1 |
+-----+----------+
after alter,the data:
select k,count(*)  from sbtest group by k;
+---+----------+
| k | count(*) |
+---+----------+
| 0 |    10114 |
+---+----------+
```
the log:
![image](https://user-images.githubusercontent.com/26221539/28106444-6c3db530-6716-11e7-80c8-fc05e4acb101.png)

it not choice the columns of k,the mysql always ingore case-sensitive.so i want consider this condition.this is a example. we loss data in the product,because of the other people‘s carelessness. pt-online-schema-change is ingore case-sensitive.

the version is "5.6.28-76.1-log Percona Server (GPL), Release 76.1, Revision 5759e76"
the table is common.
command :
```
gh-ost_v1.0.36 
--max-load=Threads_running=32 
--critical-load=Threads_running=32 
--chunk-size=1000 
--throttle-control-replicas="$throttle_control_replicas" 
--max-lag-millis=1000 
--initially-drop-old-table 
--initially-drop-ghost-table 
--ok-to-drop-table 
--conf="***" 
--host="$binlog_slave" 
--port="$port" 
--database="$database" 
--table="$table" 
--debug 
--alter="$sql" 
--switch-to-rbr 
--allow-master-master 
--cut-over=default 
--default-retries=3 
--critical-load-interval-millis=3000 
--panic-flag-file=/tmp/ghost.panic.flag 
--postpone-cut-over-flag-file=/tmp/ghost.postpone.flag 
--execute
```

**Comment by shlomi-noach** [comment]
> it not choice the columns of k,the mysql always ingore case-sensitive.so i want consider this condition.this is a example. we loss data in the product,because of the other people‘s carelessness. pt-online-schema-change is ingore case-sensitive.

I'm very sorry to hear you lost data.

To continue the description of this issue, the outsome of the `alter` statement is:

```
Create Table: CREATE TABLE `sbtest` (
  `id` int(10) unsigned NOT NULL,
  `K` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c` char(120) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `pad` char(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `k` (`K`),
  KEY `idx_c` (`c`(10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

where the `k` column was renamed to `K`. `gh-ost` didn't pick this column as being the same.

**Comment by shlomi-noach** [comment]
This will be handled by work on https://github.com/github/gh-ost/pull/447

**Comment by cenkore** [comment]
gh-ost should not change the column name by self . change column should only command `"change column c1 c2"` achieve it.  And in my reproduce , if add `--approve-renamed-columns` ,data is ok.

**Comment by shlomi-noach** [comment]
These binaries should fix the problem. @luoxiaocai91 or anyone else that would like to experiment:

[Uploading gh-ost-binary-linux-20170713132503.tar.gz…]()
[gh-ost-binary-osx-20170713132503.tar.gz](https://github.com/github/gh-ost/files/1144798/gh-ost-binary-osx-20170713132503.tar.gz)

**Comment by cenkore** [comment]
@shlomi-noach 
I cannot download the linux binary ..

**Comment by shlomi-noach** [comment]
ah yes, my bad. Here are the binaries again:

[gh-ost-binary-linux-20170713132503.tar.gz](https://github.com/github/gh-ost/files/1144846/gh-ost-binary-linux-20170713132503.tar.gz)

[gh-ost-binary-osx-20170713132503.tar.gz](https://github.com/github/gh-ost/files/1144847/gh-ost-binary-osx-20170713132503.tar.gz)

**Comment by cenkore** [comment]
I test your binary , and it's OK ! When would you merge and release new version , very expect it !

**Comment by shlomi-noach** [comment]
I'll need some days of testing in production next week before I merge this.

**Comment by shlomi-noach** [comment]
merged; to be released on Friday.

**Comment by shlomi-noach** [comment]
released in https://github.com/github/gh-ost/releases/tag/v1.0.40

**Comment by luoxiaocai91** [comment]
thank you for timely repair！I test it's work.

**Comment by shlomi-noach** [comment]
Thank you for confirming!
