### ISSUE TITLE
Issue with DATETIME(6) on MariaDB

### ISSUE THREAD

**Issue by aadant** [github/gh-ost#450]
Here are the steps to reproduce : 

1. on the master

```
create database ghost;
use ghost;
drop table if exists t;
create table t(id bigint, d datetime(6),primary key(id)) engine=InnoDB;
```

2. on the test replica 

Using gh-ost-binary-linux-20170403125842.tar.gz

```
touch /tmp/ghost.postpone.t.flag 
./gh-ost \
--max-load=Threads_running=32 \
--critical-load=Threads_running=1000 \
--initially-drop-ghost-table \
--initially-drop-old-table \
--chunk-size=10000 \
--dml-batch-size=100 \
--max-lag-millis=1500 \
--user="" \
--password="" \
--host= \
--database="ghost" \
--table="t" \
--verbose \
--skip-foreign-key-checks \
--alter="engine=InnoDB" \
--switch-to-rbr \
--cut-over=default \
--test-on-replica \
--default-retries=120 \
--panic-flag-file=/tmp/ghost.panic.flag \
--postpone-cut-over-flag-file=/tmp/ghost.postpone.t.flag \
--approve-renamed-columns \
--replica-server-id=83 \
--execute
```

3. on the master

> insert into t(id,d) values(1,'2017-07-14 00:09:51.073974')
> commit;

4. on the test replica

`rm /tmp/ghost.postpone.t.flag`

5. on the test replica database, microseconds are multiplied by 10

```
MariaDB [ghost]> select * from t;
+----+----------------------------+
| id | d                          |
+----+----------------------------+
|  1 | 2017-07-14 00:09:51.073974 |
+----+----------------------------+
1 row in set (0.02 sec)

MariaDB [ghost]> select * from _t_gho;
+----+----------------------------+
| id | d                          |
+----+----------------------------+
|  1 | 2017-07-14 00:09:51.739740 |
+----+----------------------------+
1 row in set (0.02 sec)
```
This looks like a major issue with DATETIME(6). The database is MariaDB 10.1.20.
Not sure if it is an issue with Oracle MySQL.

**Comment by shlomi-noach** [comment]
Thank you, I'll investigate.

**Comment by shlomi-noach** [comment]
I have a guess as for why this is happening. It's a bit outside my code but I should be able to fix it.

**Comment by shlomi-noach** [comment]
Reproduced

**Comment by shlomi-noach** [comment]
https://github.com/github/gh-ost/issues/452 fixes the problem. @aadant, can you please test attached binaries?
I will meanwhile send to production testing.

[gh-ost-binary-linux-20170719155447.tar.gz](https://github.com/github/gh-ost/files/1159138/gh-ost-binary-linux-20170719155447.tar.gz)
[gh-ost-binary-osx-20170719155447.tar.gz](https://github.com/github/gh-ost/files/1159139/gh-ost-binary-osx-20170719155447.tar.gz)

**Comment by aadant** [comment]
@shlomi-noach  : thanks, that fixes the issue. I ran a couple of tests and it is OK now.

**Comment by shlomi-noach** [comment]
Thank you. I will publish a release this Thursday or Friday.

**Comment by shlomi-noach** [comment]
released in https://github.com/github/gh-ost/releases/tag/v1.0.40
