### ISSUE TITLE
Improve connection logging to indicate the usage.

### ISSUE THREAD

**Issue by sjmudd** [github/gh-ost#461]
I have been testing gh-ost and notice it may make several different types of connections to different servers. That may lead to confusion if you have a lot. Therefore I think it would be good to identify: the "writer" connection, the "reader" (when you're running against a replica) and even the "monitoring" connections.

e.g.
```
2017-07-26 11:02:40 INFO connection validated on myreplica.example.com:3306
```
maybe could be:

```
2017-07-26 11:02:40 INFO inspector connection validated on myreplica.example.com:3306
```
(or similar)

and similarly adjust the entries for the connections used for writing and any other read handles you make.

**Comment by akshaychhajed** [comment]
If this involves reviewing code and modifying log statements, I can give this a shot.

**Comment by tomkrouper** [comment]
@akshaychhajed, please, give it a shot.
