### ISSUE TITLE
Add unique key cause data-integrity problem

### ISSUE THREAD

**Issue by cenkore** [github/gh-ost#485]
#167 #477 
This problem is due to apply dml binlog and row-copy thread concurrent issue. And gh-ost self-mechanism would replace `insert` to `insert ignore into`(row-copy) or `replace into`(binlog apply).

When table have a primary key , and wanna add a unique key (or opposite, add primary key),there have two conditions would cauze data-integrity problem
> 1. original table data could not match, and would be duplicate in new unique key
> 2. app write "duplicate" rows into original table when gh-ost running

In fact this two condition is similar , and gh-ost do not need to care it. As try to fix it

`/*
create table member (id int , name varchar(10) , nickname varchar(10),primary key(id));
insert into member values(1,'thsun','cenkore');
*/`

> -- ddl: add unique key uk(name,nickname);

If i execute `insert into member values(2,'thsun','cenkore')` in a right opportunity when gh-ost is running

1. First binlog apply and then row-copy

> if gh-ost apply binlog firstly and execute `replace into _del_member_gho values(2,'thsun','cenkore')` -> success
> then row-copy (1,'thsun','cenkore'),(2,'thsun','cenkore') and execute
> `insert ignore into _del_member_gho values(1,'thsun','cenkore')`  -> ignore , data-integrity problem
> `insert ignore into _del_member_gho values(2,'thsun','cenkore')`  -> ignore

2. First row-copy and then binlog apply

> if row-copy firstly and execute `insert ignore into _del_member_gho values(1,'thsun','cenkore')` -> success
> then have two sub-conditon , 1.1 row-copy and binlog apply 1.2 binlog apply and row-copy
> 	1.1 row-copy continuously and execute `insert ignore into _del_member_gho values(2,'thsun','cenkore')` -> ignore
> 	at last binlog apply and execute `replace into _del_member_gho values(2,'thsun','cenkore')`  -> data-integrity problem
> 
> 	1.2 binlog apply firstly and execute `replace into _del_member_gho values(2,'thsun','cenkore')` -> data-integrity problem
> 	at last row-copy another record and execute `insert ignore into _del_member_gho values(2,'thsun','cenkore')` -> ignore

In this two condition , user may be hope failure and bail out , but not data loss.

Condition 1 `First binlog apply and then row-copy`:
before row-copy , gh-ost can validate whether there already have primary key data in the _gho table,
if true, execute `insert ignore into`, otherwise switch to  execute `insert into` , As follows replay condition 1
> 1. `replace into _del_member_gho values(2,'thsun','cenkore')` -> success
> 2. `insert into _del_member_gho values(1,'thsun','cenkore')`  -> fail (not exists original primary key id 1 , so insert into)
> 3. `insert ignore into _del_member_gho values(2,'thsun','cenkore')`  -> ignore

Similar to condition 1

Condition 2 `First row-copy and then binlog apply`:

before binlog apply , gh-ost can validate whether there already have primary key data in the _gho table,
if true ,execute `replace into`, otherwise switch to execute `insert into` , As follows replay condition 2
sub 1
> 1. row-copy `insert ignore into _del_member_gho values(1,'thsun','cenkore')` -> success
> 2. row-copy `insert ignore into _del_member_gho values(2,'thsun','cenkore')` -> ignore
> 3. binlog apply `insert into _del_member_gho values(2,'thsun','cenkore')`  -> fail (not exists original primary key id 2 , so insert into)

sub 2
> 1. row-copy `insert ignore into _del_member_gho values(1,'thsun','cenkore')` -> success
> 2. binlog apply `insert into _del_member_gho values(2,'thsun','cenkore')` -> fail

or firstly row-copy id 2

> 1. row-copy `insert ignore into _del_member_gho values(2,'thsun','cenkore')` -> success
> 2. binlog apply `replace into _del_member_gho values(2,'thsun','cenkore')` -> success(exists original primary key id 2)
> 3. row-copy `insert into _del_member_gho values(1,'thsun','cenkore')` -> fail (not exists original primary key id 1 , so insert into)

As stated above, add a unique key maybe could not fully use `replace into` and `insert ignore into`. instead , switch to `insert into` in the specific scene. But for the range query and write slice data to gho table , it may be more difficult to achieve.

**Comment by shlomi-noach** [comment]
Thank you for your analysis.

There is no solution to adding a `unique key` with duplicate values. It does not matter how we reorder row-copy and binlog-apply, even if we first only run row-copy on entire table ; there is always a scenario where a duplicate can happen and where the _ghost_ table is not in sync with the original table. Forgive me for not describing the full list of options here, they are not documented anywhere but they've been in my mind for 8 years now.

 It is on the user's responsibility to understand the impact of adding a `unique key`. As per https://github.com/github/gh-ost/issues/477, I'm thinking I'll add the opt-in `-fail-on-adding-unique-key`.

I'm closing this issue as discussion takes place in #477 .
