### ISSUE TITLE
the data loss , float data type

### ISSUE THREAD

**Issue by cenkore** [github/gh-ost#486]
My test table as follows , I dont know whether use reflect to get data type.
```
CREATE TABLE `floa` (
  `fl` float NOT NULL,
  `n` int(11) DEFAULT NULL,
  PRIMARY KEY (`fl`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
insert into floa select 1.1 , 1;
insert into floa select 1.2 , 2;
```
> cmd
```gh-ost --host=10.28.77.43 --database="ghostdb" --table="floa" --debug --alter="add column it int" --concurrent-rowcount --conf="/usr/local/gh-ost.cnf" --port=55944 --initially-drop-old-table --initially-drop-ghost-table --execute```

> log
```Copy: 0/2 0.0%; Applied: 0; Backlog: 0/1000; Time: 2s(total), 1s(copy); streamer: SVR14883DE630-bin.001861:131792890; State: migrating; ETA: N/A
Copy: 1/1 100.0%; Applied: 0; Backlog: 0/1000; Time: 2s(total), 1s(copy); streamer: SVR14883DE630-bin.001861:131792890; State: migrating; ETA: due
```
> binlog
```
# insert /* gh-ost `ghostdb`.`floa` */ ignore into `ghostdb`.`_floa_gho` (`fl`, `n`, `it`)
#       (select `fl`, `n`, `it` from `ghostdb`.`floa` force index (`PRIMARY`)
#         where (((`fl` > '1.1') or ((`fl` = '1.1'))) and ((`fl` < 1.100000023841858) or ((`fl` = 1.100000023841858)))) lock in share mode
#       )```

**Comment by shlomi-noach** [comment]
Thank you. Your observation is correct, and `float` shouldn't be trusted for range comparisons. 
I'd also discourage people from using `float` as `primary key` or `unique key` in the first place.

The solution I see is to make `gh-ost` intentionally fail if all possible shared keys have `float`.
