### ISSUE TITLE
--help going to stderr

### ISSUE THREAD

**Issue by zmoazeni** [github/gh-ost#492]
This is a minor quibble, but `gh-ost --help` sends its output to stderr. Is that an intentional decision?

It's a bummer for me because I keep having to remember the `2>&1` syntax just to pipe it to `less` or `grep` (you would think after all these years I would have it memorized, but I don't).

If I get some :+1: to move to stdout, I'll take a stab at a PR. But I wanted to ask first.

**Comment by shlomi-noach** [comment]
@zmoazeni good point. I'm happy for a PR!

**Comment by zmoazeni** [comment]
Yeah go for it! My schedule has been extremely busy the past few weeks anyway so I have made zero progress on it.

If you wouldn't mind, could you ask if someone does decide to take this on that they just drop a note here? That way this doesn't fall by the wayside if no one volunteers.

**Comment by akshaychhajed** [comment]
Sure. I would let them know.
Thanks @zmoazeni

**Comment by vedhavyas** [comment]
@zmoazeni I can take it up 👍
