### ISSUE TITLE
Version 1.0.40 writes the password in the output

### ISSUE THREAD

**Issue by plapythian** [github/gh-ost#496]
We upgraded to 1.0.40 and we're seeing the database password is written in the log:

XXXX/XX/XX XX:XX:XX binlogsyncer.go:75: [info] create BinlogSyncer with config &{99999 mysql db.somedomain.com 3306 user **password**  false false <nil>}

**Comment by shlomi-noach** [comment]
This is done as part of the `go-mysql` underlying library, [here](https://github.com/siddontang/go-mysql/blob/89fc82130ac2531f20c672e80d5283c0b0c15290/replication/binlogsyncer.go#L106). 

I'll edit to remove the password as I'm including this library inline.

@plapythian would you care to likewise submit this issue in https://github.com/siddontang/go-mysql/, so that @siddontang can consider doing the same upstream?

**Comment by siddontang** [comment]
@shlomi-noach 

I will ignore the password output.

**Comment by siddontang** [comment]
PTAL @shlomi-noach https://github.com/siddontang/go-mysql/pull/163

**Comment by plapythian** [comment]
Thanks

**Comment by shlomi-noach** [comment]
I'll incorporate the change either tomorrow or after PerconaLive.

**Comment by morgado-pythian** [comment]
Wondering if this has been fixed in any release?
I'm still seeing it on latest:

```
$ sh test-g.sh
2018-01-11 11:31:20 INFO starting gh-ost 1.0.42
2018-01-11 11:31:20 INFO Migrating `foo`.`tbl1`
2018-01-11 11:31:20 INFO connection validated on localhost:20795
2018-01-11 11:31:20 INFO User has ALL privileges
2018-01-11 11:31:20 INFO binary logs validated on localhost:20795
2018-01-11 11:31:20 INFO Restarting replication on localhost:20795 to make sure binlog settings apply to replication thread
2018-01-11 11:31:20 INFO Inspector initiated on LMCI:20795, version 5.7.20-log
2018-01-11 11:31:20 INFO Table found. Engine=InnoDB
2018-01-11 11:31:20 INFO Estimated number of rows via EXPLAIN: 1
2018-01-11 11:31:20 INFO Recursively searching for replication master
2018-01-11 11:31:20 INFO Master found to be LMCI:20795
2018-01-11 11:31:20 INFO log_slave_updates validated on localhost:20795
2018-01-11 11:31:20 INFO connection validated on localhost:20795
2018/01/11 11:31:20 binlogsyncer.go:75: [info] create BinlogSyncer with config &{99999 mysql localhost 20795 msandbox msandbox  false false <nil>}
<snip>
```

In these BinlogSyncer entries it shows the username and password (msandbox) in clear text.

**Comment by shlomi-noach** [comment]
My attempt at updating the `go-mysql` library was unsuccessful. Some changes in `go-mysql` (namely, subsecond resolution for temporal values) have been made that break `gh-ost`'s data integrity.

I will therefore just apply the same masking on the password as done on `go-mysql`. Thank you for the reminder!

**Comment by shlomi-noach** [comment]
fix is in `master`, no official release yet.

**Comment by morgado-pythian** [comment]
Just verified the plain password fix is in 1.0.44. 
Thanks Shlomi!

**Comment by shlomi-noach** [comment]
@morgado-pythian thank you for confirming! And I did forget to drop a note that this is released in `1.0.44`, thank you for pointing this out!

**Comment by morgado-pythian** [comment]
No worries! Hmm.. I see the changelog entry here:

Remove plaintext password from log
https://github.com/github/gh-ost/releases/tag/v1.0.44

Maybe you forgot you had added it already :)

**Comment by shlomi-noach** [comment]
I mean I forgot to drop the note here in this Issue.

**Comment by morgado-pythian** [comment]
Ah, yes. Well, after the chat above, no more problems with missing notes and awareness, for sure! :)

**Comment by shlomi-noach** [comment]
LOL
