### ISSUE TITLE
localtests randomly fail with "can't find process"

### ISSUE THREAD

**Issue by zmoazeni** [github/gh-ost#497]
Hey gang, I'm setting up gh-ost on a different machine (weaker hardware than my typical box).

I notice I keep getting random failures:

```bash
$ GOPATH=/home/zmoazeni/projects/gh-ost/.gopath ./localtests/test.sh
# some tests pass, one will randomly fail

$ cat /tmp/gh-ost-test.log
2017-09-18 13:51:40 FATAL Cannot find process. Hints: metadata lock, rename
goroutine 1 [running]:
runtime/debug.Stack(0x4b, 0x31, 0x0)
        /home/zmoazeni/.gvm/gos/go1.7/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /home/zmoazeni/.gvm/gos/go1.7/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x0, 0x8cdc60, 0xc4201b2620, 0x0, 0x0)
        /home/zmoazeni/projects/gh-ost/.gopath/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0x10b
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Fatale(0x8cdc60, 0xc4201b2620, 0x0, 0x0)
        /home/zmoazeni/projects/gh-ost/.gopath/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:255 +0x3e
main.main()
        /home/zmoazeni/projects/gh-ost/.gopath/src/github.com/github/gh-ost/go/cmd/gh-ost/main.go:248 +0x1d8b
```

At first I thought it was something silly I was doing, but now I'm not so sure. I'm seeing a lot of this in the mysql error log:

```
2017-09-18T17:59:23.612926Z 175 [Note] While initializing dump thread for slave with UUID <00020596-3333-3333-3333-333333333333>, found a zombie dump thread with the same UUID. Master is killing the zombie dump thread(173).
2017-09-18T17:59:23.613022Z 175 [Note] Start binlog_dump to master_thread_id(175) slave_server(102), pos(, 4)
2017-09-18T17:59:25.203166Z 177 [Note] While initializing dump thread for slave with UUID <00020596-3333-3333-3333-333333333333>, found a zombie dump thread with the same UUID. Master is killing the zombie dump thread(175).
2017-09-18T17:59:25.203482Z 177 [Note] Start binlog_dump to master_thread_id(177) slave_server(102), pos(, 4)
```

I'm seeing this with Percona 5.7.18 and 5.7.19 with and without GTID enabled.

I believe I read these tests are going to morph into something CI can run continuously, but I'm just wondering if this rings a bell on what in the world is going on that these tests would flake out.

Or worse, if perhaps this is a legitimate issue the test suite is warning us about.

**Comment by zmoazeni** [comment]
Changing https://github.com/github/gh-ost/blob/52f2dd7a203305ff52741fa3cdc060e506bc5a9f/localtests/test.sh#L93

to `--default-retries=3` "fixes" my problem. Not sure if that's an issue with the test suite though or a lurking production issue.

**Comment by shlomi-noach** [comment]
That's interesting. This is coming from https://github.com/github/gh-ost/blob/52f2dd7a203305ff52741fa3cdc060e506bc5a9f/go/logic/migrator.go#L599.

I haven't seen this happening. Nonetheless, it is not unreasonable and in fact, as you have observed, the code supports retries for this check -- and so this was predicted.

 The `--default-retries` solution is super legit. I'm merely curious why `PROCESSLIST` would not reflect the query immediately as it does on my tests.

**Comment by zmoazeni** [comment]
Yeah I might dig in a bit. However I suspect most users of gh-ost are going to be running production servers much stronger than this XPS 13.

I'm guessing it's just a race condition exacerbated by this weaker gear.

I'm going to close this issue but I'll reopen if I find something serious.

**Comment by daisishu** [comment]
I also encountered this problem. Because there are many places affected by retry parameter, I added sleep100ms to judge whether there is rename in processlist, which will save 900ms time
