### ISSUE TITLE
Support for creating tables?

### ISSUE THREAD

**Issue by seanbourkemckenna** [github/gh-ost#506]
Hello! 

We heard that Github uses gh-ost for everything, is there a way to create tables using Gh-ost? Not seeing anything in the docs that suggest you can.

**Comment by shlomi-noach** [comment]
> We heard that Github uses gh-ost for everything

We don't use it to store your git info!

Joking aside, we use `gh-ost` to migrate table schemas, not to create them. Unsure how you heard we were runnign it for everything.

In particular, `gh-ost` is just a part in the general schema migration flow. There's PRs and tests and whatnot. See Tom Krouper's [presentation](https://www.percona.com/live/17/sessions/automating-schema-changes-using-gh-ost) on the subject.

The reason `gh-ost` isn't interested in creating schemas is that as far as it is concerned, you just need to go ahead and `create table`. There's no need to tell it to run a full blown app to run that single query.

If you're looking for a more end-to-end solution, consider using https://github.com/skeema/skeema/ or https://github.com/square/shift (neither support `gh-ost` at this time).

**Comment by seanbourkemckenna** [comment]
🤐 

Got it! 

Appreciate the fast response and thanks for the suggestions 😄
