### ISSUE TITLE
Support extra alter-commands

### ISSUE THREAD

**Issue by druud62** [github/gh-ost#512]
To do both re-partitioning and uncompressing in one `gh-ost` run, I now do:

```
d=foo t=Bar ; \
echo 'throttle' |nc -U /tmp/gh-ost.$d.$t.sock ; \
echo '- - - -' ; \
echo Now execute: mysql $d -BNe \"ALTER TABLE \\\`_$t\_gho\\\` KEY_BLOCK_SIZE=0 ROW_FORMAT=DYNAMIC\" ; \
echo And after: echo \'no-throttle\' \|nc -U /tmp/gh-ost.$d.$t.sock
```

It would be much more convenient to be able to do that already from the initial command, for example by allowing multiple `-alter` options.

**Comment by druud62** [comment]
Mostly a duplicate of #476.

**Comment by shlomi-noach** [comment]
I don't see what in your original query does repartitioning. 

#476 discusses a particular fabulous bug in MySQL where multiple `ALTER` statements are not supported. We've never hit this bug, and are running plenty multi-alter statements.

```
`gh-ost --alter="ALTER TABLE t ADD COLUMN..., ADD INDEX ..., DROP INDEX ... KEY_BLOCK_SIZE=0 ROW_FORMAT=DYNAMIC"
```

^ should work well for you without a problem. Is there a specific reason you wish to support multiple `-alter` args?

**Comment by druud62** [comment]
I assumed it would be obvious that the re-partitioning was in the `--alter`. :)

**Comment by shlomi-noach** [comment]
@druud62 very good, let's start from the beginning. Is a multi-alter statement not working for you because it includes both a partitioning directive and a change to row format? Can you please describe the problem?

**Comment by druud62** [comment]
Ah, that made me try a bit harder, and on a 5.7.19 this works:
```
ALTER TABLE Test_ruud 
  ADD test_01 int
, KEY_BLOCK_SIZE=0 ROW_FORMAT=DYNAMIC 
  PARTITION BY HASH(id) PARTITIONS 4
;
```
There can be no comma before the PARTITION phrase, and it should be at the end.
(the old table was compressed, and not partitioned yet)

**Comment by druud62** [comment]
The "no comma" rule is strict, so without uncompressing it becomes:
```
ALTER TABLE Test_ruud 
  ADD test_02 int
  PARTITION BY HASH(id) PARTITIONS 8
;
```

**Comment by shlomi-noach** [comment]
duplicate: #688
