### ISSUE TITLE
non-atomic table swap

### ISSUE THREAD

**Issue by tivenwang** [github/gh-ost#530]
hi ~ I want to understand the principle of table swap from http://code.openark.org/blog/mysql/solving-the-non-atomic-table-swap-take-iii-making-it-atomic .  
"A blocked RENAME is always prioritized over a blocked INSERT/UPDATE/DELETE, no matter who came first
"。

Questions : 
is the rename  is always have priority over DML? why? is there has a documentation page?

**Comment by ggunson** [comment]
I never found any official documentation that explained this, and I remember that the discussions that lead to the table swap algorithm didn't involve any doc or textbook referencing. It would be good to have this defined somewhere.

**Comment by shlomi-noach** [comment]
Some more in-depth explanation is found on https://github.com/github/gh-ost/issues/82. [Here is](https://github.com/mysql/mysql-server/blob/a533e2c786164af9bd276660b972d93649434297/sql/mdl.cc#L2312) the pointer to the MySQL code which supports the DDL-vs-DML priority assertion.

**Comment by ggunson** [comment]
> Some more in-depth explanation is found on #82.

That issue is nearly identical to your blog post that @tivenwang linked to in the description.

The MySQL code comments aren't very helpful here, talking about piglets and hogs (🐷). It might be worth asking someone at MySQL to explain it (maybe write up a docs bug?).

**Comment by tivenwang** [comment]
>Some more in-depth explanation is found on #82 
It·s useful for me. 
thanks a lot. @ggunson @shlomi-noach

**Comment by tivenwang** [comment]
> Some more in-depth explanation is found on #82    

It·s useful for me.
thanks a lot. @ggunson @shlomi-noach

**Comment by shlomi-noach** [comment]
At the time, our friend @MarkLeith of Oracle explained this to me. The explanation was lost in Slack's history rentention. Perhaps if he has the time he can explain again how DDL locks get higher priority over DML locks. 🙇
