### ISSUE TITLE
Impossible to migrate a high activity table without sync error with the binary logs

### ISSUE THREAD

**Issue by pothibo** [github/gh-ost#531]
So I've been migrating ~ 50 columns using gh-ost of different table sizes (from as low as 500k rows to 250m rows) but now I'm trying to migrate a table that has a lot of UPDATE query to it and I've had many different type of failures in the last 24 hours. I've tried adjusting parameters but I haven't been successful yet, here's a sample of the errors I get:

```
Copy: 21183000/284509416 7.4%; Applied: 39116; Backlog: 1000/1000; Time: 1h0m0s(total), 1h0m0s(copy); streamer: mysql-bin-changelog.002575:61125755; State: throttled, max-load Threads_running=459 >= 100; ETA: 12h25m51s
2017/12/22 15:19:15 binlogsyncer.go:490: [error] connection was bad 

[error] close sync with err: ERROR 1236 (HY000): Could not find first log file name in binary log index file
Copy: 22213000/284510893 7.8%; Applied: 40807; Backlog: 0/1000; Time: 1h3m35s(total), 1h3m35s(copy); streamer: mysql-bin-changelog.002575:4; State: migrating; ETA: 12h30m48s
```

This starts always under the same scenario, I have a 1000/1000 backlog on that table while migrating then I get the connection was bad error and then it crashes, I don't know much about log rotation but my understanding so far is that the problem might come because the buffer is full and there is a log rotation so I'm losing logs between the rotation.

Now, we're running on a maxed out RDS instance with 30k provisionned I/O.

The database is usually hovering at 25% CPU usage during the migration and the Write I/O at ~ 1k/sec while the Read is at about ~5k/sec

Since that db has a lot of stuff going on, I would love to have a 10k buffers but I've read from other issues that you are against that. so I don't know.

Last note:

The backlog fills usually because there is a Lag threshold or Running Threads treshold that is hit. 

Here's my last attempt:

```
gh-ost --database="database1" --user="user" --host="some.read.replica.amazon.ca" --password="password" --table="subscriptions" --assume-rbr --max-load=Threads_running=100 --critical-load=Threads_running=1200 --chunk-size=1000 --max-lag-millis=10000 --throttle-control-replicas="some.read.replica.amazon.ca" --exact-rowcount --concurrent-rowcount --alter="change referrer referrer TEXT character set utf8" --execute
```

**Comment by zmoazeni** [comment]
> but now I'm trying to migrate a table that has a lot of UPDATE query to it

For my own curiosity, how many updates/second does this table receive?

**Comment by pothibo** [comment]
I don't have the metrics on me but it comes in batches, it can idle for a bit then get to like ~300 update per secon

**Comment by shlomi-noach** [comment]
Some notes:

From our experience, increasing the buffer merely postpones one's problem till a few events later. We've recently had our largest migration running on a very busy table, and more often than not, hit the cache limits. Our migration ran over the duration of a few weeks (!) and so we had plenty of opportunity to play with configuration. Increasing/decreasing cache size made not impact. Increasing the cache merely gave a few more seconds of air, but then `gh-ost` would choke again.
Increasing the cache to `10,000` is unlikely to contribute much: I can only assume `10,000` is less than the amount of events in a single binlog file. I wouldn't want to cache the entire contents of an entire binlog file within `gh-ost`'s memory. And to what effect? The caching is mostly beneficial for avoiding back-and-forth interaction between binlogs & rowcopy operation, making more batched writes and running less commits. Committing `1,000` rows at a time or `10,000` rows at a time are unlikely to be the tipping point for a very busy migration.


Your error:
```
[error] close sync with err: ERROR 1236 (HY000): Could not find first log file name in binary log index file
```

Is something I haven't seen yet with `gh-ost`. Is it possible you have aggressive purging of binary logs on the master, such that when `gh-ost` is a few binlog files behind, said purging is already removing those binary logs `gh-ost` still hopes to work through?

The -
```
2017/12/22 15:19:15 binlogsyncer.go:490: [error] connection was bad
```
- error is a recoverable one, `gh-ost` reconnects at same point and keeps running. But I may be missing some info. Do you get this error all the time? Repeatedly?

Last, do you perhaps have some `pt-kill` daemon killing `gh-ost` connections?

**Comment by pothibo** [comment]
Thank you for your comments! Yes, I knew `connection was bad` is a recoverable error. As for `pt-kill` no, I don't think so but I'll double check.

As for aggressive binary logs rotation, I think it might be the case. I'll double check this morning and circle back here.

Thanks!
