### ISSUE TITLE
From DATETIME to TIMESTAMP in uk

### ISSUE THREAD

**Issue by tivenwang** [github/gh-ost#537]
Hi,
I have some questions to ask.  Review the code from https://github.com/github/gh-ost/blob/master/go/logic/inspect.go#L193 
Why is there such a limit. I can not think of the corresponding scene.

Thank you very much!

**Comment by shlomi-noach** [comment]
Permalink: https://github.com/github/gh-ost/blob/ce4e42da328ddad57ddea204fd768b91e58bdd96/go/logic/inspect.go#L193

**Comment by shlomi-noach** [comment]
`TIMESTAMP` has timezone context where `DATETIME` does not. `gh-ost` works by tailing the binary log, where `TIMESTAMP` columns are converted to `utc` and `DATETIME` columns are kept as string representation. The adding/removal of timezone context when one converts `DATETIME`->`TIMESTAMP` or vice versa, means it's impossible for `gh-ost` to correlate the binlog entry value with table value. 
Keep in mind `gh-ost` does not know the timezone context in which a `DATETIME` was created with.

**Comment by tivenwang** [comment]
Very reasonable, It is a usage limit.

Thank you !
