### ISSUE TITLE
TimeZone on ApplyDMLEventQueries

### ISSUE THREAD

**Issue by tivenwang** [github/gh-ost#540]
https://github.com/github/gh-ost/blob/ce4e42da328ddad57ddea204fd768b91e58bdd96/go/logic/applier.go#L1048

Should “time_zone = '+00:00' ”   be replaced by “this.migrationContext.ApplierTimeZone” ？

https://github.com/github/gh-ost/blob/ce4e42da328ddad57ddea204fd768b91e58bdd96/go/logic/applier.go#L484

**Comment by shlomi-noach** [comment]
Heh, so, why do you ask?
More seriously, can you please elaborate?
Insofar the tests are showing the current handling is correct. 

`TIMESTAMP` representation in binary logs is always UTC, hence the `+00:00`.

**Comment by tivenwang** [comment]
Yes. you are right.
My tests binlog lib base on  https://github.com/tivenwang/mysql-binlog-connector-java, DateTime has been converted. 
Very sorry for disturbing you.
