### ISSUE TITLE
throttle-control-replicas is ignored in interactive mode

### ISSUE THREAD

**Issue by wluo** [github/gh-ost#548]
Version: GA release v1.0.44, Linux
OS: Centos 6.7

After gh-ost starts, I tried issuing `throttle-control-replicas` command interactively but it seems to be ignored.

The actual command I issued was:
```
echo 'throttle-control-replicas="10.32.4.54,10.28.4.56,10.28.4.58"' | nc -U /tmp/gh-ost.dbname.table_name.sock
```

gh-ost was started using just one throttle-control-replica. After issuing the command, gh-ost still reported having just one throttle-control replica, and also it did not throttle even though one of the new replicas added was minutes behind in replication.

**Comment by shlomi-noach** [comment]
Can you please try without the quotes?

```
echo 'throttle-control-replicas=10.32.4.54,10.28.4.56,10.28.4.58' | nc -U /tmp/gh-ost.dbname.table_name.sock
```

**Comment by wluo** [comment]
Hey that worked! The documentation does show using quotes though, so maybe this is just a documentation issue.

Thanks for the speedy reply. We've been really loving `gh-ost` so far!!!

**Comment by shlomi-noach** [comment]
You are correct, the [docs](https://github.com/github/gh-ost/blob/4390c854ca9a2433b90bfbb9335b09235f68b323/doc/interactive-commands.md#known-commands) show an example with quotes.

Reopening till I decide whether to change the code or the docs.
