### ISSUE TITLE
Support exponential backoff for cutover attempts

### ISSUE THREAD

**Issue by kurtzur** [github/gh-ost#558]
Hello, we're using this library at Gusto. My teammate @nikhilmat has contributed here previously.

I'd like `gh-ost` to have a configuration option that enables exponential backoff for cutover attempts. From my reading, it seems the current behavior is that [`retryOperation`](https://github.com/github/gh-ost/blob/f0c3028f27d9fafc1f511a29d3105e9ada2798be/go/logic/migrator.go#L133) waits a constant 1 second in between cutover attempts. In our production environment, we've observed that waiting exponentially longer times between each attempt would result in a better DB load profile. One reason for this is that we have periodic background jobs that hammer certain tables at certain times. I expect that's a relatively common scenario for others as well.

I'd be happy to implement this change myself and submit a PR for it. I wanted to first verify with this issue that it's functionality you're open to adding in.

**Comment by shlomi-noach** [comment]
@kurtzur thank you, this makes sense and we're happy to receive a PR!
