### ISSUE TITLE
binlog encryption?

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#561]
I saw that Percona Server 5.7 has a binlog encryption feature -- https://www.percona.com/blog/2018/03/08/binlog-encryption-percona-server-mysql/

It's currently in beta, but if it gains traction we'll need to either say we don't support it and/or get the go mysql parser to support it. But temporarily it might be useful to add it to the docs somewhere?

**Comment by shlomi-noach** [comment]
I don't expect the `go-mysql` driver to support that. If it does gain traction and we're requested to support it we can revisit. Please see #562
