### ISSUE TITLE
[Question] Why gh-ost 's progress report is 200%?

### ISSUE THREAD

**Issue by leafonsword** [github/gh-ost#572]
Maximum value should be 100%, why did 200% occur?
```
...
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# throttle-control-replicas count: 2
# panic-flag-file: /tmp/ghost.panic.flag
# Serving on unix socket: /tmp/gh-ost.DB.TB.sock
Copy: 31259000/15215793 205.4%; Applied: 7654; Backlog: 0/1000; Time: 1h7m44s(total), 1h7m44s(copy); streamer: mysql-bin.000291:61287782; State: migrating; ETA: due
```

**Comment by shlomi-noach** [comment]
Did you run with `-exact-rowcount`? Can you please share your command line? Any other details you can please supply?

There can be various reasons. If runnning without `-exact-rowcount`, then row count is based on `SHOW TABLE STATUS` output which is merely a heuristic and known to be flaky.

If running with `-exact-rowcount` situation is much better, and `gh-ost` tries to dynamically adjust the count as it intercepts incoming queries, but that can be flaky too.

**Comment by leafonsword** [comment]
@shlomi-noach 
I didn't run with `-exact-rowcount`, so this is reason, thx!
