### ISSUE TITLE
LOGO for GH-OST

### ISSUE THREAD

**Issue by familqasimov** [github/gh-ost#591]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/40077199-f035c784-5891-11e8-9c7e-84c8bb0fea47.png)

**Comment by ggunson** [comment]
Hello @familqasimov !

> Hi sir.

Just so you know, there are more people working on this project than a single male, see [The Authors](https://github.com/github/gh-ost#authors). 

Thank you for the submission. We can see you spent some time designing these logos. One of our female designers at GitHub put a lot of effort into our existing logo back in 2016, and we have been very happy with it. We do not have plans to replace that logo at this time. 

Thank you very much for your efforts and support of our project!
