### ISSUE TITLE
Executing queries other than alter table

### ISSUE THREAD

**Issue by swallowstalker** [github/gh-ost#593]
Hi All,

As far as I know, gh-ost only executes query `ALTER TABLE table_name *`. How about executing `CREATE INDEX`, or `RENAME TABLE` (although I know both operations can be interpreted as `ALTER TABLE table_name ADD INDEX *` and `ALTER TABLE table_name RENAME TO new_table_name`) is there anyway I can directly send the query without converting them to `ALTER TABLE` syntax?

Thanks

**Comment by shlomi-noach** [comment]
`ALTER TABLE ... RENAME` is actually not supported (see https://github.com/github/gh-ost/blob/master/doc/requirements-and-limitations.md)

`CREATE INDEX` is not supported and you must use `--alter="ADD INDEX..."`. Out of curiosity, what is your use case, why do you prefer using `CREATE INDEX`?

**Comment by swallowstalker** [comment]
Hi @shlomi-noach, thanks for your quick response 👍 

Currently I'm trying to run sql which is generated from rails' active record. (it generates `CREATE INDEX`, `RENAME TABLE`) but it's ok, I just trying to find easier method to do `CREATE INDEX` on gh-ost.

I just found out that `RENAME TABLE` operation causes no downtime 👍 that's why it is trivial.
Thanks 👍 👍

**Comment by timvaillancourt** [comment]
Closing this as a resolved question
