### ISSUE TITLE
[error] connection was bad

### ISSUE THREAD

**Issue by aadant** [github/gh-ost#596]
Cut over was successful but we got those errors in the log :

`2018/05/23 03:40:26 binlogsyncer.go:495: [error] connection was bad
2018/05/23 03:40:26 binlogstreamer.go:47: [error] close sync with err: Sync was closed
`
Full log. 

> 2018-05-23 03:40:22 INFO Grabbing voluntary lock: gh-ost.1436439.lock
> 2018-05-23 03:40:22 INFO Setting LOCK timeout as 6 seconds
> 2018-05-23 03:40:22 INFO Looking for magic cut-over table
> Copy: 1415907350/1415907350 100.0%; Applied: 6629968; Backlog: 0/1000; Time: 39h23m45s(total), 19h51m2s(copy); streamer: binary.037878:945257751; State: migrating; ETA: due
> 2018-05-23 03:40:23 INFO Creating magic cut-over table test._t_del
> 2018-05-23 03:40:23 INFO Magic cut-over table created
> 2018-05-23 03:40:23 INFO Locking test.t, test._t_del
> 2018-05-23 03:40:23 INFO Tables locked
> 2018-05-23 03:40:23 INFO Session locking original & magic tables is 1436439
> 2018-05-23 03:40:23 INFO Writing changelog state: AllEventsUpToLockProcessed:1527064823427778880
> 2018-05-23 03:40:23 INFO Waiting for events up to lock
> 2018-05-23 03:40:23 INFO Intercepted changelog state AllEventsUpToLockProcessed
> 2018-05-23 03:40:23 INFO Handled changelog state AllEventsUpToLockProcessed
> 2018-05-23 03:40:24 INFO Waiting for events up to lock: got AllEventsUpToLockProcessed:1527064823427778880
> 2018-05-23 03:40:24 INFO Done waiting for events up to lock; duration=713.681887ms
> \# Migrating test.t; Ghost table is test._t_gho
> \# Migrating chl-transreportingdev-db01:3306; inspecting carf-mysql-dw01:3306; executing on chl-transreportingdev-db01
> \# Migration started at Mon May 21 12:16:37 -0500 2018
> \# chunk-size: 10000; max-lag-millis: 1500ms; dml-batch-size: 100; max-load: Threads_running=32; critical-load: Threads_running=1000; nice-ratio: 0.000000
> \# throttle-additional-flag-file: /tmp/gh-ost.throttle
> \# postpone-cut-over-flag-file: /tmp/ghost.postpone.t.flag
> \# panic-flag-file: /tmp/ghost.panic.flag
> \# Serving on unix socket: /tmp/gh-ost.test.t.sock
> Copy: 1415907350/1415907350 100.0%; Applied: 6629968; Backlog: 0/1000; Time: 39h23m46s(total), 19h51m2s(copy); streamer: binary.037878:945261759; State: migrating; ETA: due
> 2018-05-23 03:40:24 INFO Setting RENAME timeout as 3 seconds
> 2018-05-23 03:40:24 INFO Session renaming tables is 1436449
> 2018-05-23 03:40:24 INFO Issuing and expecting this to block: rename /* gh-ost */ table test.t to test._t_del, test._t_gho to test.t
> 2018-05-23 03:40:24 INFO Found atomic RENAME to be blocking, as expected. Double checking the lock is still in place (though I don't strictly have to)
> 2018-05-23 03:40:24 INFO Checking session lock: gh-ost.1436439.lock
> 2018-05-23 03:40:24 INFO Connection holding lock on original table still exists
> 2018-05-23 03:40:24 INFO Will now proceed to drop magic table and unlock tables
> 2018-05-23 03:40:24 INFO Dropping magic cut-over table
> 2018-05-23 03:40:24 INFO Releasing lock from test.t, test._t_del
> 2018-05-23 03:40:24 INFO Tables unlocked
> 2018-05-23 03:40:26 INFO Tables renamed
> 2018-05-23 03:40:26 INFO Lock & rename duration: 3.346974709s. During this time, queries on t were blocked
> 2018-05-23 03:40:26 INFO Looking for magic cut-over table
> 2018/05/23 03:40:26 binlogsyncer.go:107: [info] syncer is closing...
> 2018/05/23 03:40:26 binlogsyncer.go:495: [error] connection was bad
> 2018/05/23 03:40:26 binlogstreamer.go:47: [error] close sync with err: Sync was closed
> 2018/05/23 03:40:26 binlogsyncer.go:122: [info] syncer is closed
> 2018-05-23 03:40:26 INFO Closed streamer connection. err=<nil>
> 2018-05-23 03:40:26 INFO Dropping table test._t_ghc
> 2018-05-23 03:40:27 INFO Table dropped
> 2018-05-23 03:40:27 INFO Am not dropping old table because I want this operation to be as live as possible. If you insist I should do it, please add --ok-to-drop-table next time. But I prefer you do not. To drop the old table, issue:
> 2018-05-23 03:40:27 INFO -- drop table test._t_del
> 2018-05-23 03:40:27 INFO Done migrating test.t
> 2018-05-23 03:40:27 INFO Removing socket file: /tmp/gh-ost.test.t.sock
> 2018-05-23 03:40:27 INFO Tearing down inspector
> [MySQL] 2018/05/23 03:40:27 packets.go:118: write tcp 10.40.4.35:60952->7.128.12.24:3306: write: broken pipe
> 2018-05-23 03:40:27 INFO Tearing down applier
> [MySQL] 2018/05/23 03:40:27 packets.go:118: write tcp 10.40.4.35:48338->10.40.4.35:3306: write: broken pipe
> 2018-05-23 03:40:27 INFO Tearing down streamer
> 2018-05-23 03:40:27 INFO Tearing down throttler

BTW congrats on all the bug fixes. This was not working a year ago 

- cross data center 
- t is a huge partitioned table nearly 1TB

**Comment by shlomi-noach** [comment]
You may safely ignore those errors. They are reported by an underlying library and `gh-ost` takes care of them.

**Comment by aadant** [comment]
@shlomi-noach : thanks for looking. I guess we can close this. DBAs do not like to see errors in the logs ;-)

**Comment by shlomi-noach** [comment]
Agreed. I understand; since this error comes from an underlying library, I'm refraining from fixing it directly.
