### ISSUE TITLE
Question: Using IAM authentication on RDS with gh-ost 

### ISSUE THREAD

**Issue by wesleyk** [github/gh-ost#608]
Hi folks,

My team is trying to integrate with gh-ost on AWS, and the docs have been really helpful (in particular, https://github.com/github/gh-ost/blob/master/doc/rds.md).

One challenge we've run into is that we'd like to use [IAM authenticated MySQL users](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html). The password that gets generated in that authentication flow exceeds 32 characters, resulting in the following error:

```
FATAL MySQL replication length limited to 32 characters. See https://dev.mysql.com/doc/refman/5.7/en/assigning-passwords.html
```

and the corresponding details on mysql's documentation:
> The password used for a MySQL Replication slave account in a CHANGE MASTER TO statement is limited to 32 characters in length; prior to MySQL 5.7.5, if the password was longer, the statement succeeded, but any excess characters were silently truncated. In MySQL 5.7.5 and later, trying to use a password of more than 32 characters causes CHANGE MASTER TO to fail. (Bug #11752299, Bug #43439)

I was wondering if anyone else had been able to successfully use an IAM authenticated MySQL user on RDS.

Thanks in advance for any support you can provide!

- Wesley

**Comment by wesleyk** [comment]
Hi @dbaltas, thanks for linking the ticket! I understand that there's a limit of 32 characters, however for IAM-based authentication on AWS RDS databases, the provided password that must be used is greater than 32 characters.

I was wondering if anyone had a workaround to still use IAM based auth. I suppose not!

**Comment by shlomi-noach** [comment]
@wesleyk does that password have to be greater than 32 or are 32 characters allowed? In which case 32 is the magic number that is accepted by both?

**Comment by wesleyk** [comment]
Going to close this out as I don't think there's much we can do on the ghost side.
