### ISSUE TITLE
gh-ost occasionally hangs at waitForEventsUpToLock

### ISSUE THREAD

**Issue by wfxiang08** [github/gh-ost#610]
I use gh-ost to migrate tables on my macbook pro, and occasionally find  it hands when at waitForEventsUpToLock

repeatedly print the logs below

> Waiting for events up to lock
> Timeout while waiting for events up to lock

The environment is：
- go version go1.10.3 darwin/amd64
- MacOS Sierra 10.12.6
- MySQL 5.7

After debuging, I found be deadlocks in `migrator.go#iterateChunks#copyRowsFunc#CalculateNextIterationRangeEndValues`

The code in problem is as below:
```go
go this.executeWriteFuncs()
go this.iterateChunks()
if err := retrier(this.cutOver); err != nil {
}
```

cutOver#cutOverTwoStep#LockOriginalTable might lock the Original table before the last call of CalculateNextIterationRangeEndValues, then deadlock might happen.

**Comment by shlomi-noach** [comment]
Closed by #611
