### ISSUE TITLE
run the gh-ost on aws RDS but get error

### ISSUE THREAD

**Issue by yiwenshuo** [github/gh-ost#620]
When I run the gh-ost  on AWS EC2, but get error 

[root@test-dba-ops01 ~]# ./gh-ost --host='10.100.7.40' --port=3306 --user=xxxx --password='xxxxxx' --database='xxxxx'  --execute  --alter="modify column id bigint not null auto_increment"  --table='tb1'
2018-08-02 18:50:11 ERROR Error 1045: Access denied for user 'dbroot'@'%!'(MISSING) (using password: YES)
2018-08-02 18:50:11 ERROR Error 1045: Access denied for user 'dbroot'@'%!'(MISSING) (using password: YES)
2018-08-02 18:50:11 FATAL Error 1045: Access denied for user 'dbroot'@'%!'(MISSING) (using password: YES)

**Comment by yiwenshuo** [comment]
why get  'dbroot'@'%!'(MISSING)  ？

**Comment by shlomi-noach** [comment]
`'dbroot'@'%!'(MISSING)` is an unfortunate sql error text -> `golang` formatting issue. But it is not the actual problem, merely a formatting error for the error message.

Basically it just seems like credentials are wrong.

PS.
RDS or AWS EC2? Which is it?

**Comment by yiwenshuo** [comment]
The AWS's RDS,  I run the same command on mysql ecs mysql， there is not error,but run on aws's rds,got it.

**Comment by shlomi-noach** [comment]
If it's not the credentials (which still look to me as the case), I have no further insight, except suggest that you review https://github.com/github/gh-ost/blob/master/doc/rds.md and possibly https://github.com/github/gh-ost/issues/163

**Comment by yiwenshuo** [comment]
@shlomi-noach  thank you very much ! I have resolved it.

**Comment by shlomi-noach** [comment]
@yiwenshuo can you please comment how you resolved it?

**Comment by apatrida** [comment]
@zeusYi what was the problem?  help out the rest or the community.
