### ISSUE TITLE
How use the gh-ost to transfer  part of data from old table to new  structure table ？

### ISSUE THREAD

**Issue by yiwenshuo** [github/gh-ost#621]
I want to modify a big table primary key from int to bigint ,but just want to migrate  part of data  just like " where id >= 1000000". Does gh-ost have the option like 'where' or 'filter' when migrate data ?

**Comment by shlomi-noach** [comment]
There is no such option. The entire table needs to be migrated.

**Comment by yiwenshuo** [comment]
All the table rows must be migrated ? I just want to migrated  part of rows .

**Comment by tomkrouper** [comment]
`gh-ost` doesn't have a mechanism for partial migrations. Percona's [pt-archiver](https://www.percona.com/doc/percona-toolkit/LATEST/pt-archiver.html) might work for what you are wanting, but `gh-ost` will not.

**Comment by ggunson** [comment]
At GitHub if we want to do this we use both pt-archiver and gh-ost. We first delete the rows we no longer need with pt-archiver, and then we use gh-ost to migrate the smaller table.

**Comment by yiwenshuo** [comment]
@ggunson  you konw the  pt-archiver delete rows very very slowly.

**Comment by tomkrouper** [comment]
@yiwenshuo, the idea behind deleting rows slow is because it doesn't want to cause replication delays.

If having a `--where` clause in `gh-ost` is something you think it needs, we love PR contributions. I'm gonna go ahead and close this issue for now.
