### ISSUE TITLE
Compilation on/for Windows [question]

### ISSUE THREAD

**Issue by andy250** [github/gh-ost#624]
I need to compile this for Windows. I am also totally new to Go language. I quickly tried on a Windows machine but I am getting error about undefined syslog.writer. I found this: https://stackoverflow.com/questions/42083059/getting-syslog-writer-undefined
Does this mean it is impossible to compile gh-ost on windows.  Is it possible to on Linux for Windows?

**Comment by shlomi-noach** [comment]
I do not know whether it's possible or not. What I can tell you, unfortunately, is that Windows is not supported, with no intention of supporting it.

> Is it possible to on Linux for Windows?

Define "Linux for Windows?" 
If it's Linux, it should build.

**Comment by andy250** [comment]
I see, thanks. That's a bummer. "Linux for Windows" --> I mean cross compilation.
