### ISSUE TITLE
what would be occur after long time throttled

### ISSUE THREAD

**Issue by cenkore** [github/gh-ost#627]
This is a question, not report a bug or suggest an enhancement.

`gh-ost version 1.0.45`

if backlog is full `Backlog: 1000/1000` and gh-ost state modify to throttle manually ,the current streamer stable at `Server001-bin.000001.1000` ,then rotate the binlog to `Server001-bin.000002` and purge the `Server001-bin.000001`(by command lsof found no process use this binlog file).

what would be occur?  loss the data between `Server001-bin.000001.1000` and `Server001-bin.000002`?

I'm confused with binlog apply thread whether also throttled or doing someting else after gh-ost throttled ? what's the mechanism ?

Thank you!

**Comment by shlomi-noach** [comment]
> what would be occur?

Did you try?

I expect `gh-ost` to break for not finding the binary log file.

> I'm confused with binlog apply thread whether also throttled or doing someting else after gh-ost throttled ? what's the mechanism ?

When `gh-ost` is throttled it does not read entries from the binary log. It does keep a buffer of entries in memory (`1000` in your case).

**Comment by cenkore** [comment]
Yes ,I tried 2 times .
1st , i throttle gh-ost manually ,and write 1,500 records into the original table, as expected , backlog is full `Backlog: 1000/1000` ,and streamer stable at a position. then purge current binlog . I thought it would be failure or loss 500 records(bug) , but actually it worked fine .  So i'm confused . and 2st , I write far more than 1,500 records ,  and tested the same step like 1st . As your except ,it break for `Could not find first log file name in binary log index file` . Anyway , gh-ost works fine and thanks for your quick reply.

**Comment by shlomi-noach** [comment]
@cenkore I'm afraid we have a language barrier here. From your comment, I got the impression everything worked fine. But then I got this #639, which made me revisit your issue. "Works without complaint" doesn't mean "Works fine". I don't think `gh-ost` worked fine for you.

> then purge current binlog 

You can't purge the current binlog. You can `flush logs` to the next binlog, and then purge all logs _up to the current binlog_. But you can never purge events from the last binlog file. Can you please clarify exactly what you did?

> As your except ,it break for Could not find first log file name in binary log index file

Seems like #629 didn't get that, so I need to see why.

**Comment by shlomi-noach** [comment]
OK now I'm super confused, too. I reproduced the question in similar way to @cenkore:

- initiated `gh-ost` with a `throttle-flag-file` in place
- while `gh-ost` is throttled, injected some `1400` entries
- `gh-ost` was only able to put `1000/1000` in the backlog buffer
- I then flushed binary logs on the gh-ost replica 10 times
- and purged binary logs to the last one

I expected 400 entries to get lost, however:

- `gh-ost` ended up applying `1400` entries. Nice surprise! How?!

In the logs, I see this:
```
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000017, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000017, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000018, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000018, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000019, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000019, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000020, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000020, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000021, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000021, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000022, 4)^[[0m
2018/08/19 12:50:59 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000022, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000023, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000023, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000024, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000024, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000025, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000025, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000026, 4)^[[0m
2018/08/19 12:51:00 binlogsyncer.go:573: ^[[0;37m[info] rotate to (mysql-bin.000026, 4)^[[0m
```

As reminder ,`binlogsyncer.go` is part of `go-mysql`, the underlying library we use for reading the binary logs. And it seems `binlogsyncer` was able to rotate the binary logs 10 times even while `gh-ost` was throttled. This only makes sense if it was able to cache the extra `400` entries `gh-ost` hasn't consumed from it.

So I will be looking into what kind of cache `binlogsyncer` has.

**Comment by shlomi-noach** [comment]
Some added debug messages also show that log rotation took place at the correct end-of-log position per log.

**Comment by shlomi-noach** [comment]
Seems like `go-mysql` uses a buffer at the length of 10240: https://github.com/github/gh-ost/blob/master/vendor/github.com/siddontang/go-mysql/replication/binlogstreamer.go#L57

**Comment by timvaillancourt** [comment]
> It _appears_ to me that there is no bug.

Closing as wont fix. Please open a new issue if you feel there is a bug to tackle
