### ISSUE TITLE
Does gh-ost support incremental, asynchronous offline updating to a slave DB

### ISSUE THREAD

**Issue by andrewv99** [github/gh-ost#630]
Hi,

I would like to know if gh-ost can support this use case:

- The master is running inside a locked down secure network. 
- The slave is running in a separate network, and is used for analysing a copy of all data generated on the master. The slave is only ever used in read only mode - NO changes are made to it - it is a (delayed) exact copy of the master.

I would like to incrementally replicate the changes (schema + data) that occur in the master, by dumping the changes each day into a file(s), copying those files containing the incremental changes to where the slave is, and running a command to apply the incrmental changes stored in those files to the slave.

Is this possible to achieve with gh-ost ?
Thanks

**Comment by shlomi-noach** [comment]
I'm confused.

> I would like to incrementally replicate the changes (schema + data) that occur in the master, by dumping the changes each day into a file(s), copying those files containing the incremental changes to where the slave is, and running a command to apply the incrmental changes stored in those files to the slave.

This just sounds like what replication does.

At any case `gh-ost` does not provide this out of the box. Since I'm unsure exactly what it is you wish to achieve (I'm really confused) I'm not sure what it would take to make `gh-ost` do it.

**Comment by shlomi-noach** [comment]
Got it. Then, these are not master-replica per se.

> As I understand it, the replication facility provided by MySQL expects that incremental replication needs a network connection between master and slave, i.e. it doesn;t support a stored change file(s) that can be applied to a slave at a later time.

Not quite. You can copy the binary logs from the master and just apply them directly on the "replica". Same way as we do "incremental restore from backup".

> I was wanting to know if gh-ost supported anything like that kind of replication use case.

It does not, but seems to me like you don't actually need a tool.

**Comment by andrewv99** [comment]
Thanks  @shlomi-noach for your quick feedback regarding gh-ost and also about the binary logs method - I will look into that option, thanks again.
