### ISSUE TITLE
sha256sum of linux binary release 1.0.42 doesn't match

### ISSUE THREAD

**Issue by esnunes** [github/gh-ost#636]
Hi, I just want to inform that the sha256 checksum of version 1.0.42 in releases page doesn't match for the linux binary file:

```
7a465fda2a6799d0cdf448e5402d6de017b733274ade01c9bc18eb6f0eae6519  gh-ost-binary-linux-20170914095800.tar.gz
```

The expected value:
```
297b14ed1efe9b894e27e63f7aff36ceded7334c174f5a8602af9e74beb2f512  gh-ost-binary-linux-20170914095800.tar.gz
```

I guess the same applies to all other checksums.

**Comment by shlomi-noach** [comment]
@esnunes thanks -- but `sha56sum` seems to reproduce the same checksum as listed. I do, in fact, download the binary, checksum it, and get `297b14ed1efe9b894e27e63f7aff36ceded7334c174f5a8602af9e74beb2f512`.

It is possible your downloaded binary is corrupted, hence the wrong checksum.

**Comment by esnunes** [comment]
Yeah, I'm sorry the file I downloaded was corrupted, that's why I closed the issue.

**Comment by shlomi-noach** [comment]
Cool, thanks. Please drop a note next time to clarify.

**Comment by esnunes** [comment]
Will do, my bad!
