### ISSUE TITLE
Ghost terminates because of critical load by some other client on mysql

### ISSUE THREAD

**Issue by chinmaygupta28** [github/gh-ost#639]
Gh-ost was throttled during peak hours on a very large table (~1bn row data), but it got fatally terminated because of the critical load on mysql master by our application.

So should gh-ost terminate even if its in throttled state, also should it stop if the threads were not created by ghost user on master?
`Copy: 805732100/1190325553 67.7%;`
`Applied: 5116798;`
`Backlog: 1000/1000;`

`Time: 47h0m30s(total), 47h0m29s(copy);`
`streamer: mysql-bin.016961:79466879;`
`State: throttled, flag-file;`
`ETA: 22h26m16s`

`Copy: 805732100/1190325553 67.7%;`
`Applied: 5116798;`
`Backlog: 1000/1000;`

`Time: 47h1m0s(total), 47h0m59s(copy);`
`streamer: mysql-bin.016961:79466879;`
`State: throttled, flag-file;`
`ETA: 22h26m31s`

`Copy: 805732100/1190325553 67.7%;`
`Applied: 5116798;`
`Backlog: 1000/1000;`

`Time: 47h1m30s(total), 47h1m29s(copy);`
`streamer: mysql-bin.016961:79466879;`
`State: throttled, flag-file;`
`ETA: 22h26m45s`

`Copy: 805732100/1190325553 67.7%;`
`Applied: 5116798;`
`Backlog: 1000/1000;`

`Time: 47h2m0s(total), 47h1m59s(copy);`
`streamer: mysql-bin.016961:79466879;`
`State: throttled, flag-file;`
`ETA: 22h26m59s`

`Copy: 805732100/1190325553 67.7%;`
`Applied: 5116798;`
`Backlog: 1000/1000;`

`Time: 47h2m30s(total), 47h2m29s(copy);`
`streamer: mysql-bin.016961:79466879;`
`State: throttled, flag-file;`
`ETA: 22h27m13s`

`2018-09-13 22:59:55 ERROR critical-load met once: Threads_running=1006, >=1000. Will check again in 5000 millis`
`2018-09-13 22:59:56 ERROR critical-load met once: Threads_running=1000, >=1000. Will check again in 5000 millis`
`2018-09-13 22:59:59 ERROR critical-load met once: Threads_running=1001, >=1000. Will check again in 5000 millis`
`2018-09-13 23:00:00 ERROR critical-load met once: Threads_running=1005, >=1000. Will check again in 5000 millis`
`2018-09-13 23:00:00 FATAL critical-load met again after 5000 millis: Threads_running=1006, >=1000`

**Comment by shlomi-noach** [comment]
> So should gh-ost terminate even if its in throttled state, also should it stop if the threads were not created by ghost user on master?

That's for you to answer. 

BTW, we do not terminate on critical load anymore, we go hibernating, via `-critical-load-hibernate-seconds`.

**Comment by chinmaygupta28** [comment]
This flag solves  this use case.
