### ISSUE TITLE
An Option should be added to throttle or panic at a certain Disk Used amount

### ISSUE THREAD

**Issue by Jericon** [github/gh-ost#645]
It would be useful if there was an option to specifically throttle or panic an alter when the disk reaches a certain amount of fullness.

**Comment by shlomi-noach** [comment]
The way we run `gh-ost` is from a remote box, aka a "utility box", and not actually on a MySQL box. Thus, in our case, `gh-ost` does not have visibility into disk space issues.

I suggest one of the following:

- Use your own custom scripting to generate a throttle file, or
- Use your own custom scripting to invoke a `echo throttle | socat - /tmp/THE_GH_OST_SOCKET_FILE`, or
- Suggest a PR. I'd expect `gh-ost` should be told what mount point it should be observing and what disk space threshold it should throttle on.

**Comment by Jericon** [comment]
@shlomi-noach Using a custom script to generate a throttle file worked perfectly for this.  Thank you for that alternative.
