### ISSUE TITLE
Use case question.

### ISSUE THREAD

**Issue by chrhlnd** [github/gh-ost#649]
How far away is ghost from being used as a slave creator.

1) Connect to slave/master, replicate to table(s) another slave/instance.

2) After rename to proper table name, stop replication sql join the created table(s) into the replication rules, start replication sql.

Maybe this use case already works?

**Comment by shlomi-noach** [comment]
`gh-ost` is far away from this. But perhaps https://github.com/Shopify/ghostferry is closer (though still not there).
