### ISSUE TITLE
The value of GO_PKG_DARWIN_SHA in ./script/ensure-go-installed is not correct

### ISSUE THREAD

**Issue by jrgm** [github/gh-ost#662]
The value of GO_PKG_DARWIN_SHA in ./script/ensure-go-installed is not correct, and so my build fails on Darwin.

This is the same change as https://github.com/github/orchestrator/pull/613/files (although the .gitignore changes there are unneeded in this repo, and doesn't include the debug change which I could add if you'd prefer).

**Comment by shlomi-noach** [comment]
fixed by #663 

Thank you
