### ISSUE TITLE
How to modify cloumn named with reserved words?

### ISSUE THREAD

**Issue by AlfredWu** [github/gh-ost#690]
how to modify cloumn with named by reserved words?

I tried to use backticks but not working.

```
gh-ost  --user="xx" --password="xx" --host=localhost --port=3309  --allow-on-master --serve-socket-file=/tmp/gh-ost.sock --panic-flag-file=/tmp/gh-ost.panic.flag --database="xx" --table="xxx"  --alter='modify "`desc`" varchar(1000) NULL' --initially-drop-ghost-table --initially-drop-old-table --execute  --verbose
```

What I got:
FATAL Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"`desc`" varchar(1000) NULL' at line 1

Please advise.

**Comment by shlomi-noach** [comment]
The way I read this, you have:
```
 --alter='modify "`desc`" varchar(1000) NULL'
```
what happens if you run:
```
 --alter='modify `desc` varchar(1000) NULL'
```

?

**Comment by AlfredWu** [comment]
yes it did work with --alter='modify column `desc` varchar(1000) NULL'
Thank you very much.
