### ISSUE TITLE
Utilize MySQL 8 RENAME TABLE supporting locks

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#714]
MySQL 8 (as of `8.0.13`) introduced a change where `RENAME TABLE` is possible while holding a `WRITE LOCK`. This has been targeted specifically for `gh-ost`. See https://dev.mysql.com/doc/refman/8.0/en/rename-table.html and https://mysqlserverteam.com/the-mysql-8-0-13-maintenance-release-is-generally-available/

`gh-ost` should utilize this new feature on `>= 8.0.13`.

This will potentialy solve https://github.com/github/gh-ost/issues/687

**Comment by breisig** [comment]
We are using MySQL 8.0.15 and is essential to get fixed and released.

**Comment by shlomi-noach** [comment]
According to my tests `gh-ost` supports MySQL `8.0.16` and `8.0.18`, so I'm closing this issue.
