### ISSUE TITLE
Intermittent failures in localtests

### ISSUE THREAD

**Issue by zmoazeni** [github/gh-ost#753]
Per #750 I was going to try digging into some possible causes for the intermittent failures in localtests.

I now have a way to reliable reproduce it. https://github.com/zmoazeni/gh-ost/commit/b3955d1f0b6aee54d96f2b359a5e739eeaaabed5

If you read the commit, it'll explain how to reproduce (just run `./force-failure`). It may take ~4-15 iterations before you run into the issue. It doesn't take that long. About a minute or two.

The problem seems to be in https://github.com/github/gh-ost/blob/ffc6c40150efb149321a2f32103b98424d6652b1/go/logic/applier.go#L711-L723

The timing issue is that at the time we query, the sessionId _does_ exist, however neither the `state` nor the `info` columns are populated. So we end up getting no rows/`found=false` based on our hints in the where clause and we return an error.

Update: A followup query _does_ include both. Which made it hard to debug at first, but I decided to push the logic into Go instead which highlighted the problem.

Here's the output of a full run for me that failed on the 3rd attempt (it says 2nd attempt, but...off by one errors :/)

https://gist.github.com/zmoazeni/e40ba08113bc5f8e3843443d51e03b66

---

I wonder what you think @shlomi-noach (or anyone else). Do you think we should retry this query? Should we do some special handling on the hint criteria? Something else entirely?

**Comment by zmoazeni** [comment]
Two things worked for me to fix this (50 uninterrupted test runs).

* Changing `--default-retries=2` https://github.com/github/gh-ost/blob/master/localtests/test.sh#L155
* Adding a manual sleep `time.Sleep(250 * time.Millisecond)` before this line https://github.com/github/gh-ost/blob/master/go/logic/applier.go#L722

Of the two, I think the 2nd probably makes more sense. Though it's still a guess how long it should wait (unless we make it a command line parameter). I don't know if allowing retries in the localtests is the right approach.

There may be a more appropriate way to deal with this by not using the hints for the query. I'm not sure how you feel about that.

**Comment by shlomi-noach** [comment]
@zmoazeni thank you for investigating!

> I wonder what you think @shlomi-noach (or anyone else). Do you think we should retry this query? 

The query is indeed being retried as per:

https://github.com/github/gh-ost/blob/ffc6c40150efb149321a2f32103b98424d6652b1/go/logic/migrator.go#L654-L667

> I don't know if allowing retries in the localtests is the right approach.

I'm surprised to see `--default-retries=1` in the localtests. I seem to have added this 3 years ago in https://github.com/github/gh-ost/commit/2faa27a2c402506518113cc4f2afb286825c387e, but I did not explicitly comment about this and I don't have a recollection of why this was done.

I'm all for using `--default-retries=3` (because why not).
Yeah, retries are perfectly legit.
