### ISSUE TITLE
Is it possible to filter migrated rows?

### ISSUE THREAD

**Issue by FortuneOSarcasm** [github/gh-ost#756]
Hi there, is it possible to filter the rows migrated to the new table structure in gh-ost?
Something similar to mysqldump's --where 

My Scenario
I have a large table that contains quite a few years worth of data to make a change on so what I would like to do is run gh-ost to alter the table structure but only copy data for the last year.
I will then archive off the older data from the _<tablename>_del table before I drop it and live operations will continue on the now smaller table with the changes applied.

Thanks in advance

**Comment by shlomi-noach** [comment]
it is not possible right now. See https://github.com/github/gh-ost/issues/621
But there's a contributed PR (which I haven't tested): https://github.com/github/gh-ost/pull/718

**Comment by FortuneOSarcasm** [comment]
Thanks very much.
