### ISSUE TITLE
throttled for lag, but no replica has such lag

### ISSUE THREAD

**Issue by acharis** [github/gh-ost#766]
Running v1.0.48
```
Copy: 36734000/10544533 348.4%; Applied: 21368; Backlog: 0/1000; Time: 6h18m0s(total), 6h18m0s(copy); streamer: vt-1093751700-bin.000543:678917658; State: throttled, lag=3715.636286s; ETA: due
```
But neither of the replicas is lagged by more than 2s.

**Comment by shlomi-noach** [comment]
Could there be a clock synchronization issue? Could there be replicas in a different timezone?

**Comment by zmoazeni** [comment]
Here's another possibility. We're returning the replication lag from `show slave status` which can be known to be just an approximation of lag.

https://github.com/github/gh-ost/blob/b38814f90ebfd429bd1bdf0ebd258472e5bb3965/go/mysql/utils.go#L62-L75 

* https://dba.stackexchange.com/a/64456
* https://www.percona.com/doc/percona-toolkit/LATEST/pt-heartbeat.html

I definitely +1 to double check Shlomi's suggestions. But if we end up pulling our hair out it might be that we got caught in one of those edgecases.

**Comment by acharis** [comment]
no clock sync issues; all replicas in same tz.
i haven't seen this again. happy to close now, and re-open if we do.

i assume setting throttle-control-replicas will make it pay attention to _only_ those replicas, rather than do any replication crawling.
