### ISSUE TITLE
incorrect estimate of number of rows

### ISSUE THREAD

**Issue by acharis** [github/gh-ost#767]
Running v1.0.48
```
Copy: 36734000/10544533 348.4%; Applied: 21368; Backlog: 0/1000; Time: 6h19m0s(total), 6h19m0s(copy); streamer: vt-1093751700-bin.000543:678917658; State: throttled, lag=3775.636445s; ETA: due
```

The table has ~41M rows, but upon startup, gh-ost only seems to have found ~10M.

**Comment by shlomi-noach** [comment]
Did you use [exact-rowcount](https://github.com/github/gh-ost/blob/master/doc/command-line-flags.md#exact-rowcount)?

**Comment by acharis** [comment]
i did not, my bad.
