### ISSUE TITLE
Can Gh-ost merge tables?

### ISSUE THREAD

**Issue by andrewg1024** [github/gh-ost#849]
Hello!

New to Gh-ost, so bear with me.

The feature of Gh-ost I am most interested in is the **zero downtime**. And I have a requirement to merge large, similar tables. When I say 'similar', one table can have 100 columns, and another 106 columns, where 100 columns are the same datatype/size/domain on each table. Each Tables Primary Key would be unique, so no unique key issues are anticipated.

So, I know Gh-ost can be used to add columns to the 100 column table to bring it in line with the 106 column table. And I know Gh-ost can use hooks. But, there appears no hooks that can be fired on every row copied it seems?

My question is then: **can Gh-ost be used to clone/copy data from a second table, while is it changing the schema of the target, without causing block Lock issues on either table?**

With thanks in advance,
Andrew G
DBA

**Comment by tomkrouper** [comment]
@andrewg1024, that is out of the scope of gh-ost's functionality. I also don't think that [ghostferry](https://github.com/Shopify/ghostferry) by Shopify could do that either. But, honestly I haven't done a lot with ghostferry, so you might want to look at their docs. It sounds like a pretty complicated problem. Good luck.

**Comment by timvaillancourt** [comment]
Closing issue as answered. PRs are welcome if you'd like to tackle this
