### ISSUE TITLE
got connect: connection timed out on aliyun rds

### ISSUE THREAD

**Issue by EthenQ** [github/gh-ost#852]
when i try gh-ost on aliyun rds 
`
./gh-ost --user="user" --password="pass" --host=rm-xxx.mysql.rds.aliyuncs.com --port=3306 --database="db" --table="test"  --alter="ALTER TABLE test ADD cid varchar(50) comment 'cid';"  --exact-rowcount --serve-socket-file=/tmp/gh-ost.sock   --postpone-cut-over-flag-file=/tmp/gh-ost.postpone --aliyun-rds --assume-rbr --allow-on-master  –-assume-master-host="rm-xxx.mysql.rds.aliyuncs.com:3306" --ssl --ssl-allow-insecure --execute
`

i got
```
2020-06-11 22:46:00 ERROR dial tcp 11.200.167.195:3099: connect: connection timed out
2020-06-11 22:46:00 FATAL dial tcp 11.200.167.195:3099: connect: connection timed out
```
but i have no idea about  11.200.167.195 ,but found it is an  ip from US

**Comment by MoeMoeFish** [comment]
could you send some running result with --verbose flag?

**Comment by EthenQ** [comment]
sorry， i have no chance to try it again
