### ISSUE TITLE
why sync binlog set master_binlog_checksum=NONE

### ISSUE THREAD

**Issue by soocold** [github/gh-ost#870]
I find this code in binlogsyncer.log :
```SQL
SHOW GLOBAL VARIABLES LIKE 'BINLOG_CHECKSUM'
SET @master_binlog_checksum='NONE'
```
I'm very confused about why sync binlog not use checksum ?

**Comment by shlomi-noach** [comment]
`binlogsyncer` is a 3rd party library, https://github.com/siddontang/go-mysql. I suggest asking in that repo.

**Comment by soocold** [comment]
thx

**Comment by soocold** [comment]
> `binlogsyncer` is a 3rd party library, https://github.com/siddontang/go-mysql. I suggest asking in that repo.

thx
