### ISSUE TITLE
support GET to HTTP throttle

### ISSUE THREAD

**Issue by takaidohigasi** [github/gh-ost#874]
http-throttle flag support `HEAD` request now

> The --throttle-http flag allows for throttling via HTTP. Every 100ms gh-ost issues a HEAD request to the provided URL. If the response status code is not 200 throttling will kick in until a 200 response status code is returned.
https://github.com/github/gh-ost/blob/master/doc/throttle.md#http-throttle

if it support `GET` request, it's easy to use.

**Comment by shlomi-noach** [comment]
The reason it issues a `HEAD` and not `GET` is to skip the extra traffic. We're only interested in status code, and avoid downloading a response. Since we run this request every `100ms` this can be beneficial.
