### ISSUE TITLE
Dynamic lock timeout idea with the final table swap 

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#88]
There was discussion in a chat room about the lock wait timeout and retry settings for gh-ost: can these be set dynamically, rather than hardcoded. 

Here's an idea:
1. Have a lowish lock_wait_timeout value; currently it's 3 seconds in the code.
2. Start the lock and swap sequence, where it's blocked waiting for the rest of the log to get parsed and changes run on the ghost table.
3. Have the processlist on the master polled regularly; if it sees a certain number of threads in "Waiting on metadata lock" state, timeout the lock/swap process and retry after a period.

A few thoughts/concerns:
1. We might want configurable settings for
- lock-wait-timeout (if not already there)
- max-waiting-threads-at-swap
- wait-before-retry
- retry-count?
1. Are there any other waiting process states that could occur from the lock and swap scenario? (lock tables and DDL will cause that, but mentioning the possibility anyways).

**Comment by ggunson** [comment]
I think this can be closed?

**Comment by shlomi-noach** [comment]
Yes, I'll closing. The suggestion is sound, but in practice we see that the cut-over works well, and I've seen (also by user reports) how the timeout works well, too.
