### ISSUE TITLE
Ghost table is many times bigger than original table

### ISSUE THREAD

**Issue by dinesh-rdk** [github/gh-ost#890]
**Info:** I am using AWS RDS Mysql 5.6.34 (500GB) instance (Without replica, just the master)
**Note:** Binlog is enabled & set to Row
**Target:** Modify a column `field_1` from enum to tinyint
**Extra info:** I am using Rails application. So everytime I wanted to add a value to the enum, I need to write a migration. So converting the enum field to tinyint so I can add or delete a enum value without writing a migration using [Active Enum](https://github.com/adzap/active_enum)
**Other info:** I also tried [LHM](https://github.com/soundcloud/lhm) but the RDS instance went out of memory at 93%

Database info before running gh-ost:
```sql
mysql> select table_schema, sum((data_length+index_length)/1024/1024) AS MB from information_schema.tables group by 1;
+--------------------+-----------------+
| table_schema       | MB              |
+--------------------+-----------------+
| information_schema |      0.00976560 |
| mysql              |      5.96277428 |
| performance_schema |      0.00000000 |
| my_app_db          | 223941.79882818 |
+--------------------+-----------------+
```

Size of the original table before gh-ost: (showing only the table needed to be modified from the list)
```sql
mysql> SELECT table_name AS `Table`, round(((data_length + index_length) / 1024 / 1024), 2) `Size (MB)` FROM information_schema.TABLES WHERE table_schema = "my_app_db";
+----------------------------------------+-----------+
| Table                                  | Size (MB) |
+----------------------------------------+-----------+
| table_abc                              |     70.41 |
| my_table                               |  86058.73 |
```

Started the migration:
```bash
gh-ost \
--user="user" \
--password="password" \
--host="my-endpoint.rds.amazonaws.com" \
--database="my_app_db" \
--table="my_table" \
--alter="MODIFY field_1 TINYINT(2) DEFAULT 1 NOT NULL" \
--assume-rbr \
--allow-on-master \
--verbose \
--execute
```

When the migration was nearly 93% complete, the RDS free-memory went down to 20GB. So I stopped gh-ost.

Database info after stopping gh-ost:
```sql
mysql> select table_schema, sum((data_length+index_length)/1024/1024) AS MB from information_schema.tables group by 1;
+--------------------+-----------------+
| table_schema       | MB              |
+--------------------+-----------------+
| information_schema |      0.00976560 |
| mysql              |      5.96277428 |
| performance_schema |      0.00000000 |
| my_app_db          | 446299.17968756 |
+--------------------+-----------------+
```

Size of the original table after stopping gh-ost:
```sql
mysql> SELECT table_name AS `Table`, round(((data_length + index_length) / 1024 / 1024), 2) `Size (MB)` FROM information_schema.TABLES WHERE table_schema = "my_app_db";
+----------------------------------------+-----------+
| Table                                  | Size (MB) |
+----------------------------------------+-----------+
| _my_table_ghc                       |      0.41 |
| _my_table_gho                       | 273157.00 |
| my_table                            |  85011.62 |
```

### Question:

Why is the gh-ost table many times larger than the original table?

If more info is required about the table, index or database, I can provide :+1:

**Comment by shlomi-noach** [comment]
I don't have insight into why this would happen. I'm inclined to believe this is a RDS-specific problem. And as you may know, the `information_schema` `innodb` metrics are skewed, and I've seen mismatches of `2*` and more in size estimates.

I don't suppose you can look into the `*.ibd` file size?

Can you randomly 
- `mysql -e "SELECT * FROM my_table ORDER BY id LIMIT 10000" | wc'
- `mysql -e "SELECT * FROM _my_table_gho ORDER BY id LIMIT 10000" | wc' 
just to see that table content makes sense?

**Comment by dinesh-rdk** [comment]
@shlomi-noach 

```bash
mysql -e "SELECT * FROM my_table ORDER BY id LIMIT 10000" | wc
  10001  280421 11111217
mysql -e "SELECT * FROM _my_table_gho ORDER BY id LIMIT 10000" | wc
  10001  280421 11014952
```

**Comment by shlomi-noach** [comment]
if we just extrapolate from the above, then the data seems legit, and the `information_schema` numbers are skewed and do not represent reality. To confirm, keep on comparing various parts of the tables.

**Comment by dinesh-rdk** [comment]
Let me check if I can look into the *.ibd file size as well.
And sure I will compare various parts of the tables & check.
Thanks for the help. I will let you know if I find anything :+1:

**Comment by dinesh-rdk** [comment]
Thanks for this awesome tool.
The issue was with the mysql parameter group. More info -> https://stackoverflow.com/a/65103462/5098595
