### ISSUE TITLE
Manually building gh-ost on go1.16 requires special configuration

### ISSUE THREAD

**Issue by natewernimont-wk** [github/gh-ost#933]
As of [go1.16](https://golang.org/doc/go1.16#go-command), go modules are defaulted to be enabled. This means that any consumer manually packaging gh-ost needs to override `GO111MODULE`. Additionally, go modules are the now standard approach to dependency management in go. It would be nice to move to go modules.

**Comment by shlomi-noach** [comment]
My personal thoughts shared on the PR: https://github.com/github/gh-ost/pull/932#issuecomment-786069468

**Comment by timvaillancourt** [comment]
@natewernimont-wk this is resolved with the merge of https://github.com/github/gh-ost/pull/966

Moving to `go mod` will continue in https://github.com/github/gh-ost/pull/966
