### ISSUE TITLE
Does github store binary logs of its databases from day-1 forever ?

### ISSUE THREAD

**Issue by none-da** [github/gh-ost#943]
Hello,

Thanks for your hard work on `gh-ost`! 

I have recently started exploring gh-ost and I have a question on the binary logs. Since gh-ost is very much dependent on binary logs, does github store binary logs of its databases since day-1 ? This question also stems from the question, can gh-ost be used (now or in future) in cases where I have binary logs only with X days retention and still want to perform online-migrations using gh-ost.

Thanks for your time and consideration!

**Comment by xinwu5** [comment]
Hi @none-da , with different server roles, it stores binary logs differently. The setting is called `expire_logs_days`, you can find it on https://github.com/github/puppet/search?q=expire_logs_days. 
```
Replica: 1d
Backup: 4d
Analytics: 1d
Primary: 4d
```
Normall `gh-ost` would read the binlog directly, and only if there is a pause, or some issues it stopped, then you need `expire_logs_days` to store enough data before it starts run again. 

https://github.com/github/gh-ost/blob/master/doc/throttle.md#how-long-can-you-throttle-for This may give you more details.

Hope this answers your question.

**Comment by xinwu5** [comment]
Hi @none-da ,

Normally gh-ost would read the binlog directly, and only if there is a pause or some issues it stops, then you need `expire_logs_days` to store enough data before it starts to run again.

https://github.com/github/gh-ost/blob/master/doc/throttle.md#how-long-can-you-throttle-for This may give you more details.

Hope this answers your question.

**Comment by none-da** [comment]
Thanks for the prompt response @xinwu5. Its still not clear to me. Let me explain:
1. Lets say the db has 3 days as retention period for bin logs
2. Now 1 month later (like on 33rd day lets say) you want to do online migration using gh-ost.
3. Since the retention period of bin logs is just 3 days, you dont have bin logs from day 1. This is required to create the (new) gh-ost table right ? 

How `gh-ost` behaves in this scenario ? Would it crash ? or would it create the `gh-ost` table with just the last 3 days worth of data (that is pulled from bin logs) ?

**Comment by fighterleslie** [comment]
> Thanks for the prompt response @xinwu5. Its still not clear to me. Let me explain:
> 
> 1. Lets say the db has 3 days as retention period for bin logs
> 2. Now 1 month later (like on 33rd day lets say) you want to do online migration using gh-ost.
> 3. Since the retention period of bin logs is just 3 days, you dont have bin logs from day 1. This is required to create the (new) gh-ost table right ?
> 
> How `gh-ost` behaves in this scenario ? Would it crash ? or would it create the `gh-ost` table with just the last 3 days worth of data (that is pulled from bin logs) ?

As far as I know, `gh-ost` doesn't need the bin log from day 1. `gh-ost` only applied the new changes from the bin log, and copied existent rows directly from the tables.

Quote the README:

> All existing online-schema-change tools operate in similar manner: they create a _ghost_ table in the likeness of your original table, migrate that table while empty, slowly and incrementally copy data from your original table to the _ghost_ table, meanwhile propagating ongoing changes (any `INSERT`, `DELETE`, `UPDATE` applied to your table) to the _ghost_ table. Finally, at the right time, they replace your original table with the _ghost_ table.

**Comment by none-da** [comment]
@shlomi-noach any thoughts on this ?

**Comment by shlomi-noach** [comment]
@fighterleslie is correct. The history of binary logs is irrelevant. No one has their entire binary logs history, everyone purges binary logs. It would be virtually impossible to run `gh-ost` if it required all historical binary logs.

When `gh-ost` starts, it takes a look at the _current_ binlog position. Anything before that is irrelevant. During runtime, `gh-ost` advances along with the binary logs. Normally, it is able to keep in pace with new binlog entry rate. Under load, it may lag behind, as far as a few binary logs.

What's important is that you shouldn't purge binary logs `gh-ost` hasn't processed yet. `gh-ost` tells you which file:pos it is processing once per minute, on the status output line.

BTW `gh-ost` prioritizes processing of binary logs over copying of row data.

Last, I think a quick experiment could have shown you that this works as expected. Good luck!

**Comment by none-da** [comment]
> Last, I think a quick experiment could have shown you that this works as expected. Good luck!
Thanks for the input @shlomi-noach. Yes, I tried and it does seem to copy rows in chunks from the origin/replica table into the ghost table. Found these log lines proving the same 👇 
```
ghost            | # Migrating `try_osc`.`referringitem`; Ghost table is `try_osc`.`_referringitem_gho`
ghost            | # Migrating vanila-minikube:3307; inspecting vanila-minikube:3308; executing on vanila-minikube
ghost            | # Migration started at Thu Apr 01 18:07:02 +0000 2021
ghost            | # chunk-size: 1000; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: ; critical-load: ; nice-ratio: 0.000000
ghost            | # throttle-additional-flag-file: /tmp/gh-ost.throttle
ghost            | # Serving on unix socket: /tmp/gh-ost.try_osc.referringitem.sock
ghost            | 2021-04-01 18:07:02 DEBUG Getting nothing in the write queue. Sleeping...
ghost            | Copy: 0/10 0.0%; Applied: 0; Backlog: 0/1000; Time: 0s(total), 0s(copy); streamer: bin.000003:9690; Lag: 0.03s, State: migrating; ETA: N/A
ghost            | 2021-04-01 18:07:03 DEBUG Issued INSERT on range: [1]..[10]; iteration: 0; chunk-size: 1000
ghost            | 2021-04-01 18:07:03 DEBUG Iteration complete: no further range to iterate
ghost            | 2021-04-01 18:07:03 DEBUG Getting nothing in the write queue. Sleeping...
ghost            | 2021-04-01 18:07:03 INFO Row copy complete
```
