### ISSUE TITLE
unix socket file does not get cleaned up

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#95]
`gh-ost` termination, at least orderly one, should clean up and remove unix socket file.

**Comment by sjmudd** [comment]
Shlomi, table names may not be unique though I guess the chances of OSC type collisions on same named tables (in different databases) on the same server are quite small maybe it might be better to use some sort of hash based on the database + table name to ensure uniqueness?

I have also seen tables named with spaces and other "non-unix" type characters so using this type of name might best be avoided if possible even if technically unix allows you to use them.

Just a thought.

**Comment by shlomi-noach** [comment]
@sjmudd the unix socket name is already based on `database_name.table_name` so no uniqueness problem here.

If you have spaces etc, then it's on you: provide your own `--serve-socket-file` rather than let `gh-ost` decide on the name.

**Comment by shlomi-noach** [comment]
Closed by https://github.com/github/gh-ost/pull/147
