### ISSUE TITLE
Unwanted directories added to RPM

### ISSUE THREAD

**Issue by yakirgb** [github/gh-ost#953]
When creating an RPM,  unwanted directories and files of `/usr/lib/.build-id/` are included in the RPM, .
```
[root@u1 ~]# rpm -ql gh-ost-1.1.2-1
/usr/bin/gh-ost
/usr/lib/.build-id
/usr/lib/.build-id/c4
/usr/lib/.build-id/c4/dd5acac09d7d035b4a07fdce618a4eab59366c
```
Based on: https://fedoraproject.org/wiki/Releases/FeatureBuildId and https://fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo
Add `--rpm-rpmbuild-define "_build_id_links none"` to `fpm` should fix the issue

**Comment by timvaillancourt** [comment]
This was resolved in https://github.com/github/gh-ost/pull/954
