### ISSUE TITLE
Is it possible to use gh-ost as a Go library directly?

### ISSUE THREAD

**Issue by shakefu** [github/gh-ost#959]
I know the main documentation is around the `gh-ost` CLI tool, but I'm wondering if there are any concerns about using the library directly (e.g. the `MigrationContext`+`Migrator` API which the CLI leverages), especially w/r to trying to run multiple migrations from within a single process context (e.g. are there shared globals that might have issues? thread/goroutine blocking? unsafe/unlocked vars?).

My use case is that I'd like to write a small migration management (internal) web app to integrate with `gh-ost` and it seems like invoking the CLI tool and then communicating over the unix/TCP socket would be a bit more wonky than just being able to import the golang lib and work with it that way.

**Comment by shlomi-noach** [comment]
Please see the following (rather old) issues:

- https://github.com/github/gh-ost/issues/577
- #465 
- #526 

Personally I haven't experimented running `gh-ost` as a library. Happy to hear about your review/experiment.

**Comment by shakefu** [comment]
Good to know!

Without using it as a library can I ask how y'all are running `gh-ost` in production? Some wrapper tooling maybe? Running the CLI in a container perhaps? We're trying to solve the production use case as well but in a not-quite-fully-automated fashion (hence a use case of a web app).

**Comment by shlomi-noach** [comment]
This is how GitHub does it:
https://github.blog/2020-02-14-automating-mysql-schema-migrations-with-github-actions-and-more/

**Comment by shakefu** [comment]
> This is how GitHub does it: https://github.blog/2020-02-14-automating-mysql-schema-migrations-with-github-actions-and-more/

Oh that's an awesome writeup! Thanks!

**Comment by shakefu** [comment]
Whoops. Leaving open to for reporting back on how it went with `gh-ost` as a library. Will close in a few days if that doesn't proceed.

**Comment by timvaillancourt** [comment]
Closing this questions as answered
