### ISSUE TITLE
Communist Vietnamses's Get out of Vietnam... let the jungle monkeys debug their brains 

### ISSUE THREAD

**Issue by use931** [github/gh-ost#980]
> This is the place to report a bug, ask a question, or suggest an enhancement.

> This is also the place to make a discussion before creating a PR.

> If this is a bug report, please provide a test case (e.g., your table definition and gh-ost command) and the error output.

> Please use markdown to format code or SQL: https://guides.github.com/features/mastering-markdown/

> Please label the issue on the right (bug, enhancement, question, etc.).

> And please understand if this issue is not addressed immediately or in a timeframe you were expecting.

> Thank you!

**Comment by shlomi-noach** [comment]
@timvaillancourt please make sure to block these users, you should be able to do so as admin of this repo.

**Comment by timvaillancourt** [comment]
@shlomi-noach sounds good 👍. For some reason I can only `Report Content` but I'll keep looking

I've reported this as inappropriate content in the meantime
